use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use anyhow::Result;

use crate::model::{Ir, Property, Shape};

/// Emit a self-contained Go package containing the public AHP models and codecs.
///
/// The generated decoder deliberately performs only the structural checks represented
/// by the codegen IR. Unknown object members, open-enum values, and discriminator
/// variants are retained so a decode/encode cycle does not discard forward-compatible data.
pub fn emit(ir: &Ir) -> Result<String> {
    let mut generator = Generator::new(ir);
    let mut named_types = ir.types.iter().collect::<Vec<_>>();
    named_types.sort_by_key(|named| (named.name.as_str(), named.source.as_str()));
    for named in named_types {
        let go_name = generator.named_name(&named.name);
        generator.emit_named(&go_name, named.source.as_str(), &named.shape)?;
    }

    let descriptors = ir
        .types
        .iter()
        .map(|named| {
            (
                named.name.clone(),
                serde_json::to_value(&named.shape).expect("shape serializes"),
            )
        })
        .collect::<BTreeMap<_, _>>();
    let descriptor_json = serde_json::to_string(&descriptors)?;

    let mut output = String::new();
    writeln!(output, "// Code generated by ahp-codegen. DO NOT EDIT.")?;
    writeln!(
        output,
        "// Generated from AHP schema {}.",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "// The source schema is authoritative if this output conflicts with it."
    )?;
    writeln!(output, "package ahp\n")?;
    output.push_str(IMPORTS);
    writeln!(
        output,
        "const SchemaRevision = {}",
        go_string(&ir.schema_revision)?
    )?;
    writeln!(
        output,
        "const ProtocolVersionValue = {}\n",
        go_string(&ir.protocol_version)?
    )?;
    output.push_str(PRELUDE);
    for declaration in &generator.declarations {
        output.push_str(declaration);
    }
    writeln!(
        output,
        "var schemaDescriptors = loadSchemaDescriptors({})\n",
        go_string(&descriptor_json)?
    )?;
    output.push_str(RUNTIME);

    let mut roots = ir.roots.iter().collect::<Vec<_>>();
    roots.sort_by_key(|root| (root.name.as_str(), root.schema.as_str()));
    for root in roots {
        let root_name = generator.named_name(&root.name);
        writeln!(
            output,
            "// Parse{root_name} parses and structurally checks one {root_name} JSON document."
        )?;
        writeln!(
            output,
            "func Parse{root_name}(input []byte) ParseResult[{root_name}] {{"
        )?;
        writeln!(
            output,
            "\treturn parseRoot[{root_name}]({}, input)",
            go_string(&root.name)?
        )?;
        writeln!(output, "}}\n")?;
        writeln!(
            output,
            "// Encode{root_name} encodes value without applying schema defaults."
        )?;
        writeln!(
            output,
            "func Encode{root_name}(value {root_name}) ([]byte, error) {{"
        )?;
        writeln!(output, "\treturn json.Marshal(value)")?;
        writeln!(output, "}}\n")?;
        writeln!(output, "const {root_name}SchemaRevision = SchemaRevision\n")?;
    }
    if output.ends_with("\n\n") {
        output.pop();
    }

    Ok(output)
}

struct Generator<'a> {
    ir: &'a Ir,
    named_names: BTreeMap<String, String>,
    used_names: BTreeSet<String>,
    declarations: Vec<String>,
}

impl<'a> Generator<'a> {
    fn new(ir: &'a Ir) -> Self {
        let mut used_names = runtime_names();
        let mut named_names = BTreeMap::new();
        let root_names = ir
            .roots
            .iter()
            .map(|root| root.name.as_str())
            .collect::<BTreeSet<_>>();
        let mut ordered = ir.types.iter().collect::<Vec<_>>();
        ordered.sort_by_key(|named| {
            (
                !root_names.contains(named.name.as_str()),
                named.name.as_str(),
            )
        });
        for named in ordered {
            let base = go_identifier(&named.name);
            let allocated = if root_names.contains(named.name.as_str()) {
                allocate_root_name(&base, &mut used_names)
            } else {
                allocate_local_name(&base, &mut used_names)
            };
            named_names.insert(named.name.clone(), allocated);
        }
        Self {
            ir,
            named_names,
            used_names,
            declarations: Vec::new(),
        }
    }

    fn named_name(&self, name: &str) -> String {
        self.named_names
            .get(name)
            .cloned()
            .unwrap_or_else(|| go_identifier(name))
    }

    fn emit_named(&mut self, name: &str, source: &str, shape: &Shape) -> Result<()> {
        if let Some(properties) = self.structural_properties(shape, &mut BTreeSet::new()) {
            self.emit_struct(name, Some(source), properties)?;
        } else if matches!(shape, Shape::Literal { .. } | Shape::Enum { .. }) {
            self.emit_value_type(name, Some(source), shape)?;
        } else if let Shape::Union { .. } = shape {
            self.emit_union(name, Some(source), shape)?;
        } else {
            let rendered = self.render_type(shape, &format!("{name}Value"))?;
            let mut declaration = String::new();
            writeln!(declaration, "// {name} is generated from {source}.")?;
            writeln!(declaration, "type {name} = {rendered}\n")?;
            self.declarations.push(declaration);
        }
        Ok(())
    }

    /// Flatten object intersections for useful root models. Duplicate property
    /// constraints are intersected commutatively and requiredness is cumulative.
    fn structural_properties(
        &self,
        shape: &Shape,
        visiting: &mut BTreeSet<String>,
    ) -> Option<Vec<Property>> {
        match shape {
            Shape::Object { properties, .. } => Some(properties.clone()),
            Shape::Intersection { variants } => {
                let mut merged = Vec::<Property>::new();
                for variant in variants {
                    for property in self.structural_properties(variant, visiting)? {
                        if let Some(existing) = merged
                            .iter_mut()
                            .find(|existing| existing.wire_name == property.wire_name)
                        {
                            existing.required |= property.required;
                            existing.shape = intersect_shapes(
                                std::mem::replace(&mut existing.shape, Shape::Any),
                                property.shape,
                            );
                        } else {
                            merged.push(property);
                        }
                    }
                }
                Some(merged)
            }
            Shape::Ref { name } => {
                if !visiting.insert(name.clone()) {
                    return None;
                }
                let result = self
                    .ir
                    .types
                    .iter()
                    .find(|named| named.name == *name)
                    .and_then(|named| self.structural_properties(&named.shape, visiting));
                visiting.remove(name);
                result
            }
            _ => None,
        }
    }

    fn emit_struct(
        &mut self,
        name: &str,
        source: Option<&str>,
        mut properties: Vec<Property>,
    ) -> Result<()> {
        properties.sort_by(|left, right| left.wire_name.cmp(&right.wire_name));
        let mut fields = Vec::with_capacity(properties.len());
        let mut field_names = BTreeSet::from(["AdditionalProperties".to_owned()]);
        for property in properties {
            let base = go_identifier(&property.wire_name);
            let field_name = allocate_local_name(&base, &mut field_names);
            let hint = format!("{name}{field_name}");
            let field_type = self.render_type(&property.shape, &hint)?;
            fields.push(RenderedField {
                wire_name: property.wire_name,
                field_name,
                field_type,
                required: property.required,
            });
        }

        let mut declaration = String::new();
        let field_width = fields
            .iter()
            .map(|field| field.field_name.len())
            .chain(std::iter::once("AdditionalProperties".len()))
            .max()
            .expect("AdditionalProperties is always present")
            + 1;
        match source {
            Some(source) => writeln!(declaration, "// {name} is generated from {source}.")?,
            None => writeln!(declaration, "// {name} is a generated nested model.")?,
        }
        writeln!(declaration, "type {name} struct {{")?;
        for field in &fields {
            if field.required {
                writeln!(
                    declaration,
                    "\t{:<width$}{}",
                    field.field_name,
                    field.field_type,
                    width = field_width
                )?;
            } else {
                writeln!(
                    declaration,
                    "\t{:<width$}Optional[{}]",
                    field.field_name,
                    field.field_type,
                    width = field_width
                )?;
            }
        }
        writeln!(
            declaration,
            "\t{:<width$}map[string]json.RawMessage",
            "AdditionalProperties",
            width = field_width
        )?;
        writeln!(declaration, "}}\n")?;

        writeln!(
            declaration,
            "// UnmarshalJSON retains members not known to this schema revision."
        )?;
        writeln!(
            declaration,
            "func (value *{name}) UnmarshalJSON(data []byte) error {{"
        )?;
        writeln!(
            declaration,
            "\tvar fields map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &fields); err != nil {{\n\t\treturn err\n\t}}"
        )?;
        writeln!(
            declaration,
            "\tif fields == nil {{\n\t\treturn fmt.Errorf({})\n\t}}",
            go_string(&format!("{name} must be a JSON object"))?
        )?;
        writeln!(declaration, "\tvar decoded {name}")?;
        for field in &fields {
            writeln!(
                declaration,
                "\tif raw, ok := fields[{}]; ok {{",
                go_string(&field.wire_name)?
            )?;
            if field.required {
                writeln!(
                    declaration,
                    "\t\tif err := json.Unmarshal(raw, &decoded.{}); err != nil {{",
                    field.field_name
                )?;
            } else {
                writeln!(
                    declaration,
                    "\t\tdecoded.{}.Present = true\n\t\tif err := json.Unmarshal(raw, &decoded.{}.Value); err != nil {{",
                    field.field_name, field.field_name
                )?;
            }
            writeln!(
                declaration,
                "\t\t\treturn fmt.Errorf({}, err)\n\t\t}}\n\t\tdelete(fields, {})\n\t}}",
                go_string(&format!("{name}.{}: %w", field.wire_name))?,
                go_string(&field.wire_name)?
            )?;
        }
        writeln!(
            declaration,
            "\tdecoded.AdditionalProperties = fields\n\t*value = decoded\n\treturn nil\n}}\n"
        )?;

        writeln!(
            declaration,
            "// MarshalJSON emits known fields together with all retained members."
        )?;
        writeln!(
            declaration,
            "func (value {name}) MarshalJSON() ([]byte, error) {{"
        )?;
        writeln!(
            declaration,
            "\tfields := make(map[string]json.RawMessage, len(value.AdditionalProperties)+{})",
            fields.len()
        )?;
        writeln!(
            declaration,
            "\tfor key, raw := range value.AdditionalProperties {{\n\t\tfields[key] = raw\n\t}}"
        )?;
        for field in &fields {
            if field.required {
                writeln!(declaration, "\t{{")?;
                writeln!(
                    declaration,
                    "\t\traw, err := json.Marshal(value.{})",
                    field.field_name
                )?;
            } else {
                writeln!(declaration, "\tif value.{}.Present {{", field.field_name)?;
                writeln!(
                    declaration,
                    "\t\traw, err := json.Marshal(value.{}.Value)",
                    field.field_name
                )?;
            }
            writeln!(
                declaration,
                "\t\tif err != nil {{\n\t\t\treturn nil, fmt.Errorf({}, err)\n\t\t}}\n\t\tfields[{}] = raw\n\t}}",
                go_string(&format!("{name}.{}: %w", field.wire_name))?,
                go_string(&field.wire_name)?
            )?;
        }
        writeln!(declaration, "\treturn json.Marshal(fields)\n}}\n")?;
        self.declarations.push(declaration);
        Ok(())
    }

    fn emit_value_type(&mut self, name: &str, source: Option<&str>, shape: &Shape) -> Result<()> {
        let values = match shape {
            Shape::Literal { value } => std::slice::from_ref(value),
            Shape::Enum { values, .. } => values.as_slice(),
            _ => unreachable!("value types are literals or enums"),
        };
        let base = if values.iter().all(serde_json::Value::is_string) {
            "string"
        } else if values.iter().all(serde_json::Value::is_boolean) {
            "bool"
        } else if values.iter().all(serde_json::Value::is_number) {
            "json.Number"
        } else {
            "json.RawMessage"
        };
        let mut declaration = String::new();
        match source {
            Some(source) => writeln!(declaration, "// {name} is generated from {source}.")?,
            None => writeln!(declaration, "// {name} is a generated schema value.")?,
        }
        if base == "json.RawMessage" {
            writeln!(declaration, "type {name} json.RawMessage")?;
            writeln!(
                declaration,
                "\nfunc (value *{name}) UnmarshalJSON(data []byte) error {{\n\tif _, err := decodeJSON(data); err != nil {{\n\t\treturn err\n\t}}\n\t*value = append((*value)[:0], data...)\n\treturn nil\n}}"
            )?;
            writeln!(
                declaration,
                "\nfunc (value {name}) MarshalJSON() ([]byte, error) {{\n\treturn json.Marshal(json.RawMessage(value))\n}}\n"
            )?;
        } else {
            writeln!(declaration, "type {name} {base}\n")?;
            for (index, value) in values.iter().enumerate() {
                let suffix = value_constant_suffix(value, index);
                let constant = self.allocate_package_name(&format!("{name}{suffix}"));
                let rendered = match value {
                    serde_json::Value::String(value) => go_string(value)?,
                    serde_json::Value::Bool(value) => value.to_string(),
                    serde_json::Value::Number(value) => go_string(&value.to_string())?,
                    _ => continue,
                };
                writeln!(declaration, "const {constant} {name} = {rendered}")?;
            }
            if base == "json.Number" {
                writeln!(
                    declaration,
                    "\nfunc (value *{name}) UnmarshalJSON(data []byte) error {{\n\tvar number json.Number\n\tif err := json.Unmarshal(data, &number); err != nil {{\n\t\treturn err\n\t}}\n\t*value = {name}(number)\n\treturn nil\n}}"
                )?;
                writeln!(
                    declaration,
                    "\nfunc (value {name}) MarshalJSON() ([]byte, error) {{\n\treturn json.Marshal(json.Number(value))\n}}"
                )?;
            }
            declaration.push('\n');
        }
        self.declarations.push(declaration);
        Ok(())
    }

    fn emit_union(&mut self, name: &str, source: Option<&str>, shape: &Shape) -> Result<()> {
        let Shape::Union { variants, .. } = shape else {
            unreachable!("union emitter requires a union");
        };
        let mut fields = Vec::with_capacity(variants.len());
        let mut field_names = BTreeSet::from(["Unknown".to_owned()]);
        for (index, variant) in variants.iter().enumerate() {
            let field_type = self.render_type(variant, &format!("{name}Variant{}", index + 1))?;
            let base = union_variant_name(self, variant, index);
            let field_name = allocate_local_name(&base, &mut field_names);
            fields.push((field_name, field_type));
        }
        let descriptor = serde_json::to_string(shape)?;
        let mut declaration = String::new();
        match source {
            Some(source) => writeln!(declaration, "// {name} is generated from {source}.")?,
            None => writeln!(declaration, "// {name} is a generated union model.")?,
        }
        let field_width = fields
            .iter()
            .map(|(field_name, _)| field_name.len())
            .chain(std::iter::once("Unknown".len()))
            .max()
            .expect("Unknown is always present")
            + 1;
        writeln!(declaration, "type {name} struct {{")?;
        for (field_name, field_type) in &fields {
            writeln!(
                declaration,
                "\t{field_name:<field_width$}Optional[{field_type}]"
            )?;
        }
        writeln!(
            declaration,
            "\t{:<field_width$}json.RawMessage\n}}\n",
            "Unknown"
        )?;
        writeln!(
            declaration,
            "func (value *{name}) UnmarshalJSON(data []byte) error {{"
        )?;
        writeln!(
            declaration,
            "\trawValue, err := decodeJSON(data)\n\tif err != nil {{\n\t\treturn err\n\t}}"
        )?;
        writeln!(
            declaration,
            "\tschema := loadSchemaNode({})",
            go_string(&descriptor)?
        )?;
        writeln!(
            declaration,
            "\tdiagnostics := make([]ParseDiagnostic, 0)\n\tcheckNode(schema, rawValue, \"\", &diagnostics)\n\tif hasErrors(diagnostics) {{\n\t\treturn fmt.Errorf({})\n\t}}",
            go_string(&format!("{name}: value does not match the union"))?
        )?;
        writeln!(declaration, "\tvar decoded {name}")?;
        for (index, (field_name, field_type)) in fields.iter().enumerate() {
            writeln!(
                declaration,
                "\t{{\n\t\tattempt := make([]ParseDiagnostic, 0)\n\t\tcheckNode(schema.Variants[{index}], rawValue, \"\", &attempt)\n\t\tif !hasErrors(attempt) {{\n\t\t\tvar candidate {field_type}\n\t\t\tif err := json.Unmarshal(data, &candidate); err != nil {{\n\t\t\t\treturn fmt.Errorf({}, err)\n\t\t\t}}\n\t\t\tdecoded.{field_name} = Some(candidate)\n\t\t\t*value = decoded\n\t\t\treturn nil\n\t\t}}\n\t}}",
                go_string(&format!("{name}.{field_name}: %w"))?
            )?;
        }
        writeln!(
            declaration,
            "\tdecoded.Unknown = append(json.RawMessage(nil), data...)\n\t*value = decoded\n\treturn nil\n}}\n"
        )?;
        writeln!(
            declaration,
            "func (value {name}) MarshalJSON() ([]byte, error) {{"
        )?;
        writeln!(declaration, "\tselected := 0")?;
        for (field_name, _) in &fields {
            writeln!(
                declaration,
                "\tif value.{field_name}.Present {{\n\t\tselected++\n\t}}"
            )?;
        }
        writeln!(
            declaration,
            "\tif len(value.Unknown) != 0 {{\n\t\tselected++\n\t}}\n\tif selected != 1 {{\n\t\treturn nil, fmt.Errorf({})\n\t}}",
            go_string(&format!("{name}: exactly one variant must be selected"))?
        )?;
        for (field_name, _) in &fields {
            writeln!(
                declaration,
                "\tif value.{field_name}.Present {{\n\t\treturn json.Marshal(value.{field_name}.Value)\n\t}}"
            )?;
        }
        writeln!(declaration, "\treturn json.Marshal(value.Unknown)\n}}\n")?;
        self.declarations.push(declaration);
        Ok(())
    }

    fn render_type(&mut self, shape: &Shape, hint: &str) -> Result<String> {
        Ok(match shape {
            Shape::Any | Shape::Never | Shape::Null => "json.RawMessage".into(),
            Shape::Boolean => "bool".into(),
            Shape::Integer | Shape::Number => "json.Number".into(),
            Shape::String => "string".into(),
            Shape::Literal { .. } | Shape::Enum { .. } => {
                let name = self.allocate_type_name(hint);
                self.emit_value_type(&name, None, shape)?;
                name
            }
            Shape::Array { items } => {
                format!("[]{}", self.render_type(items, &format!("{hint}Item"))?)
            }
            Shape::Object { properties, .. } => {
                let name = self.allocate_type_name(hint);
                self.emit_struct(&name, None, properties.clone())?;
                name
            }
            Shape::Ref { name } => format!("*{}", self.named_name(name)),
            Shape::Union { .. } => {
                let name = self.allocate_type_name(hint);
                self.emit_union(&name, None, shape)?;
                name
            }
            Shape::Intersection { .. } => {
                if let Some(properties) = self.structural_properties(shape, &mut BTreeSet::new()) {
                    let name = self.allocate_type_name(hint);
                    self.emit_struct(&name, None, properties)?;
                    name
                } else {
                    "json.RawMessage".into()
                }
            }
        })
    }

    fn allocate_type_name(&mut self, hint: &str) -> String {
        let base = go_identifier(hint);
        self.allocate_package_name(&base)
    }

    fn allocate_package_name(&mut self, base: &str) -> String {
        allocate_local_name(base, &mut self.used_names)
    }
}

fn intersect_shapes(left: Shape, right: Shape) -> Shape {
    match (left, right) {
        (Shape::Any, shape) | (shape, Shape::Any) => shape,
        (Shape::Never, _) | (_, Shape::Never) => Shape::Never,
        (left, right) => {
            let mut variants = Vec::new();
            for shape in [left, right] {
                match shape {
                    Shape::Intersection { variants: nested } => variants.extend(nested),
                    shape => variants.push(shape),
                }
            }
            variants.sort_by_cached_key(|shape| {
                serde_json::to_string(shape).expect("shape serializes")
            });
            variants.dedup_by(|left, right| {
                serde_json::to_string(left).expect("shape serializes")
                    == serde_json::to_string(right).expect("shape serializes")
            });
            if variants.len() == 1 {
                variants.pop().expect("one intersection shape")
            } else {
                Shape::Intersection { variants }
            }
        }
    }
}

struct RenderedField {
    wire_name: String,
    field_name: String,
    field_type: String,
    required: bool,
}

fn union_variant_name(generator: &Generator<'_>, shape: &Shape, index: usize) -> String {
    match shape {
        Shape::Ref { name } => generator.named_name(name),
        Shape::Literal {
            value: serde_json::Value::String(value),
        } => go_identifier(value),
        _ => format!("Variant{}", index + 1),
    }
}

fn value_constant_suffix(value: &serde_json::Value, index: usize) -> String {
    match value {
        serde_json::Value::String(value) if !value.is_empty() => {
            let identifier = go_identifier(value);
            if value.as_bytes()[0].is_ascii_digit() {
                format!("Value{}", identifier.trim_start_matches("Field"))
            } else {
                identifier
            }
        }
        serde_json::Value::Bool(true) => "True".into(),
        serde_json::Value::Bool(false) => "False".into(),
        serde_json::Value::Number(_) => format!("Value{}", index + 1),
        _ => format!("Value{}", index + 1),
    }
}

fn runtime_names() -> BTreeSet<String> {
    [
        "SchemaRevision",
        "ProtocolVersionValue",
        "Optional",
        "Some",
        "DiagnosticCode",
        "DiagnosticInvalidType",
        "DiagnosticMissingRequired",
        "DiagnosticLiteralMismatch",
        "DiagnosticUnknownEnum",
        "DiagnosticUnknownVariant",
        "DiagnosticInvalidKnownVariant",
        "DiagnosticNoUnionMatch",
        "DiagnosticAmbiguousUnion",
        "DiagnosticInvalidJSON",
        "DiagnosticSeverity",
        "SeverityError",
        "SeverityWarning",
        "ParseDiagnostic",
        "ParseResult",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

fn allocate_root_name(base: &str, used: &mut BTreeSet<String>) -> String {
    for suffix in 1.. {
        let candidate = if suffix == 1 {
            base.to_owned()
        } else {
            format!("{base}{suffix}")
        };
        let companions = [
            candidate.clone(),
            format!("Parse{candidate}"),
            format!("Encode{candidate}"),
            format!("{candidate}SchemaRevision"),
        ];
        if companions.iter().all(|name| !used.contains(name)) {
            used.extend(companions);
            return candidate;
        }
    }
    unreachable!()
}

fn allocate_local_name(base: &str, used: &mut BTreeSet<String>) -> String {
    if used.insert(base.to_owned()) {
        return base.to_owned();
    }
    for suffix in 2.. {
        let candidate = format!("{base}{suffix}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!()
}

fn go_identifier(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase_next {
                result.extend(character.to_uppercase());
                uppercase_next = false;
            } else {
                result.push(character);
            }
        } else {
            uppercase_next = true;
        }
    }
    if result.is_empty() {
        result.push_str("Field");
    }
    if result.as_bytes()[0].is_ascii_digit() {
        result.insert_str(0, "Field");
    }
    match result.to_ascii_lowercase().as_str() {
        "id" => "ID".into(),
        "url" => "URL".into(),
        "uri" => "URI".into(),
        "http" => "HTTP".into(),
        "https" => "HTTPS".into(),
        "jsonrpc" => "JSONRPC".into(),
        "cwd" => "CWD".into(),
        _ => result,
    }
}

fn go_string(value: &str) -> Result<String> {
    Ok(serde_json::to_string(value)?)
}

const IMPORTS: &str = r#"import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"reflect"
	"strings"
)

"#;

const PRELUDE: &str = r#"// Optional distinguishes an absent member from a present zero or null value.
type Optional[T any] struct {
	Value   T
	Present bool
}

// Some returns a present optional value.
func Some[T any](value T) Optional[T] {
	return Optional[T]{Value: value, Present: true}
}

// DiagnosticCode identifies a structural parse diagnostic.
type DiagnosticCode string

const (
	DiagnosticInvalidType         DiagnosticCode = "invalid_type"
	DiagnosticMissingRequired     DiagnosticCode = "missing_required"
	DiagnosticLiteralMismatch     DiagnosticCode = "literal_mismatch"
	DiagnosticUnknownEnum         DiagnosticCode = "unknown_enum"
	DiagnosticUnknownVariant      DiagnosticCode = "unknown_variant"
	DiagnosticInvalidKnownVariant DiagnosticCode = "invalid_known_variant"
	DiagnosticNoUnionMatch        DiagnosticCode = "no_union_match"
	DiagnosticAmbiguousUnion      DiagnosticCode = "ambiguous_union"
	DiagnosticInvalidJSON         DiagnosticCode = "invalid_json"
)

// DiagnosticSeverity indicates whether a diagnostic prevents a typed result.
type DiagnosticSeverity string

const (
	SeverityError   DiagnosticSeverity = "error"
	SeverityWarning DiagnosticSeverity = "warning"
)

// ParseDiagnostic describes a structural mismatch at a JSON Pointer path.
type ParseDiagnostic struct {
	Path     string             `json:"path"`
	Code     DiagnosticCode     `json:"code"`
	Severity DiagnosticSeverity `json:"severity"`
	Message  string             `json:"message"`
}

// ParseResult contains the typed value on success and the original JSON on every
// syntactically valid parse. Callers must check OK before using Value.
type ParseResult[T any] struct {
	OK          bool
	Value       T
	Raw         json.RawMessage
	Diagnostics []ParseDiagnostic
}

"#;

const RUNTIME: &str = r#"type schemaProperty struct {
	WireName string      `json:"wire_name"`
	Required bool        `json:"required"`
	Shape    *schemaNode `json:"shape"`
}

type schemaNode struct {
	Kind                  string           `json:"kind"`
	Value                 any              `json:"value"`
	Values                []any            `json:"values"`
	OpenStrings           bool             `json:"open_strings"`
	Items                 *schemaNode      `json:"items"`
	Properties            []schemaProperty `json:"properties"`
	ForbiddenPropertySets [][]string       `json:"forbidden_property_sets"`
	Mode                  string           `json:"mode"`
	Variants              []*schemaNode    `json:"variants"`
	Discriminator         *string          `json:"discriminator"`
	Name                  string           `json:"name"`
}

func loadSchemaDescriptors(source string) map[string]*schemaNode {
	decoder := json.NewDecoder(strings.NewReader(source))
	decoder.UseNumber()
	var descriptors map[string]*schemaNode
	if err := decoder.Decode(&descriptors); err != nil {
		panic(fmt.Sprintf("invalid generated schema descriptors: %v", err))
	}
	return descriptors
}

func loadSchemaNode(source string) *schemaNode {
	decoder := json.NewDecoder(strings.NewReader(source))
	decoder.UseNumber()
	var node schemaNode
	if err := decoder.Decode(&node); err != nil {
		panic(fmt.Sprintf("invalid generated schema node: %v", err))
	}
	return &node
}

func parseRoot[T any](name string, input []byte) ParseResult[T] {
	raw := append(json.RawMessage(nil), input...)
	value, err := decodeJSON(input)
	if err != nil {
		return ParseResult[T]{
			Diagnostics: []ParseDiagnostic{{
				Code: DiagnosticInvalidJSON, Severity: SeverityError, Message: err.Error(),
			}},
		}
	}

	diagnostics := make([]ParseDiagnostic, 0)
	checkNode(schemaDescriptors[name], value, "", &diagnostics)
	result := ParseResult[T]{Raw: raw, Diagnostics: diagnostics}
	if hasErrors(diagnostics) {
		return result
	}
	if err := json.Unmarshal(input, &result.Value); err != nil {
		result.Diagnostics = append(result.Diagnostics, ParseDiagnostic{
			Code: DiagnosticInvalidType, Severity: SeverityError, Message: err.Error(),
		})
		return result
	}
	result.OK = true
	return result
}

func decodeJSON(input []byte) (any, error) {
	decoder := json.NewDecoder(bytes.NewReader(input))
	decoder.UseNumber()
	var value any
	if err := decoder.Decode(&value); err != nil {
		return nil, err
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("multiple JSON values")
		}
		return nil, err
	}
	return value, nil
}

func checkNode(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	if schema == nil {
		addError(diagnostics, path, DiagnosticInvalidType, "Missing generated schema")
		return
	}
	switch schema.Kind {
	case "any":
		return
	case "never":
		addError(diagnostics, path, DiagnosticInvalidType, "Value is forbidden")
	case "null":
		if value != nil {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected null")
		}
	case "boolean":
		if _, ok := value.(bool); !ok {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected boolean")
		}
	case "integer":
		if number, ok := value.(json.Number); !ok || !isSafeInteger(number) {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected safely representable integer")
		}
	case "number":
		if number, ok := value.(json.Number); !ok || !isFiniteNumber(number) {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected finite number")
		}
	case "string":
		if _, ok := value.(string); !ok {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected string")
		}
	case "literal":
		if !sameJSON(value, schema.Value) {
			addError(diagnostics, path, DiagnosticLiteralMismatch, fmt.Sprintf("Expected %s", jsonText(schema.Value)))
		}
	case "enum":
		checkEnum(schema, value, path, diagnostics)
	case "array":
		items, ok := value.([]any)
		if !ok {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected array")
			return
		}
		for index, item := range items {
			checkNode(schema.Items, item, fmt.Sprintf("%s/%d", path, index), diagnostics)
		}
	case "object":
		checkObject(schema, value, path, diagnostics)
	case "intersection":
		for _, variant := range schema.Variants {
			checkNode(variant, value, path, diagnostics)
		}
	case "ref":
		checkNode(schemaDescriptors[schema.Name], value, path, diagnostics)
	case "union":
		checkUnion(schema, value, path, diagnostics)
	default:
		addError(diagnostics, path, DiagnosticInvalidType, "Unknown generated schema node")
	}
}

func checkEnum(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	for _, candidate := range schema.Values {
		if sameJSON(candidate, value) {
			return
		}
	}
	if _, ok := value.(string); schema.OpenStrings && ok {
		*diagnostics = append(*diagnostics, ParseDiagnostic{
			Path: path, Code: DiagnosticUnknownEnum, Severity: SeverityWarning,
			Message: fmt.Sprintf("Unknown enum value %s was preserved", jsonText(value)),
		})
		return
	}
	addError(diagnostics, path, DiagnosticInvalidType, "Value does not match the enum's scalar type")
}

func checkObject(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	object, ok := value.(map[string]any)
	if !ok {
		addError(diagnostics, path, DiagnosticInvalidType, "Expected object")
		return
	}
	for _, forbiddenSet := range schema.ForbiddenPropertySets {
		allPresent := true
		for _, key := range forbiddenSet {
			if _, present := object[key]; !present {
				allPresent = false
				break
			}
		}
		if allPresent {
			addError(diagnostics, path, DiagnosticInvalidType, "Forbidden property combination: "+strings.Join(forbiddenSet, ", "))
		}
	}
	for _, property := range schema.Properties {
		child, present := object[property.WireName]
		childPath := joinPath(path, property.WireName)
		if !present {
			if property.Required {
				addError(diagnostics, childPath, DiagnosticMissingRequired, "Required property is absent")
			}
			continue
		}
		checkNode(property.Shape, child, childPath, diagnostics)
	}
}

func checkUnion(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	if schema.Discriminator != nil {
		object, objectOK := value.(map[string]any)
		actual, discriminatorOK := object[*schema.Discriminator].(string)
		if !objectOK || !discriminatorOK {
			addError(diagnostics, joinPath(path, *schema.Discriminator), DiagnosticInvalidType, "Expected string discriminator")
			return
		}
		var branch *schemaNode
		for _, candidate := range schema.Variants {
			if discriminatorValue(candidate, *schema.Discriminator) == actual {
				branch = candidate
				break
			}
		}
		if branch == nil {
			*diagnostics = append(*diagnostics, ParseDiagnostic{
				Path: path, Code: DiagnosticUnknownVariant, Severity: SeverityWarning,
				Message: fmt.Sprintf("Unknown %s variant %s was preserved", *schema.Discriminator, jsonText(actual)),
			})
			return
		}
		branchDiagnostics := make([]ParseDiagnostic, 0)
		checkNode(branch, value, path, &branchDiagnostics)
		*diagnostics = append(*diagnostics, branchDiagnostics...)
		if hasErrors(branchDiagnostics) {
			*diagnostics = append(*diagnostics, ParseDiagnostic{
				Path: path, Code: DiagnosticInvalidKnownVariant, Severity: SeverityError,
				Message: fmt.Sprintf("Known %s variant is malformed", *schema.Discriminator),
			})
		}
		return
	}

	matches := make([][]ParseDiagnostic, 0, len(schema.Variants))
	for _, variant := range schema.Variants {
		attempt := make([]ParseDiagnostic, 0)
		checkNode(variant, value, path, &attempt)
		if !hasErrors(attempt) {
			matches = append(matches, attempt)
		}
	}
	if len(matches) == 0 {
		addError(diagnostics, path, DiagnosticNoUnionMatch, "Value matches no union branch")
	} else if schema.Mode == "oneOf" && len(matches) > 1 {
		addError(diagnostics, path, DiagnosticAmbiguousUnion, "Value matches more than one union branch")
	} else {
		*diagnostics = append(*diagnostics, matches[0]...)
	}
}

func discriminatorValue(schema *schemaNode, property string) string {
	if schema == nil {
		return ""
	}
	switch schema.Kind {
	case "ref":
		return discriminatorValue(schemaDescriptors[schema.Name], property)
	case "intersection":
		for _, variant := range schema.Variants {
			if value := discriminatorValue(variant, property); value != "" {
				return value
			}
		}
	case "object":
		for _, field := range schema.Properties {
			if field.WireName == property && field.Shape.Kind == "literal" {
				if value, ok := field.Shape.Value.(string); ok {
					return value
				}
			}
		}
	}
	return ""
}

func hasErrors(diagnostics []ParseDiagnostic) bool {
	for _, diagnostic := range diagnostics {
		if diagnostic.Severity == SeverityError {
			return true
		}
	}
	return false
}

type exactDecimal struct {
	Negative bool
	Digits   string
	Exponent *big.Int
}

func exactNumber(number json.Number) (exactDecimal, bool) {
	text := number.String()
	negative := strings.HasPrefix(text, "-")
	if negative {
		text = text[1:]
	}
	mantissa, exponentText := text, "0"
	if index := strings.IndexAny(text, "eE"); index >= 0 {
		mantissa, exponentText = text[:index], text[index+1:]
	}
	exponent, ok := new(big.Int).SetString(exponentText, 10)
	if !ok {
		return exactDecimal{}, false
	}
	whole, fraction := mantissa, ""
	if index := strings.IndexByte(mantissa, '.'); index >= 0 {
		whole, fraction = mantissa[:index], mantissa[index+1:]
	}
	digits := strings.TrimLeft(whole+fraction, "0")
	if digits == "" {
		return exactDecimal{Digits: "0", Exponent: new(big.Int)}, true
	}
	exponent.Sub(exponent, big.NewInt(int64(len(fraction))))
	trimmed := strings.TrimRight(digits, "0")
	exponent.Add(exponent, big.NewInt(int64(len(digits)-len(trimmed))))
	return exactDecimal{Negative: negative, Digits: trimmed, Exponent: exponent}, true
}

func isSafeInteger(number json.Number) bool {
	value, ok := exactNumber(number)
	if !ok || value.Digits == "0" {
		return ok
	}
	if value.Exponent.Sign() < 0 || !value.Exponent.IsInt64() {
		return false
	}
	zeros := value.Exponent.Int64()
	if zeros > 16 || int64(len(value.Digits))+zeros > 16 {
		return false
	}
	digits := value.Digits + strings.Repeat("0", int(zeros))
	return len(digits) < 16 || digits <= "9007199254740991"
}

func isFiniteNumber(number json.Number) bool {
	_, ok := exactNumber(number)
	return ok
}

func sameJSON(left, right any) bool {
	leftNumber, leftIsNumber := left.(json.Number)
	rightNumber, rightIsNumber := right.(json.Number)
	if leftIsNumber || rightIsNumber {
		if !leftIsNumber || !rightIsNumber {
			return false
		}
		leftValue, leftOK := exactNumber(leftNumber)
		rightValue, rightOK := exactNumber(rightNumber)
		return leftOK && rightOK && leftValue.Negative == rightValue.Negative &&
			leftValue.Digits == rightValue.Digits && leftValue.Exponent.Cmp(rightValue.Exponent) == 0
	}
	leftArray, leftIsArray := left.([]any)
	rightArray, rightIsArray := right.([]any)
	if leftIsArray || rightIsArray {
		if !leftIsArray || !rightIsArray || len(leftArray) != len(rightArray) {
			return false
		}
		for index := range leftArray {
			if !sameJSON(leftArray[index], rightArray[index]) {
				return false
			}
		}
		return true
	}
	leftObject, leftIsObject := left.(map[string]any)
	rightObject, rightIsObject := right.(map[string]any)
	if leftIsObject || rightIsObject {
		if !leftIsObject || !rightIsObject || len(leftObject) != len(rightObject) {
			return false
		}
		for key, leftValue := range leftObject {
			rightValue, ok := rightObject[key]
			if !ok || !sameJSON(leftValue, rightValue) {
				return false
			}
		}
		return true
	}
	return reflect.DeepEqual(left, right)
}

func joinPath(path, key string) string {
	escaped := strings.ReplaceAll(strings.ReplaceAll(key, "~", "~0"), "/", "~1")
	return path + "/" + escaped
}

func jsonText(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return "<invalid JSON>"
	}
	return string(encoded)
}

func addError(diagnostics *[]ParseDiagnostic, path string, code DiagnosticCode, message string) {
	*diagnostics = append(*diagnostics, ParseDiagnostic{
		Path: path, Code: code, Severity: SeverityError, Message: message,
	})
}

"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AdditionalProperties, Ir, NamedType, PublicRoot, Shape, UnionMode};

    fn sample_ir() -> Ir {
        Ir {
            schema_revision: "test-revision".into(),
            protocol_version: "1".into(),
            roots: vec![PublicRoot {
                name: "Message".into(),
                schema: "message.json".into(),
            }],
            types: vec![NamedType {
                name: "Message".into(),
                source: "message.json#".into(),
                shape: Shape::Object {
                    properties: vec![Property {
                        wire_name: "displayName".into(),
                        required: false,
                        shape: Shape::String,
                    }],
                    forbidden_property_sets: vec![],
                    additional: AdditionalProperties::Allowed,
                },
            }],
        }
    }

    #[test]
    fn output_is_deterministic_and_has_lossless_entrypoints() {
        let mut ordered = sample_ir();
        ordered.types.push(NamedType {
            name: "Alpha".into(),
            source: "alpha.json#".into(),
            shape: Shape::String,
        });
        let mut reversed = sample_ir();
        reversed.types.push(NamedType {
            name: "Alpha".into(),
            source: "alpha.json#".into(),
            shape: Shape::String,
        });
        reversed.types.reverse();
        let first = emit(&ordered).unwrap();
        let second = emit(&reversed).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("type Message struct"));
        assert!(first.contains("DisplayName          Optional[string]"));
        assert!(first.contains("AdditionalProperties map[string]json.RawMessage"));
        assert!(first.contains("func ParseMessage(input []byte) ParseResult[Message]"));
        assert!(first.contains("func EncodeMessage(value Message) ([]byte, error)"));
        assert!(first.contains("DiagnosticUnknownVariant"));
    }

    #[test]
    fn renders_nested_models_and_union_aliases() {
        let mut ir = sample_ir();
        ir.types.push(NamedType {
            name: "Envelope".into(),
            source: "envelope.json#".into(),
            shape: Shape::Object {
                properties: vec![Property {
                    wire_name: "payload".into(),
                    required: true,
                    shape: Shape::Object {
                        properties: vec![Property {
                            wire_name: "id".into(),
                            required: true,
                            shape: Shape::Integer,
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Forbidden,
                    },
                }],
                forbidden_property_sets: vec![],
                additional: AdditionalProperties::Allowed,
            },
        });
        ir.types.push(NamedType {
            name: "Choice".into(),
            source: "choice.json#".into(),
            shape: Shape::Union {
                mode: UnionMode::OneOf,
                variants: vec![Shape::String, Shape::Integer],
                discriminator: None,
            },
        });
        let output = emit(&ir).unwrap();
        assert!(output.contains("type EnvelopePayload struct"));
        assert!(
            output
                .lines()
                .any(|line| line.split_whitespace().eq(["Payload", "EnvelopePayload"]))
        );
        assert!(
            output
                .lines()
                .any(|line| line.split_whitespace().eq(["ID", "json.Number"]))
        );
        assert!(output.contains("type Choice struct"));
        assert!(output.contains("Variant1 Optional[string]"));
        assert!(output.contains("Variant2 Optional[json.Number]"));
    }

    #[test]
    fn normalizes_colliding_names_and_breaks_recursive_value_cycles() {
        let ir = Ir {
            schema_revision: "test".into(),
            protocol_version: "1".into(),
            roots: vec![PublicRoot {
                name: "Optional".into(),
                schema: "node.json".into(),
            }],
            types: vec![
                NamedType {
                    name: "Optional".into(),
                    source: "node.json#".into(),
                    shape: Shape::Object {
                        properties: vec![Property {
                            wire_name: "next".into(),
                            required: false,
                            shape: Shape::Ref {
                                name: "Optional".into(),
                            },
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Allowed,
                    },
                },
                NamedType {
                    name: "optional!".into(),
                    source: "other.json#".into(),
                    shape: Shape::String,
                },
            ],
        };
        let output = emit(&ir).unwrap();
        assert!(output.contains("type Optional2 struct"));
        assert!(output.contains("Next                 Optional[*Optional2]"));
        assert!(output.contains("type Optional3 = string"));
        assert!(output.contains("func ParseOptional2"));
    }

    #[test]
    fn emits_named_literals_and_open_enums() {
        let mut ir = sample_ir();
        ir.types.push(NamedType {
            name: "ProtocolVersion".into(),
            source: "protocol.json#".into(),
            shape: Shape::Literal {
                value: serde_json::json!("2.0"),
            },
        });
        ir.types.push(NamedType {
            name: "Mode".into(),
            source: "mode.json#".into(),
            shape: Shape::Enum {
                values: vec![serde_json::json!("strict"), serde_json::json!("open")],
                open_strings: true,
            },
        });
        let output = emit(&ir).unwrap();
        assert!(output.contains("type ProtocolVersion string"));
        assert!(output.contains("const ProtocolVersionValue20 ProtocolVersion = \"2.0\""));
        assert!(output.contains("type Mode string"));
        assert!(output.contains("const ModeStrict Mode = \"strict\""));
    }

    #[test]
    fn intersection_properties_merge_commutatively_with_any_as_identity() {
        fn properties(variants: Vec<Shape>) -> Vec<Property> {
            let shape = Shape::Intersection { variants };
            let ir = Ir {
                schema_revision: "test".into(),
                protocol_version: "1".into(),
                roots: vec![],
                types: vec![],
            };
            Generator::new(&ir)
                .structural_properties(&shape, &mut BTreeSet::new())
                .unwrap()
        }
        fn object(shape: Shape, required: bool) -> Shape {
            Shape::Object {
                properties: vec![Property {
                    wire_name: "effects".into(),
                    required,
                    shape,
                }],
                forbidden_property_sets: vec![],
                additional: AdditionalProperties::Allowed,
            }
        }

        let typed = Shape::Array {
            items: Box::new(Shape::String),
        };
        let forward = properties(vec![object(Shape::Any, false), object(typed.clone(), true)]);
        let reverse = properties(vec![object(typed, true), object(Shape::Any, false)]);
        assert_eq!(
            serde_json::to_value(&forward).unwrap(),
            serde_json::to_value(&reverse).unwrap()
        );
        assert!(forward[0].required);
        assert!(matches!(forward[0].shape, Shape::Array { .. }));
    }

    #[test]
    fn go_identifiers_are_exported_and_stable() {
        assert_eq!(go_identifier("eventName"), "EventName");
        assert_eq!(go_identifier("id"), "ID");
        assert_eq!(go_identifier("jsonrpc"), "JSONRPC");
        assert_eq!(go_identifier("future-field"), "FutureField");
        assert_eq!(go_identifier("123"), "Field123");
    }
}
