pub mod facade;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use anyhow::{Context, Result};

use crate::model::{Ir, Property, Shape};

/// Emit a self-contained Go package containing the public AHP models and codecs.
///
/// The generated decoder deliberately performs only the structural checks represented
/// by the codegen IR. Unknown object members, open-enum values, and discriminator
/// variants are retained so a decode/encode cycle does not discard forward-compatible data.
pub fn emit(ir: &Ir) -> Result<String> {
    let mut generator = Generator::new(ir);
    let mut named_types = ir.types.iter().collect::<Vec<_>>();
    named_types.sort_by_key(|named| (named.name.as_str(), named.source.as_str()));
    for named in named_types {
        let go_name = generator.named_name(&named.name);
        generator.emit_named(&go_name, named.source.as_str(), &named.shape)?;
    }

    let descriptors = ir
        .types
        .iter()
        .map(|named| {
            (
                named.name.clone(),
                serde_json::to_value(&named.shape).expect("shape serializes"),
            )
        })
        .collect::<BTreeMap<_, _>>();
    let descriptor_json = serde_json::to_string(&descriptors)?;

    let mut output = String::new();
    writeln!(output, "// Code generated by ahp-codegen. DO NOT EDIT.")?;
    writeln!(
        output,
        "// Generated from AHP schema {}.",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "// The source schema is authoritative if this output conflicts with it."
    )?;
    writeln!(output, "package ahp\n")?;
    output.push_str(IMPORTS);
    writeln!(
        output,
        "const SchemaRevision = {}",
        go_string(&ir.schema_revision)?
    )?;
    writeln!(
        output,
        "const ProtocolVersionValue = {}\n",
        go_string(&ir.protocol_version)?
    )?;
    output.push_str(PRELUDE);
    for declaration in &generator.declarations {
        output.push_str(declaration);
    }
    facade::capability_queries(&generator, &mut output)?;
    for name in generator.decoder_shapes.keys() {
        writeln!(
            output,
            "// UnmarshalJSON enforces generated structural rules and retains supported extensions.\nfunc (value *{name}) UnmarshalJSON(data []byte) error {{\n\tif err := validateModelJSON(modelDescriptors[{}], data); err != nil {{\n\t\treturn err\n\t}}\n\treturn value.unmarshalValidatedJSON(data)\n}}\n",
            go_string(name)?
        )?;
    }
    writeln!(
        output,
        "var modelDescriptors = loadSchemaDescriptors({})\n",
        go_string(&serde_json::to_string(&generator.decoder_shapes)?)?
    )?;
    writeln!(
        output,
        "var unionDescriptors = loadSchemaDescriptors({})\n",
        go_string(&serde_json::to_string(&generator.union_descriptors)?)?
    )?;
    writeln!(
        output,
        "var schemaDescriptors = loadSchemaDescriptors({})\n",
        go_string(&descriptor_json)?
    )?;
    output.push_str(RUNTIME);

    let mut roots = ir.roots.iter().collect::<Vec<_>>();
    roots.sort_by_key(|root| (root.name.as_str(), root.schema.as_str()));
    for root in roots {
        let root_name = generator.named_name(&root.name);
        writeln!(
            output,
            "// Parse{root_name} parses and structurally checks one {root_name} JSON document."
        )?;
        writeln!(
            output,
            "func Parse{root_name}(input []byte) ParseResult[{root_name}] {{"
        )?;
        writeln!(
            output,
            "\treturn parseRoot[{root_name}]({}, input)",
            go_string(&root.name)?
        )?;
        writeln!(output, "}}\n")?;
        writeln!(
            output,
            "// Encode{root_name} encodes value without applying schema defaults."
        )?;
        writeln!(
            output,
            "func Encode{root_name}(value {root_name}) ([]byte, error) {{"
        )?;
        writeln!(output, "\treturn json.Marshal(value)")?;
        writeln!(output, "}}\n")?;
        writeln!(output, "const {root_name}SchemaRevision = SchemaRevision\n")?;
    }
    if output.ends_with("\n\n") {
        output.pop();
    }

    Ok(output)
}

struct Generator<'a> {
    ir: &'a Ir,
    named_names: BTreeMap<String, String>,
    used_names: BTreeSet<String>,
    declarations: Vec<String>,
    objects: BTreeMap<String, Vec<RenderedField>>,
    unions: BTreeMap<String, Vec<(String, String)>>,
    nullables: BTreeMap<String, String>,
    decoder_shapes: BTreeMap<String, Shape>,
    union_descriptors: BTreeMap<String, Shape>,
}

impl<'a> Generator<'a> {
    fn new(ir: &'a Ir) -> Self {
        let mut used_names = runtime_names();
        let mut named_names = BTreeMap::new();
        let root_names = ir
            .roots
            .iter()
            .map(|root| root.name.as_str())
            .collect::<BTreeSet<_>>();
        let mut ordered = ir.types.iter().collect::<Vec<_>>();
        ordered.sort_by_key(|named| {
            (
                !root_names.contains(named.name.as_str()),
                named.name.as_str(),
            )
        });
        for named in ordered {
            let base = go_identifier(&named.name);
            let allocated = if root_names.contains(named.name.as_str()) {
                allocate_root_name(&base, &mut used_names)
            } else {
                allocate_local_name(&base, &mut used_names)
            };
            named_names.insert(named.name.clone(), allocated);
        }
        Self {
            ir,
            named_names,
            used_names,
            declarations: Vec::new(),
            objects: BTreeMap::new(),
            unions: BTreeMap::new(),
            nullables: BTreeMap::new(),
            decoder_shapes: BTreeMap::new(),
            union_descriptors: BTreeMap::new(),
        }
    }

    fn named_name(&self, name: &str) -> String {
        self.named_names
            .get(name)
            .cloned()
            .unwrap_or_else(|| go_identifier(name))
    }

    fn emit_named(&mut self, name: &str, source: &str, shape: &Shape) -> Result<()> {
        if let Some(properties) = self.structural_properties(shape, &mut BTreeSet::new()) {
            self.emit_struct(name, Some(source), properties, shape)?;
        } else if let Some(projected) = self.intersection_union(shape) {
            self.emit_union(name, Some(source), &projected)?;
            self.decoder_shapes.insert(name.to_owned(), shape.clone());
        } else if matches!(shape, Shape::Literal { .. } | Shape::Enum { .. }) {
            self.emit_value_type(name, Some(source), shape)?;
        } else if let Shape::Union { .. } = shape {
            self.emit_union(name, Some(source), shape)?;
        } else {
            let rendered = self.render_type(shape, &format!("{name}Value"))?;
            if matches!(shape, Shape::Ref { .. }) {
                // A pointer alias lets encoding/json accept null without calling
                // the target decoder. Value aliases inherit its validation methods.
                let rendered = rendered.trim_start_matches('*');
                self.declarations.push(format!(
                    "// {name} is generated from {source}.\ntype {name} = {rendered}\n\n"
                ));
            } else {
                self.emit_checked_type(name, &rendered, shape)?;
            }
        }
        Ok(())
    }

    fn emit_checked_type(&mut self, name: &str, rendered: &str, shape: &Shape) -> Result<()> {
        self.decoder_shapes.insert(name.to_owned(), shape.clone());
        let declaration = format!(
            "// {name} is a structurally validated schema value.\ntype {name} {rendered}\n\nfunc (value *{name}) unmarshalValidatedJSON(data []byte) error {{\n\tvar decoded {rendered}\n\tif err := decodeValidatedJSON(data, &decoded); err != nil {{\n\t\treturn err\n\t}}\n\t*value = {name}(decoded)\n\treturn nil\n}}\n\nfunc (value {name}) MarshalJSON() ([]byte, error) {{\n\treturn json.Marshal({rendered}(value))\n}}\n\n"
        );
        self.declarations.push(declaration);
        Ok(())
    }

    /// Flatten object intersections for useful root models. Duplicate property
    /// constraints are intersected commutatively and requiredness is cumulative.
    fn structural_properties(
        &self,
        shape: &Shape,
        visiting: &mut BTreeSet<String>,
    ) -> Option<Vec<Property>> {
        match shape {
            Shape::Object { properties, .. } => Some(properties.clone()),
            Shape::Intersection { variants } => {
                let mut merged = Vec::<Property>::new();
                if variants.iter().all(|variant| matches!(variant, Shape::Any)) {
                    return None;
                }
                for variant in variants {
                    if matches!(variant, Shape::Any) {
                        continue;
                    }
                    for property in self.intersection_properties(variant, visiting)? {
                        if let Some(existing) = merged
                            .iter_mut()
                            .find(|existing| existing.wire_name == property.wire_name)
                        {
                            existing.required |= property.required;
                            if existing.constructor_default.is_none() {
                                existing.constructor_default = property.constructor_default.clone();
                            }
                            existing.shape = intersect_shapes(
                                std::mem::replace(&mut existing.shape, Shape::Any),
                                property.shape,
                            );
                        } else {
                            merged.push(property);
                        }
                    }
                }
                Some(merged)
            }
            Shape::Ref { name } => {
                if !visiting.insert(name.clone()) {
                    return None;
                }
                let result = self
                    .ir
                    .types
                    .iter()
                    .find(|named| named.name == *name)
                    .and_then(|named| self.structural_properties(&named.shape, visiting));
                visiting.remove(name);
                result
            }
            _ => None,
        }
    }

    /// Project predicate unions only inside intersections. A property absent in
    /// one branch is unconstrained there (unknown fields are retained), so it
    /// cannot narrow the enclosing object's property type or requiredness.
    /// This is a representation only: emit_struct keeps the original descriptor.
    fn intersection_properties(
        &self,
        shape: &Shape,
        visiting: &mut BTreeSet<String>,
    ) -> Option<Vec<Property>> {
        let Shape::Union { variants, .. } = shape else {
            return self.structural_properties(shape, visiting);
        };
        if variants.is_empty() {
            return None;
        }
        let branches = variants
            .iter()
            .map(|variant| self.intersection_properties(variant, visiting))
            .collect::<Option<Vec<_>>>()?;
        let names = branches
            .iter()
            .flatten()
            .map(|p| p.wire_name.clone())
            .collect::<BTreeSet<_>>();
        Some(
            names
                .into_iter()
                .map(|wire_name| {
                    let members = branches
                        .iter()
                        .map(|branch| branch.iter().find(|p| p.wire_name == wire_name))
                        .collect::<Vec<_>>();
                    let required = members.iter().all(|p| p.is_some_and(|p| p.required));
                    let mut shapes = members
                        .iter()
                        .map(|p| p.map_or(Shape::Any, |p| p.shape.clone()))
                        .collect::<Vec<_>>();
                    shapes.sort_by_cached_key(|s| {
                        serde_json::to_string(s).expect("shape serializes")
                    });
                    shapes.dedup_by(|a, b| {
                        serde_json::to_value(a).unwrap() == serde_json::to_value(b).unwrap()
                    });
                    let shape = if shapes.iter().any(|s| matches!(s, Shape::Any)) {
                        Shape::Any
                    } else if shapes.len() == 1 {
                        shapes.pop().expect("one property shape")
                    } else {
                        Shape::Union {
                            mode: crate::model::UnionMode::AnyOf,
                            variants: shapes,
                            discriminator: None,
                        }
                    };
                    Property {
                        wire_name,
                        required,
                        shape,
                        constructor_default: None,
                    }
                })
                .collect(),
        )
    }

    /// Distribute an object intersection over a referenced object union for
    /// its public representation (for example ContentItem plus role). The
    /// original descriptor still owns acceptance; this union only selects fields.
    fn intersection_union(&self, shape: &Shape) -> Option<Shape> {
        let Shape::Intersection { variants } = shape else {
            return None;
        };
        for (index, variant) in variants.iter().enumerate() {
            let mut resolved = variant;
            let mut visiting = BTreeSet::new();
            while let Shape::Ref { name } = resolved {
                if !visiting.insert(name) {
                    return None;
                }
                resolved = &self.ir.types.iter().find(|t| t.name == *name)?.shape;
            }
            if let Shape::Union {
                mode,
                variants: arms,
                discriminator,
            } = resolved
            {
                if arms.is_empty()
                    || !arms.iter().all(|arm| {
                        self.structural_properties(arm, &mut BTreeSet::new())
                            .is_some()
                    })
                {
                    continue;
                }
                return Some(Shape::Union {
                    mode: *mode,
                    discriminator: discriminator.clone(),
                    variants: arms
                        .iter()
                        .map(|arm| Shape::Intersection {
                            variants: variants
                                .iter()
                                .enumerate()
                                .map(|(i, other)| {
                                    if i == index {
                                        arm.clone()
                                    } else {
                                        other.clone()
                                    }
                                })
                                .collect(),
                        })
                        .collect(),
                });
            }
        }
        None
    }

    fn emit_struct(
        &mut self,
        name: &str,
        source: Option<&str>,
        mut properties: Vec<Property>,
        shape: &Shape,
    ) -> Result<()> {
        self.decoder_shapes.insert(name.to_owned(), shape.clone());
        properties.sort_by(|left, right| left.wire_name.cmp(&right.wire_name));
        let mut fields = Vec::with_capacity(properties.len());
        let mut field_names = BTreeSet::from(["AdditionalProperties".to_owned()]);
        for property in properties {
            let base = go_identifier(&property.wire_name);
            let field_name = allocate_local_name(&base, &mut field_names);
            let hint = format!("{name}{field_name}");
            let field_type = self.render_type(&property.shape, &hint)?;
            fields.push(RenderedField {
                wire_name: property.wire_name,
                field_name,
                field_type,
                required: property.required,
                constructor_default: property.constructor_default.clone(),
                shape: property.shape.clone(),
            });
        }

        self.objects.insert(name.to_owned(), fields.clone());
        let mut declaration = String::new();
        let field_width = fields
            .iter()
            .map(|field| field.field_name.len())
            .chain(std::iter::once("AdditionalProperties".len()))
            .max()
            .expect("AdditionalProperties is always present")
            + 1;
        match source {
            Some(source) => writeln!(declaration, "// {name} is generated from {source}.")?,
            None => writeln!(declaration, "// {name} is a generated nested model.")?,
        }
        writeln!(declaration, "type {name} struct {{")?;
        for field in &fields {
            if field.required {
                writeln!(
                    declaration,
                    "\t{:<width$}{}",
                    field.field_name,
                    field.field_type,
                    width = field_width
                )?;
            } else {
                writeln!(
                    declaration,
                    "\t{:<width$}Optional[{}]",
                    field.field_name,
                    field.field_type,
                    width = field_width
                )?;
            }
        }
        writeln!(
            declaration,
            "\t{:<width$}map[string]json.RawMessage",
            "AdditionalProperties",
            width = field_width
        )?;
        writeln!(declaration, "}}\n")?;

        writeln!(
            declaration,
            "// UnmarshalJSON retains members not known to this schema revision."
        )?;
        writeln!(
            declaration,
            "func (value *{name}) unmarshalValidatedJSON(data []byte) error {{"
        )?;
        writeln!(
            declaration,
            "\tvar fields map[string]json.RawMessage\n\tif err := json.Unmarshal(data, &fields); err != nil {{\n\t\treturn err\n\t}}"
        )?;
        writeln!(
            declaration,
            "\tif fields == nil {{\n\t\treturn fmt.Errorf({})\n\t}}",
            go_string(&format!("{name} must be a JSON object"))?
        )?;
        writeln!(declaration, "\tvar decoded {name}")?;
        for field in &fields {
            writeln!(
                declaration,
                "\tif raw, ok := fields[{}]; ok {{",
                go_string(&field.wire_name)?
            )?;
            if field.required {
                writeln!(
                    declaration,
                    "\t\tif err := decodeValidatedJSON(raw, &decoded.{}); err != nil {{",
                    field.field_name
                )?;
            } else {
                writeln!(
                    declaration,
                    "\t\tdecoded.{}.Present = true\n\t\tif err := decodeValidatedJSON(raw, &decoded.{}.Value); err != nil {{",
                    field.field_name, field.field_name
                )?;
            }
            writeln!(
                declaration,
                "\t\t\treturn fmt.Errorf({}, err)\n\t\t}}\n\t\tdelete(fields, {})\n\t}}",
                go_string(&format!("{name}.{}: %w", field.wire_name))?,
                go_string(&field.wire_name)?
            )?;
        }
        writeln!(
            declaration,
            "\tdecoded.AdditionalProperties = fields\n\t*value = decoded\n\treturn nil\n}}\n"
        )?;

        writeln!(
            declaration,
            "// MarshalJSON emits known fields together with all retained members."
        )?;
        writeln!(
            declaration,
            "func (value {name}) MarshalJSON() ([]byte, error) {{"
        )?;
        writeln!(
            declaration,
            "\tfields := make(map[string]json.RawMessage, len(value.AdditionalProperties)+{})",
            fields.len()
        )?;
        writeln!(
            declaration,
            "\tfor key, raw := range value.AdditionalProperties {{\n\t\tfields[key] = raw\n\t}}"
        )?;
        for field in &fields {
            if field.required {
                writeln!(declaration, "\t{{")?;
                writeln!(
                    declaration,
                    "\t\traw, err := json.Marshal(value.{})",
                    field.field_name
                )?;
            } else {
                writeln!(declaration, "\tif value.{}.Present {{", field.field_name)?;
                writeln!(
                    declaration,
                    "\t\traw, err := json.Marshal(value.{}.Value)",
                    field.field_name
                )?;
            }
            writeln!(
                declaration,
                "\t\tif err != nil {{\n\t\t\treturn nil, fmt.Errorf({}, err)\n\t\t}}\n\t\tfields[{}] = raw\n\t}}",
                go_string(&format!("{name}.{}: %w", field.wire_name))?,
                go_string(&field.wire_name)?
            )?;
        }
        writeln!(declaration, "\treturn json.Marshal(fields)\n}}\n")?;
        self.declarations.push(declaration);
        Ok(())
    }

    fn emit_value_type(&mut self, name: &str, source: Option<&str>, shape: &Shape) -> Result<()> {
        self.decoder_shapes.insert(name.to_owned(), shape.clone());
        let values = match shape {
            Shape::Literal { value } => std::slice::from_ref(value),
            Shape::Enum { values, .. } => values.as_slice(),
            _ => unreachable!("value types are literals or enums"),
        };
        let base = if values.iter().all(serde_json::Value::is_string) {
            "string"
        } else if values.iter().all(serde_json::Value::is_boolean) {
            "bool"
        } else if values.iter().all(serde_json::Value::is_number) {
            "json.Number"
        } else {
            "json.RawMessage"
        };
        let mut declaration = String::new();
        match source {
            Some(source) => writeln!(declaration, "// {name} is generated from {source}.")?,
            None => writeln!(declaration, "// {name} is a generated schema value.")?,
        }
        if base == "json.RawMessage" {
            writeln!(declaration, "type {name} json.RawMessage")?;
            writeln!(
                declaration,
                "\nfunc (value *{name}) unmarshalValidatedJSON(data []byte) error {{\n\tif _, err := decodeJSON(data); err != nil {{\n\t\treturn err\n\t}}\n\t*value = append((*value)[:0], data...)\n\treturn nil\n}}"
            )?;
            writeln!(
                declaration,
                "\nfunc (value {name}) MarshalJSON() ([]byte, error) {{\n\treturn json.Marshal(json.RawMessage(value))\n}}\n"
            )?;
        } else {
            writeln!(declaration, "type {name} {base}\n")?;
            let names = super::naming::try_literal_names(&values)
                .with_context(|| format!("cannot name Go enum {name}"))?;
            for (value, suffix) in values.iter().zip(names) {
                let suffix = go_semantic_identifier(&suffix);
                let constant = self.allocate_package_name(&format!("{name}{suffix}"));
                let rendered = match value {
                    serde_json::Value::String(value) => go_string(value)?,
                    serde_json::Value::Bool(value) => value.to_string(),
                    serde_json::Value::Number(value) => go_string(&value.to_string())?,
                    _ => continue,
                };
                writeln!(declaration, "const {constant} {name} = {rendered}")?;
            }
            writeln!(
                declaration,
                "\nfunc (value *{name}) unmarshalValidatedJSON(data []byte) error {{\n\tvar decoded {base}\n\tif err := json.Unmarshal(data, &decoded); err != nil {{\n\t\treturn err\n\t}}\n\t*value = {name}(decoded)\n\treturn nil\n}}"
            )?;
            if base == "json.Number" {
                writeln!(
                    declaration,
                    "\nfunc (value {name}) MarshalJSON() ([]byte, error) {{\n\treturn json.Marshal(json.Number(value))\n}}"
                )?;
            }
            declaration.push('\n');
        }
        self.declarations.push(declaration);
        Ok(())
    }

    fn emit_union(&mut self, name: &str, source: Option<&str>, shape: &Shape) -> Result<()> {
        let Shape::Union { variants, .. } = shape else {
            unreachable!("union emitter requires a union");
        };
        if let Some(payload) = self.nullable_payload(shape) {
            let payload_type = self.render_nullable_payload(payload, &format!("{name}Value"))?;
            self.nullables.insert(name.to_owned(), payload_type.clone());
            self.declarations.push(format!("// {name} distinguishes null from a non-null value.\ntype {name} = Nullable[{payload_type}]\n\n"));
            return Ok(());
        }
        let mut fields = Vec::with_capacity(variants.len());
        let mut field_names = BTreeSet::from(["Unknown".to_owned()]);
        let projected = super::naming::projected_union(variants)
            .with_context(|| format!("cannot name Go union {name}"))?;
        for arm in &projected {
            let variant = &variants[arm.source_indices[0]];
            let base = go_semantic_identifier(&arm.name);
            let field_name = allocate_local_name(&base, &mut field_names);
            let field_type = self.render_type(variant, &format!("{name}{field_name}"))?;
            fields.push((field_name, field_type));
        }
        self.unions.insert(name.to_owned(), fields.clone());
        self.union_descriptors
            .insert(name.to_owned(), shape.clone());
        self.decoder_shapes.insert(name.to_owned(), shape.clone());
        let mut declaration = String::new();
        match source {
            Some(source) => writeln!(declaration, "// {name} is generated from {source}.")?,
            None => writeln!(declaration, "// {name} is a generated union model.")?,
        }
        let field_width = fields
            .iter()
            .map(|(field_name, _)| field_name.len())
            .chain(std::iter::once("Unknown".len()))
            .max()
            .expect("Unknown is always present")
            + 1;
        writeln!(declaration, "type {name} struct {{")?;
        for (field_name, field_type) in &fields {
            writeln!(
                declaration,
                "\t{field_name:<field_width$}Optional[{field_type}]"
            )?;
        }
        writeln!(
            declaration,
            "\t{:<field_width$}json.RawMessage\n}}\n",
            "Unknown"
        )?;
        writeln!(
            declaration,
            "func (value *{name}) unmarshalValidatedJSON(data []byte) error {{"
        )?;
        writeln!(
            declaration,
            "\trawValue, err := decodeJSON(data)\n\tif err != nil {{\n\t\treturn err\n\t}}"
        )?;
        writeln!(
            declaration,
            "\tschema := unionDescriptors[{}]",
            go_string(name)?
        )?;
        writeln!(declaration, "\tvar decoded {name}")?;
        for (arm, (field_name, field_type)) in projected.iter().zip(&fields) {
            let index = arm.source_indices[0];
            writeln!(
                declaration,
                "\t{{\n\t\tattempt := make([]ParseDiagnostic, 0)\n\t\tcheckNode(schema.Variants[{index}], rawValue, \"\", &attempt)\n\t\tif !hasErrors(attempt) {{\n\t\t\tvar candidate {field_type}\n\t\t\tif err := decodeValidatedJSON(data, &candidate); err != nil {{\n\t\t\t\treturn fmt.Errorf({}, err)\n\t\t\t}}\n\t\t\tdecoded.{field_name} = Some(candidate)\n\t\t\t*value = decoded\n\t\t\treturn nil\n\t\t}}\n\t}}",
                go_string(&format!("{name}.{field_name}: %w"))?
            )?;
        }
        writeln!(
            declaration,
            "\tdecoded.Unknown = append(json.RawMessage(nil), data...)\n\t*value = decoded\n\treturn nil\n}}\n"
        )?;
        writeln!(
            declaration,
            "func (value {name}) MarshalJSON() ([]byte, error) {{"
        )?;
        writeln!(declaration, "\tselected := 0")?;
        for (field_name, _) in &fields {
            writeln!(
                declaration,
                "\tif value.{field_name}.Present {{\n\t\tselected++\n\t}}"
            )?;
        }
        writeln!(
            declaration,
            "\tif len(value.Unknown) != 0 {{\n\t\tselected++\n\t}}\n\tif selected != 1 {{\n\t\treturn nil, fmt.Errorf({})\n\t}}",
            go_string(&format!("{name}: exactly one variant must be selected"))?
        )?;
        for (field_name, _) in &fields {
            writeln!(
                declaration,
                "\tif value.{field_name}.Present {{\n\t\treturn json.Marshal(value.{field_name}.Value)\n\t}}"
            )?;
        }
        writeln!(declaration, "\treturn json.Marshal(value.Unknown)\n}}\n")?;
        self.declarations.push(declaration);
        Ok(())
    }

    fn render_type(&mut self, shape: &Shape, hint: &str) -> Result<String> {
        if let Some(payload) = self.nullable_payload(shape) {
            let payload_type = self.render_nullable_payload(payload, &format!("{hint}Value"))?;
            let rendered = format!("Nullable[{payload_type}]");
            self.nullables.insert(rendered.clone(), payload_type);
            return Ok(rendered);
        }
        Ok(match shape {
            Shape::Any | Shape::Never | Shape::Null => "json.RawMessage".into(),
            Shape::Boolean => "bool".into(),
            Shape::Integer | Shape::Number => "json.Number".into(),
            Shape::String => "string".into(),
            Shape::Literal { .. } | Shape::Enum { .. } => {
                let name = self.allocate_type_name(hint);
                self.emit_value_type(&name, None, shape)?;
                name
            }
            Shape::Array { items } => {
                format!("[]{}", self.render_type(items, &format!("{hint}Item"))?)
            }
            Shape::Object { properties, .. } => {
                let name = self.allocate_type_name(hint);
                self.emit_struct(&name, None, properties.clone(), shape)?;
                name
            }
            Shape::Ref { name } => {
                if self.is_nullable(shape) {
                    self.named_name(name)
                } else {
                    format!("*{}", self.named_name(name))
                }
            }
            Shape::Union { .. } => {
                let name = self.allocate_type_name(hint);
                self.emit_union(&name, None, shape)?;
                name
            }
            Shape::Intersection { variants } => {
                if let Some(properties) = self.structural_properties(shape, &mut BTreeSet::new()) {
                    let name = self.allocate_type_name(hint);
                    self.emit_struct(&name, None, properties, shape)?;
                    name
                } else if let Some(projected) = self.intersection_union(shape) {
                    let name = self.allocate_type_name(hint);
                    self.emit_union(&name, None, &projected)?;
                    self.decoder_shapes.insert(name.clone(), shape.clone());
                    name
                } else if let Some(representation) = variants
                    .iter()
                    .find(|variant| !matches!(variant, Shape::Any | Shape::Never | Shape::Null))
                {
                    // Every valid intersection value satisfies each conjunct. Use
                    // one typed representation but validate the ORIGINAL descriptor,
                    // including the other conjuncts, on direct and root decoding.
                    // Value conversion avoids invalid Go receiver types over pointers.
                    let rendered = self.render_type(representation, &format!("{hint}Value"))?;
                    let name = self.allocate_type_name(hint);
                    self.emit_checked_type(&name, rendered.trim_start_matches('*'), shape)?;
                    name
                } else {
                    "json.RawMessage".into()
                }
            }
        })
    }

    fn render_nullable_payload(&mut self, shape: &Shape, hint: &str) -> Result<String> {
        let rendered = self.render_type(shape, hint)?;
        // Primitive JSON codecs do not enforce numeric restrictions or array item
        // descriptors. Give these payloads their own model; Nullable stays generic.
        if matches!(shape, Shape::Integer | Shape::Number | Shape::Array { .. })
            || rendered == "json.RawMessage"
        {
            let name = self.allocate_type_name(hint);
            self.emit_checked_type(&name, &rendered, shape)?;
            Ok(name)
        } else {
            Ok(rendered)
        }
    }

    fn nullable_payload<'s>(&self, shape: &'s Shape) -> Option<&'s Shape> {
        let payload = nullable_candidate(shape)?;
        self.excludes_null(payload, &mut BTreeSet::new())
            .then_some(payload)
    }

    fn excludes_null(&self, shape: &Shape, visiting: &mut BTreeSet<String>) -> bool {
        match shape {
            Shape::Any | Shape::Null => false,
            Shape::Literal { value } => !value.is_null(),
            Shape::Enum { values, .. } => values.iter().all(|value| !value.is_null()),
            Shape::Union { variants, .. } => {
                variants.iter().all(|v| self.excludes_null(v, visiting))
            }
            Shape::Intersection { variants } => {
                variants.iter().any(|v| self.excludes_null(v, visiting))
            }
            Shape::Ref { name } => {
                if !visiting.insert(name.clone()) {
                    return false;
                }
                let result = self
                    .ir
                    .types
                    .iter()
                    .find(|n| n.name == *name)
                    .is_some_and(|n| self.excludes_null(&n.shape, visiting));
                visiting.remove(name);
                result
            }
            _ => true,
        }
    }

    fn is_nullable(&self, shape: &Shape) -> bool {
        fn resolve(g: &Generator<'_>, shape: &Shape, visiting: &mut BTreeSet<String>) -> bool {
            if let Shape::Ref { name } = shape {
                if !visiting.insert(name.clone()) {
                    return false;
                }
                return g
                    .ir
                    .types
                    .iter()
                    .find(|n| n.name == *name)
                    .is_some_and(|n| resolve(g, &n.shape, visiting));
            }
            g.nullable_payload(shape).is_some()
        }
        resolve(self, shape, &mut BTreeSet::new())
    }

    fn allocate_type_name(&mut self, hint: &str) -> String {
        let base = go_identifier(hint);
        self.allocate_package_name(&base)
    }

    fn allocate_package_name(&mut self, base: &str) -> String {
        allocate_local_name(base, &mut self.used_names)
    }
}

// This is a public model projection only; validation retains the original union.
fn nullable_candidate(shape: &Shape) -> Option<&Shape> {
    let Shape::Union { variants, .. } = shape else {
        return None;
    };
    if variants.len() != 2 {
        return None;
    }
    match (&variants[0], &variants[1]) {
        (Shape::Null, payload) | (payload, Shape::Null) if !matches!(payload, Shape::Null) => {
            Some(payload)
        }
        _ => None,
    }
}

fn intersect_shapes(left: Shape, right: Shape) -> Shape {
    match (left, right) {
        (Shape::Any, shape) | (shape, Shape::Any) => shape,
        (Shape::Never, _) | (_, Shape::Never) => Shape::Never,
        (left, right) => {
            let mut variants = Vec::new();
            for shape in [left, right] {
                match shape {
                    Shape::Intersection { variants: nested } => variants.extend(nested),
                    shape => variants.push(shape),
                }
            }
            variants.sort_by_cached_key(|shape| {
                serde_json::to_string(shape).expect("shape serializes")
            });
            variants.dedup_by(|left, right| {
                serde_json::to_string(left).expect("shape serializes")
                    == serde_json::to_string(right).expect("shape serializes")
            });
            if variants.len() == 1 {
                variants.pop().expect("one intersection shape")
            } else {
                Shape::Intersection { variants }
            }
        }
    }
}

#[derive(Clone)]
struct RenderedField {
    constructor_default: Option<serde_json::Value>,
    wire_name: String,
    field_name: String,
    field_type: String,
    required: bool,
    shape: Shape,
}

fn runtime_names() -> BTreeSet<String> {
    [
        "SchemaRevision",
        "ProtocolVersionValue",
        "Optional",
        "Nullable",
        "Null",
        "NonNull",
        "Some",
        "DiagnosticCode",
        "DiagnosticInvalidType",
        "DiagnosticMissingRequired",
        "DiagnosticLiteralMismatch",
        "DiagnosticUnknownEnum",
        "DiagnosticUnknownVariant",
        "DiagnosticInvalidKnownVariant",
        "DiagnosticNoUnionMatch",
        "DiagnosticAmbiguousUnion",
        "DiagnosticInvalidJSON",
        "DiagnosticSeverity",
        "SeverityError",
        "SeverityWarning",
        "ParseDiagnostic",
        "ParseResult",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

fn allocate_root_name(base: &str, used: &mut BTreeSet<String>) -> String {
    for suffix in 1.. {
        let candidate = if suffix == 1 {
            base.to_owned()
        } else {
            format!("{base}{suffix}")
        };
        let companions = [
            candidate.clone(),
            format!("Parse{candidate}"),
            format!("Encode{candidate}"),
            format!("{candidate}SchemaRevision"),
        ];
        if companions.iter().all(|name| !used.contains(name)) {
            used.extend(companions);
            return candidate;
        }
    }
    unreachable!()
}

fn allocate_local_name(base: &str, used: &mut BTreeSet<String>) -> String {
    if used.insert(base.to_owned()) {
        return base.to_owned();
    }
    for suffix in 2.. {
        let candidate = format!("{base}{suffix}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!()
}

// Apply Go initialisms to semantic labels without rewriting the shared helper's
// structural collision identity (or its duplicate/disambiguation suffix).
fn go_semantic_identifier(value: &str) -> String {
    if let Some((stem, suffix)) = value.rsplit_once("Shape") {
        if suffix.len() >= 16 && suffix.as_bytes()[..16].iter().all(u8::is_ascii_hexdigit) {
            return format!("{}Shape{suffix}", go_identifier(stem));
        }
    }
    go_identifier(value)
}

fn go_identifier(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase_next {
                result.extend(character.to_uppercase());
                uppercase_next = false;
            } else {
                result.push(character);
            }
        } else {
            uppercase_next = true;
        }
    }
    if result.is_empty() {
        result.push_str("Field");
    }
    if result.as_bytes()[0].is_ascii_digit() {
        result.insert_str(0, "Field");
    }
    match result.to_ascii_lowercase().as_str() {
        "id" => "ID".into(),
        "url" => "URL".into(),
        "uri" => "URI".into(),
        "http" => "HTTP".into(),
        "https" => "HTTPS".into(),
        "jsonrpc" => "JSONRPC".into(),
        "cwd" => "CWD".into(),
        _ => result,
    }
}

fn go_string(value: &str) -> Result<String> {
    Ok(serde_json::to_string(value)?)
}

const IMPORTS: &str = r#"import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"math/big"
	"reflect"
	"strings"
)

"#;

const PRELUDE: &str = r#"// Optional distinguishes an absent member from a present zero or null value.
type Optional[T any] struct {
	Value   T
	Present bool
}

// Some returns a present optional value.
func Some[T any](value T) Optional[T] {
	return Optional[T]{Value: value, Present: true}
}

// Nullable distinguishes JSON null from a non-null value, independently of presence.
// Its zero value is null. Use Optional[Nullable[T]] for an optional nullable member.
type Nullable[T any] struct {
	Value T
	Valid bool
}

// Null returns an explicit JSON null.
func Null[T any]() Nullable[T] { return Nullable[T]{} }

// NonNull returns a non-null payload. Encoding rejects payloads that encode as null.
func NonNull[T any](value T) Nullable[T] { return Nullable[T]{Value: value, Valid: true} }

func (value *Nullable[T]) UnmarshalJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*value = Null[T]()
		return nil
	}
	var payload T
	if err := json.Unmarshal(data, &payload); err != nil {
		return err
	}
	*value = NonNull(payload)
	return nil
}

func (value *Nullable[T]) unmarshalValidatedJSON(data []byte) error {
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		*value = Null[T]()
		return nil
	}
	var payload T
	if err := decodeValidatedJSON(data, &payload); err != nil {
		return err
	}
	*value = NonNull(payload)
	return nil
}

func (value Nullable[T]) MarshalJSON() ([]byte, error) {
	if !value.Valid {
		return []byte("null"), nil
	}
	data, err := json.Marshal(value.Value)
	if err != nil {
		return nil, err
	}
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		return nil, fmt.Errorf("Nullable: non-null payload encoded as null")
	}
	return data, nil
}

// DiagnosticCode identifies a structural parse diagnostic.
type DiagnosticCode string

const (
	DiagnosticInvalidType         DiagnosticCode = "invalid_type"
	DiagnosticMissingRequired     DiagnosticCode = "missing_required"
	DiagnosticLiteralMismatch     DiagnosticCode = "literal_mismatch"
	DiagnosticUnknownEnum         DiagnosticCode = "unknown_enum"
	DiagnosticUnknownVariant      DiagnosticCode = "unknown_variant"
	DiagnosticInvalidKnownVariant DiagnosticCode = "invalid_known_variant"
	DiagnosticNoUnionMatch        DiagnosticCode = "no_union_match"
	DiagnosticAmbiguousUnion      DiagnosticCode = "ambiguous_union"
	DiagnosticInvalidJSON         DiagnosticCode = "invalid_json"
)

// DiagnosticSeverity indicates whether a diagnostic prevents a typed result.
type DiagnosticSeverity string

const (
	SeverityError   DiagnosticSeverity = "error"
	SeverityWarning DiagnosticSeverity = "warning"
)

// ParseDiagnostic describes a structural mismatch at a JSON Pointer path.
type ParseDiagnostic struct {
	Path     string             `json:"path"`
	Code     DiagnosticCode     `json:"code"`
	Severity DiagnosticSeverity `json:"severity"`
	Message  string             `json:"message"`
}

// ParseResult contains the typed value on success and the original JSON on every
// syntactically valid parse. Callers must check OK before using Value.
type ParseResult[T any] struct {
	OK          bool
	Value       T
	Raw         json.RawMessage
	Diagnostics []ParseDiagnostic
}

"#;

const RUNTIME: &str = r#"type schemaProperty struct {
	WireName string      `json:"wire_name"`
	Required bool        `json:"required"`
	Shape    *schemaNode `json:"shape"`
}

type schemaNode struct {
	Kind                  string           `json:"kind"`
	Value                 any              `json:"value"`
	Values                []any            `json:"values"`
	OpenStrings           bool             `json:"open_strings"`
	Items                 *schemaNode      `json:"items"`
	Properties            []schemaProperty `json:"properties"`
	ForbiddenPropertySets [][]string       `json:"forbidden_property_sets"`
	Mode                  string           `json:"mode"`
	Variants              []*schemaNode    `json:"variants"`
	Discriminator         *string          `json:"discriminator"`
	Name                  string           `json:"name"`
}

func loadSchemaDescriptors(source string) map[string]*schemaNode {
	decoder := json.NewDecoder(strings.NewReader(source))
	decoder.UseNumber()
	var descriptors map[string]*schemaNode
	if err := decoder.Decode(&descriptors); err != nil {
		panic(fmt.Sprintf("invalid generated schema descriptors: %v", err))
	}
	return descriptors
}

// validateModelJSON and Parse use the same structural descriptor engine. Warnings
// (open enum values and unknown tagged variants) never become decoding errors.
func validateModelJSON(schema *schemaNode, input []byte) error {
	value, err := decodeJSON(input)
	if err != nil {
		return err
	}
	diagnostics := make([]ParseDiagnostic, 0)
	checkNode(schema, value, "", &diagnostics)
	for _, diagnostic := range diagnostics {
		if diagnostic.Severity == SeverityError {
			return fmt.Errorf("%s: %s: %s", diagnostic.Path, diagnostic.Code, diagnostic.Message)
		}
	}
	return nil
}

// decodeValidatedJSON only hydrates an already-checked subtree. Generated models
// use a private method so each nested struct does not revalidate its descendants.
// Pointer and slice traversal preserves that seam through references and arrays.
// Union selection may still inspect alternatives to select a public arm.
func decodeValidatedJSON(input []byte, target any) error {
	if decoder, ok := target.(interface{ unmarshalValidatedJSON([]byte) error }); ok {
		return decoder.unmarshalValidatedJSON(input)
	}
	if _, ok := target.(json.Unmarshaler); ok {
		return json.Unmarshal(input, target)
	}
	value := reflect.ValueOf(target).Elem()
	switch value.Kind() {
	case reflect.Pointer:
		if bytes.Equal(bytes.TrimSpace(input), []byte("null")) {
			value.SetZero()
			return nil
		}
		decoded := reflect.New(value.Type().Elem())
		if err := decodeValidatedJSON(input, decoded.Interface()); err != nil {
			return err
		}
		value.Set(decoded)
		return nil
	case reflect.Slice:
		var items []json.RawMessage
		if err := json.Unmarshal(input, &items); err != nil {
			return err
		}
		if items == nil {
			value.SetZero()
			return nil
		}
		decoded := reflect.MakeSlice(value.Type(), len(items), len(items))
		for index, item := range items {
			if err := decodeValidatedJSON(item, decoded.Index(index).Addr().Interface()); err != nil {
				return err
			}
		}
		value.Set(decoded)
		return nil
	default:
		return json.Unmarshal(input, target)
	}
}

func parseRoot[T any](name string, input []byte) ParseResult[T] {
	raw := append(json.RawMessage(nil), input...)
	value, err := decodeJSON(input)
	if err != nil {
		return ParseResult[T]{
			Diagnostics: []ParseDiagnostic{{
				Code: DiagnosticInvalidJSON, Severity: SeverityError, Message: err.Error(),
			}},
		}
	}

	diagnostics := make([]ParseDiagnostic, 0)
	checkNode(schemaDescriptors[name], value, "", &diagnostics)
	result := ParseResult[T]{Raw: raw, Diagnostics: diagnostics}
	if hasErrors(diagnostics) {
		return result
	}
	if err := decodeValidatedJSON(input, &result.Value); err != nil {
		result.Diagnostics = append(result.Diagnostics, ParseDiagnostic{
			Code: DiagnosticInvalidType, Severity: SeverityError, Message: err.Error(),
		})
		return result
	}
	result.OK = true
	return result
}

func decodeJSON(input []byte) (any, error) {
	decoder := json.NewDecoder(bytes.NewReader(input))
	decoder.UseNumber()
	var value any
	if err := decoder.Decode(&value); err != nil {
		return nil, err
	}
	var extra any
	if err := decoder.Decode(&extra); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("multiple JSON values")
		}
		return nil, err
	}
	return value, nil
}

func checkNode(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	if schema == nil {
		addError(diagnostics, path, DiagnosticInvalidType, "Missing generated schema")
		return
	}
	switch schema.Kind {
	case "any":
		return
	case "never":
		addError(diagnostics, path, DiagnosticInvalidType, "Value is forbidden")
	case "null":
		if value != nil {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected null")
		}
	case "boolean":
		if _, ok := value.(bool); !ok {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected boolean")
		}
	case "integer":
		if number, ok := value.(json.Number); !ok || !isSafeInteger(number) {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected safely representable integer")
		}
	case "number":
		if number, ok := value.(json.Number); !ok || !isFiniteNumber(number) {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected finite number")
		}
	case "string":
		if _, ok := value.(string); !ok {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected string")
		}
	case "literal":
		if !sameJSON(value, schema.Value) {
			addError(diagnostics, path, DiagnosticLiteralMismatch, fmt.Sprintf("Expected %s", jsonText(schema.Value)))
		}
	case "enum":
		checkEnum(schema, value, path, diagnostics)
	case "array":
		items, ok := value.([]any)
		if !ok {
			addError(diagnostics, path, DiagnosticInvalidType, "Expected array")
			return
		}
		for index, item := range items {
			checkNode(schema.Items, item, fmt.Sprintf("%s/%d", path, index), diagnostics)
		}
	case "object":
		checkObject(schema, value, path, diagnostics)
	case "intersection":
		for _, variant := range schema.Variants {
			checkNode(variant, value, path, diagnostics)
		}
	case "ref":
		checkNode(schemaDescriptors[schema.Name], value, path, diagnostics)
	case "union":
		checkUnion(schema, value, path, diagnostics)
	default:
		addError(diagnostics, path, DiagnosticInvalidType, "Unknown generated schema node")
	}
}

func checkEnum(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	for _, candidate := range schema.Values {
		if sameJSON(candidate, value) {
			return
		}
	}
	if _, ok := value.(string); schema.OpenStrings && ok {
		*diagnostics = append(*diagnostics, ParseDiagnostic{
			Path: path, Code: DiagnosticUnknownEnum, Severity: SeverityWarning,
			Message: fmt.Sprintf("Unknown enum value %s was preserved", jsonText(value)),
		})
		return
	}
	addError(diagnostics, path, DiagnosticInvalidType, "Value does not match the enum's scalar type")
}

func checkObject(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	object, ok := value.(map[string]any)
	if !ok {
		addError(diagnostics, path, DiagnosticInvalidType, "Expected object")
		return
	}
	for _, forbiddenSet := range schema.ForbiddenPropertySets {
		allPresent := true
		for _, key := range forbiddenSet {
			if _, present := object[key]; !present {
				allPresent = false
				break
			}
		}
		if allPresent {
			addError(diagnostics, path, DiagnosticInvalidType, "Forbidden property combination: "+strings.Join(forbiddenSet, ", "))
		}
	}
	for _, property := range schema.Properties {
		child, present := object[property.WireName]
		childPath := joinPath(path, property.WireName)
		if !present {
			if property.Required {
				addError(diagnostics, childPath, DiagnosticMissingRequired, "Required property is absent")
			}
			continue
		}
		checkNode(property.Shape, child, childPath, diagnostics)
	}
}

func checkUnion(schema *schemaNode, value any, path string, diagnostics *[]ParseDiagnostic) {
	if schema.Discriminator != nil {
		object, objectOK := value.(map[string]any)
		actual, discriminatorOK := object[*schema.Discriminator].(string)
		if !objectOK || !discriminatorOK {
			addError(diagnostics, joinPath(path, *schema.Discriminator), DiagnosticInvalidType, "Expected string discriminator")
			return
		}
		branches := make([]*schemaNode, 0)
		for _, candidate := range schema.Variants {
			if discriminatorValue(candidate, *schema.Discriminator) == actual {
				branches = append(branches, candidate)
			}
		}
		if len(branches) == 0 {
			*diagnostics = append(*diagnostics, ParseDiagnostic{
				Path: path, Code: DiagnosticUnknownVariant, Severity: SeverityWarning,
				Message: fmt.Sprintf("Unknown %s variant %s was preserved", *schema.Discriminator, jsonText(actual)),
			})
			return
		}
		// A tag can identify multiple distinct alternatives. Keep source
		// multiplicity for oneOf and do not let the first branch hide later ones.
		matches := make([][]ParseDiagnostic, 0, len(branches))
		var rejected []ParseDiagnostic
		for _, branch := range branches {
			attempt := make([]ParseDiagnostic, 0)
			checkNode(branch, value, path, &attempt)
			if hasErrors(attempt) {
				rejected = append(rejected, attempt...)
			} else {
				matches = append(matches, attempt)
			}
		}
		if len(matches) == 0 {
			*diagnostics = append(*diagnostics, rejected...)
			*diagnostics = append(*diagnostics, ParseDiagnostic{
				Path: path, Code: DiagnosticInvalidKnownVariant, Severity: SeverityError,
				Message: fmt.Sprintf("Known %s variant is malformed", *schema.Discriminator),
			})
		} else if schema.Mode == "oneOf" && len(matches) > 1 {
			addError(diagnostics, path, DiagnosticAmbiguousUnion, "Value matches more than one union branch")
		} else {
			*diagnostics = append(*diagnostics, matches[0]...)
		}
		return
	}

	matches := make([][]ParseDiagnostic, 0, len(schema.Variants))
	for _, variant := range schema.Variants {
		attempt := make([]ParseDiagnostic, 0)
		checkNode(variant, value, path, &attempt)
		if !hasErrors(attempt) {
			matches = append(matches, attempt)
		}
	}
	if len(matches) == 0 {
		addError(diagnostics, path, DiagnosticNoUnionMatch, "Value matches no union branch")
	} else if schema.Mode == "oneOf" && len(matches) > 1 {
		addError(diagnostics, path, DiagnosticAmbiguousUnion, "Value matches more than one union branch")
	} else {
		*diagnostics = append(*diagnostics, matches[0]...)
	}
}

func discriminatorValue(schema *schemaNode, property string) string {
	if schema == nil {
		return ""
	}
	switch schema.Kind {
	case "ref":
		return discriminatorValue(schemaDescriptors[schema.Name], property)
	case "intersection":
		for _, variant := range schema.Variants {
			if value := discriminatorValue(variant, property); value != "" {
				return value
			}
		}
	case "object":
		for _, field := range schema.Properties {
			if field.WireName == property && field.Shape.Kind == "literal" {
				if value, ok := field.Shape.Value.(string); ok {
					return value
				}
			}
		}
	}
	return ""
}

func hasErrors(diagnostics []ParseDiagnostic) bool {
	for _, diagnostic := range diagnostics {
		if diagnostic.Severity == SeverityError {
			return true
		}
	}
	return false
}

type exactDecimal struct {
	Negative bool
	Digits   string
	Exponent *big.Int
}

func exactNumber(number json.Number) (exactDecimal, bool) {
	text := number.String()
	negative := strings.HasPrefix(text, "-")
	if negative {
		text = text[1:]
	}
	mantissa, exponentText := text, "0"
	if index := strings.IndexAny(text, "eE"); index >= 0 {
		mantissa, exponentText = text[:index], text[index+1:]
	}
	exponent, ok := new(big.Int).SetString(exponentText, 10)
	if !ok {
		return exactDecimal{}, false
	}
	whole, fraction := mantissa, ""
	if index := strings.IndexByte(mantissa, '.'); index >= 0 {
		whole, fraction = mantissa[:index], mantissa[index+1:]
	}
	digits := strings.TrimLeft(whole+fraction, "0")
	if digits == "" {
		return exactDecimal{Digits: "0", Exponent: new(big.Int)}, true
	}
	exponent.Sub(exponent, big.NewInt(int64(len(fraction))))
	trimmed := strings.TrimRight(digits, "0")
	exponent.Add(exponent, big.NewInt(int64(len(digits)-len(trimmed))))
	return exactDecimal{Negative: negative, Digits: trimmed, Exponent: exponent}, true
}

func isSafeInteger(number json.Number) bool {
	value, ok := exactNumber(number)
	if !ok || value.Digits == "0" {
		return ok
	}
	if value.Exponent.Sign() < 0 || !value.Exponent.IsInt64() {
		return false
	}
	zeros := value.Exponent.Int64()
	if zeros > 16 || int64(len(value.Digits))+zeros > 16 {
		return false
	}
	digits := value.Digits + strings.Repeat("0", int(zeros))
	return len(digits) < 16 || digits <= "9007199254740991"
}

func isFiniteNumber(number json.Number) bool {
	_, ok := exactNumber(number)
	return ok
}

func sameJSON(left, right any) bool {
	leftNumber, leftIsNumber := left.(json.Number)
	rightNumber, rightIsNumber := right.(json.Number)
	if leftIsNumber || rightIsNumber {
		if !leftIsNumber || !rightIsNumber {
			return false
		}
		leftValue, leftOK := exactNumber(leftNumber)
		rightValue, rightOK := exactNumber(rightNumber)
		return leftOK && rightOK && leftValue.Negative == rightValue.Negative &&
			leftValue.Digits == rightValue.Digits && leftValue.Exponent.Cmp(rightValue.Exponent) == 0
	}
	leftArray, leftIsArray := left.([]any)
	rightArray, rightIsArray := right.([]any)
	if leftIsArray || rightIsArray {
		if !leftIsArray || !rightIsArray || len(leftArray) != len(rightArray) {
			return false
		}
		for index := range leftArray {
			if !sameJSON(leftArray[index], rightArray[index]) {
				return false
			}
		}
		return true
	}
	leftObject, leftIsObject := left.(map[string]any)
	rightObject, rightIsObject := right.(map[string]any)
	if leftIsObject || rightIsObject {
		if !leftIsObject || !rightIsObject || len(leftObject) != len(rightObject) {
			return false
		}
		for key, leftValue := range leftObject {
			rightValue, ok := rightObject[key]
			if !ok || !sameJSON(leftValue, rightValue) {
				return false
			}
		}
		return true
	}
	return reflect.DeepEqual(left, right)
}

func joinPath(path, key string) string {
	escaped := strings.ReplaceAll(strings.ReplaceAll(key, "~", "~0"), "/", "~1")
	return path + "/" + escaped
}

func jsonText(value any) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		return "<invalid JSON>"
	}
	return string(encoded)
}

func addError(diagnostics *[]ParseDiagnostic, path string, code DiagnosticCode, message string) {
	*diagnostics = append(*diagnostics, ParseDiagnostic{
		Path: path, Code: code, Severity: SeverityError, Message: message,
	})
}

"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AdditionalProperties, Ir, NamedType, PublicRoot, Shape, UnionMode};

    fn sample_ir() -> Ir {
        Ir {
            schema_revision: "test-revision".into(),
            protocol_version: "1".into(),
            roots: vec![PublicRoot {
                name: "Message".into(),
                schema: "message.json".into(),
            }],
            types: vec![NamedType {
                name: "Message".into(),
                source: "message.json#".into(),
                shape: Shape::Object {
                    properties: vec![Property {
                        constructor_default: None,
                        wire_name: "displayName".into(),
                        required: false,
                        shape: Shape::String,
                    }],
                    forbidden_property_sets: vec![],
                    additional: AdditionalProperties::Allowed,
                },
            }],
        }
    }

    #[test]
    fn nullable_models_preserve_presence_and_payloads() {
        fn nullable(shape: Shape) -> Shape {
            Shape::Union {
                mode: UnionMode::AnyOf,
                discriminator: None,
                variants: vec![Shape::Null, shape],
            }
        }
        let object = Shape::Object {
            properties: vec![Property {
                wire_name: "value".into(),
                required: true,
                shape: Shape::Any,
                constructor_default: None,
            }],
            forbidden_property_sets: vec![],
            additional: AdditionalProperties::Allowed,
        };
        let payloads = vec![
            ("Text", Shape::String),
            ("Boolean", Shape::Boolean),
            ("Integer", Shape::Integer),
            ("Number", Shape::Number),
            ("Object", object.clone()),
            (
                "Array",
                Shape::Array {
                    items: Box::new(nullable(Shape::String)),
                },
            ),
            (
                "Reference",
                Shape::Ref {
                    name: "Payload".into(),
                },
            ),
        ];
        let mut ir = sample_ir();
        let mut properties = Vec::new();
        for (name, payload) in &payloads {
            for (prefix, required) in [("required", true), ("optional", false)] {
                properties.push(Property {
                    wire_name: format!("{prefix}{name}"),
                    required,
                    shape: nullable(payload.clone()),
                    constructor_default: None,
                });
            }
            let root = format!("Maybe{name}");
            ir.types.push(NamedType {
                name: root.clone(),
                source: format!("{root}.json#"),
                shape: nullable(payload.clone()),
            });
            ir.roots.push(PublicRoot {
                name: root.clone(),
                schema: format!("{root}.json"),
            });
        }
        properties.push(Property {
            wire_name: "optionalNamed".into(),
            required: false,
            shape: Shape::Ref {
                name: "MaybeText".into(),
            },
            constructor_default: None,
        });
        ir.types[0].shape = Shape::Object {
            properties,
            forbidden_property_sets: vec![],
            additional: AdditionalProperties::Allowed,
        };
        ir.types.push(NamedType {
            name: "Payload".into(),
            source: "payload.json#".into(),
            shape: object,
        });
        for (name, mode) in [
            ("Ambiguous", UnionMode::OneOf),
            ("Overlapping", UnionMode::AnyOf),
        ] {
            ir.types.push(NamedType {
                name: name.into(),
                source: format!("{name}.json#"),
                shape: Shape::Union {
                    mode,
                    discriminator: None,
                    variants: vec![Shape::Null, Shape::Any],
                },
            });
            ir.roots.push(PublicRoot {
                name: name.into(),
                schema: format!("{name}.json"),
            });
        }
        for (name, mode) in [
            ("RepeatedAny", UnionMode::AnyOf),
            ("RepeatedOne", UnionMode::OneOf),
        ] {
            ir.types.push(NamedType {
                name: name.into(),
                source: format!("{name}.json#"),
                shape: Shape::Union {
                    mode,
                    discriminator: None,
                    variants: vec![
                        Shape::Ref {
                            name: "Payload".into(),
                        },
                        Shape::Ref {
                            name: "Payload".into(),
                        },
                    ],
                },
            });
            ir.roots.push(PublicRoot {
                name: name.into(),
                schema: format!("{name}.json"),
            });
        }
        let output = emit(&ir).unwrap();
        assert!(output.contains("Optional[MaybeText]"));
        assert!(!output.contains("Optional[*MaybeText]"));
        assert!(output.contains("Optional[Nullable[string]]"));
        assert!(output.contains("Nullable[MessageRequiredObjectValue]"));
        assert!(output.contains("type MaybeReference = Nullable[*Payload]"));
        let mut reversed = Ir {
            schema_revision: ir.schema_revision.clone(),
            protocol_version: ir.protocol_version.clone(),
            roots: ir
                .roots
                .iter()
                .map(|r| PublicRoot {
                    name: r.name.clone(),
                    schema: r.schema.clone(),
                })
                .collect(),
            types: ir
                .types
                .iter()
                .map(|n| NamedType {
                    name: n.name.clone(),
                    source: n.source.clone(),
                    shape: n.shape.clone(),
                })
                .collect(),
        };
        fn reverse(shape: &mut Shape) {
            match shape {
                Shape::Union { variants, .. } => {
                    variants.reverse();
                    for v in variants {
                        reverse(v);
                    }
                }
                Shape::Object { properties, .. } => {
                    for p in properties {
                        reverse(&mut p.shape);
                    }
                }
                Shape::Array { items } => reverse(items),
                _ => {}
            }
        }
        for named in &mut reversed.types {
            reverse(&mut named.shape);
        }
        let mut a = Generator::new(&ir);
        let mut b = Generator::new(&reversed);
        for named in &ir.types {
            a.emit_named(&named.name, &named.source, &named.shape)
                .unwrap();
        }
        for named in &reversed.types {
            b.emit_named(&named.name, &named.source, &named.shape)
                .unwrap();
        }
        let nullable_declarations = |g: &Generator<'_>| {
            g.declarations
                .iter()
                .filter(|d| !d.contains("type Ambiguous") && !d.contains("type Overlapping"))
                .cloned()
                .collect::<Vec<_>>()
        };
        assert_eq!(
            nullable_declarations(&a),
            nullable_declarations(&b),
            "nullable names must not depend on union order"
        );

        // Exercise generated code without requiring a checked-in synthetic SDK.
        let dir = std::env::temp_dir().join(format!("ahp-go-nullable-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("go.mod"), "module nullabletest\n\ngo 1.24\n").unwrap();
        std::fs::write(dir.join("generated.go"), output).unwrap();
        std::fs::write(dir.join("nullable_test.go"), r#"package ahp
import ("encoding/json"; "reflect"; "testing")
func TestNullableMatrix(t *testing.T) {
    values := map[string]any{"Text":"hello", "Boolean":true, "Integer":float64(3), "Number":1.5,
        "Object":map[string]any{"value":nil}, "Array":[]any{nil,"hello"}, "Reference":map[string]any{"value":nil}}
    // Every required field independently rejects absence; every optional field accepts it.
    for _, requiredNull := range []bool{true,false} {
      for _, optional := range []string{"absent","null","value"} {
        doc := map[string]any{}
        for name, payload := range values {
          if requiredNull { doc["required"+name] = nil } else { doc["required"+name] = payload }
          if optional == "null" { doc["optional"+name] = nil }
          if optional == "value" { doc["optional"+name] = payload }
        }
        raw,_ := json.Marshal(doc)
        parsed := ParseMessage(raw)
        if !parsed.OK { t.Fatalf("matrix %v %s: %+v", requiredNull, optional, parsed.Diagnostics) }
        model := reflect.ValueOf(parsed.Value)
        for name := range values {
          req := model.FieldByName("Required"+name)
          opt := model.FieldByName("Optional"+name)
          if req.FieldByName("Valid").Bool() == requiredNull { t.Fatal("required null/value collapsed",name) }
          if opt.FieldByName("Present").Bool() != (optional != "absent") { t.Fatal("presence collapsed",name) }
          if opt.FieldByName("Value").FieldByName("Valid").Bool() != (optional == "value") { t.Fatal("optional null/value collapsed",name) }
        }
        encoded,err := EncodeMessage(parsed.Value)
        if err != nil { t.Fatal(err) }
        var got any; json.Unmarshal(encoded,&got)
        if !reflect.DeepEqual(got,doc) { t.Fatalf("roundtrip %s => %s",raw,encoded) }
        for name := range values {
          old := doc["required"+name]; delete(doc,"required"+name)
          missing,_ := json.Marshal(doc)
          if ParseMessage(missing).OK { t.Fatal("missing required accepted",name) }
          var direct Message
          if json.Unmarshal(missing,&direct) == nil { t.Fatal("direct decoder coerced missing to null",name) }
          doc["required"+name] = old
        }
      }
    }
    for _, name := range []string{"optionalText", "optionalNamed"} {
      var reused Message
      base := map[string]any{}
      for field := range values { base["required"+field] = nil }
      base[name] = "old"; raw,_ := json.Marshal(base)
      if err := json.Unmarshal(raw,&reused); err != nil { t.Fatal(err) }
      base[name] = nil; raw,_ = json.Marshal(base)
      if err := json.Unmarshal(raw,&reused); err != nil { t.Fatal(err) }
      field := "OptionalText"; if name == "optionalNamed" { field = "OptionalNamed" }
      state := reflect.ValueOf(reused).FieldByName(field)
      if !state.FieldByName("Present").Bool() || state.FieldByName("Value").FieldByName("Valid").Bool() { t.Fatal("named null collapsed", name) }
      delete(base,name); raw,_ = json.Marshal(base)
      if err := json.Unmarshal(raw,&reused); err != nil { t.Fatal(err) }
      if reflect.ValueOf(reused).FieldByName(field).FieldByName("Present").Bool() { t.Fatal("absent reuse retained old state", name) }
    }
    if !ParseRepeatedAny([]byte(`{"value":null}`)).OK { t.Fatal("grouped anyOf rejected") }
    if ParseRepeatedOne([]byte(`{"value":null}`)).OK { t.Fatal("grouped public arm changed oneOf validation") }
    if reflect.TypeOf(RepeatedAny{}).NumField() != 2 { t.Fatal("identical alternatives emitted duplicate public variants") }
    if ParseAmbiguous([]byte(`null`)).OK { t.Fatal("oneOf ambiguity lost") }
    ambiguous := ParseAmbiguous([]byte(`null`))
    if len(ambiguous.Diagnostics) == 0 || ambiguous.Diagnostics[0].Code != DiagnosticAmbiguousUnion { t.Fatal("wrong ambiguity diagnostic", ambiguous.Diagnostics) }
    if !ParseOverlapping([]byte(`null`)).OK { t.Fatal("anyOf null rejected") }
    var directAmbiguous Ambiguous
    if json.Unmarshal([]byte(`null`), &directAmbiguous) == nil { t.Fatal("direct oneOf decoder lost ambiguity") }
    var directOverlapping Overlapping
    if json.Unmarshal([]byte(`null`), &directOverlapping) != nil { t.Fatal("direct anyOf decoder rejected null") }
    if !ParseMaybeText([]byte(`""`)).Value.Valid || !ParseMaybeBoolean([]byte(`false`)).Value.Valid || !ParseMaybeInteger([]byte(`0`)).Value.Valid { t.Fatal("zero values collapsed to null") }
    if !ParseMaybeText([]byte(`null`)).OK || !ParseMaybeText([]byte(`"x"`)).Value.Valid { t.Fatal("root string") }
    if ParseMaybeText([]byte(`false`)).OK { t.Fatal("wrong root primitive accepted") }
    if !ParseMaybeBoolean([]byte(`true`)).Value.Valid || !ParseMaybeInteger([]byte(`4`)).Value.Valid || !ParseMaybeNumber([]byte(`1.5`)).Value.Valid { t.Fatal("primitive roots") }
    if !ParseMaybeObject([]byte(`{"value":null}`)).Value.Valid || ParseMaybeObject([]byte(`null`)).Value.Valid { t.Fatal("root object") }
    if !ParseMaybeArray([]byte(`[null,"x"]`)).Value.Valid || !ParseMaybeReference([]byte(`{"value":null}`)).Value.Valid { t.Fatal("array/ref roots") }
    for _, value := range []any{NonNull((*Payload)(nil)), NonNull([]string(nil)), NonNull(map[string]string(nil)), NonNull(json.RawMessage("null"))} {
      if _,err := json.Marshal(value); err == nil { t.Fatal("NonNull silently encoded null") }
    }
    value := NonNull("old")
    if err := json.Unmarshal([]byte(" \n null \t"),&value); err != nil || value.Valid || value.Value != "" { t.Fatal("stale nullable payload") }
    if data,err := json.Marshal(Null[string]()); err != nil || string(data) != "null" { t.Fatal("null constructor") }
}
"#).unwrap();
        let result = std::process::Command::new("go")
            .args(["test", "./..."])
            .current_dir(&dir)
            .output()
            .expect("Go is required for the nullable codec regression");
        std::fs::remove_dir_all(&dir).unwrap();
        assert!(
            result.status.success(),
            "{}{}",
            String::from_utf8_lossy(&result.stdout),
            String::from_utf8_lossy(&result.stderr)
        );
    }

    #[test]
    fn output_is_deterministic_and_has_lossless_entrypoints() {
        let mut ordered = sample_ir();
        ordered.types.push(NamedType {
            name: "Alpha".into(),
            source: "alpha.json#".into(),
            shape: Shape::String,
        });
        let mut reversed = sample_ir();
        reversed.types.push(NamedType {
            name: "Alpha".into(),
            source: "alpha.json#".into(),
            shape: Shape::String,
        });
        reversed.types.reverse();
        let first = emit(&ordered).unwrap();
        let second = emit(&reversed).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("type Message struct"));
        assert!(first.contains("DisplayName          Optional[string]"));
        assert!(first.contains("AdditionalProperties map[string]json.RawMessage"));
        assert!(first.contains("func ParseMessage(input []byte) ParseResult[Message]"));
        assert!(first.contains("func EncodeMessage(value Message) ([]byte, error)"));
        assert!(first.contains("DiagnosticUnknownVariant"));
    }

    #[test]
    fn renders_nested_models_and_union_aliases() {
        let mut ir = sample_ir();
        ir.types.push(NamedType {
            name: "Envelope".into(),
            source: "envelope.json#".into(),
            shape: Shape::Object {
                properties: vec![Property {
                    constructor_default: None,
                    wire_name: "payload".into(),
                    required: true,
                    shape: Shape::Object {
                        properties: vec![Property {
                            constructor_default: None,
                            wire_name: "id".into(),
                            required: true,
                            shape: Shape::Integer,
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Forbidden,
                    },
                }],
                forbidden_property_sets: vec![],
                additional: AdditionalProperties::Allowed,
            },
        });
        ir.types.push(NamedType {
            name: "Choice".into(),
            source: "choice.json#".into(),
            shape: Shape::Union {
                mode: UnionMode::OneOf,
                variants: vec![Shape::String, Shape::Integer],
                discriminator: None,
            },
        });
        let output = emit(&ir).unwrap();
        assert!(output.contains("type EnvelopePayload struct"));
        assert!(
            output
                .lines()
                .any(|line| line.split_whitespace().eq(["Payload", "EnvelopePayload"]))
        );
        assert!(
            output
                .lines()
                .any(|line| line.split_whitespace().eq(["ID", "json.Number"]))
        );
        assert!(output.contains("type Choice struct"));
        assert!(
            output
                .lines()
                .any(|line| line.split_whitespace().eq(["String", "Optional[string]"]))
        );
        assert!(output.lines().any(|line| {
            line.split_whitespace()
                .eq(["Integer", "Optional[json.Number]"])
        }));
    }

    #[test]
    fn union_public_names_are_semantic_and_reorder_stable() {
        let ir = sample_ir();
        let mut variants = vec![
            Shape::Enum {
                values: vec![serde_json::json!("allow")],
                open_strings: false,
            },
            Shape::String,
            Shape::Null,
            Shape::Object {
                properties: vec![Property {
                    constructor_default: None,
                    wire_name: "value".into(),
                    required: true,
                    shape: Shape::Any,
                }],
                forbidden_property_sets: vec![],
                additional: AdditionalProperties::Allowed,
            },
        ];
        let mut arms = None;
        for _ in 0..2 {
            let mut generator = Generator::new(&ir);
            generator
                .emit_union(
                    "Choice",
                    None,
                    &Shape::Union {
                        mode: UnionMode::AnyOf,
                        variants: variants.clone(),
                        discriminator: None,
                    },
                )
                .unwrap();
            let current = generator.unions["Choice"]
                .iter()
                .cloned()
                .collect::<BTreeMap<_, _>>();
            if let Some(previous) = &arms {
                assert_eq!(previous, &current);
            }
            arms = Some(current);
            let source = generator.declarations.join("\n");
            assert!(!source.contains("Variant1"));
            assert!(source.contains("type ChoiceValueObject struct"));
            assert!(source.contains("Unknown"));
            assert!(source.contains("decoded.Unknown = append(json.RawMessage(nil), data...)"));
            variants.reverse();
        }
    }

    #[test]
    fn semantic_literal_names_preserve_go_initialisms_and_reject_collisions() {
        let mut ir = sample_ir();
        ir.types.push(NamedType {
            name: "HttpTransportType".into(),
            source: "http.json#".into(),
            shape: Shape::Literal {
                value: serde_json::json!("http"),
            },
        });
        let output = emit(&ir).unwrap();
        assert!(output.contains("const HttpTransportTypeHTTP HttpTransportType = \"http\""));
        let variants = vec![
            Shape::Literal {
                value: serde_json::json!("http"),
            },
            Shape::Literal {
                value: serde_json::json!("HTTP"),
            },
        ];
        assert!(
            super::super::naming::projected_union(&variants).is_err(),
            "collisions require explicit semantic disambiguation, not fingerprints"
        );
    }

    #[test]
    fn numeric_constants_follow_values_not_enum_positions() {
        let mut ir = sample_ir();
        let mut values = vec![
            serde_json::json!(-7),
            serde_json::json!(42),
            serde_json::json!(1.5),
        ];
        let mut constants = None;
        for _ in 0..2 {
            ir.types.push(NamedType {
                name: "Code".into(),
                source: "code.json#".into(),
                shape: Shape::Enum {
                    values: values.clone(),
                    open_strings: false,
                },
            });
            let output = emit(&ir).unwrap();
            let current = output
                .lines()
                .filter(|line| line.starts_with("const Code"))
                .map(str::to_owned)
                .collect::<BTreeSet<_>>();
            assert_eq!(current.len(), 3);
            assert!(
                !current
                    .iter()
                    .any(|line| line.starts_with("const CodeValue1 "))
            );
            if let Some(previous) = &constants {
                assert_eq!(previous, &current);
            }
            constants = Some(current);
            ir.types.pop();
            values.reverse();
        }
    }

    #[test]
    fn normalizes_colliding_names_and_breaks_recursive_value_cycles() {
        let ir = Ir {
            schema_revision: "test".into(),
            protocol_version: "1".into(),
            roots: vec![PublicRoot {
                name: "Optional".into(),
                schema: "node.json".into(),
            }],
            types: vec![
                NamedType {
                    name: "Optional".into(),
                    source: "node.json#".into(),
                    shape: Shape::Object {
                        properties: vec![Property {
                            constructor_default: None,
                            wire_name: "next".into(),
                            required: false,
                            shape: Shape::Ref {
                                name: "Optional".into(),
                            },
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Allowed,
                    },
                },
                NamedType {
                    name: "optional!".into(),
                    source: "other.json#".into(),
                    shape: Shape::String,
                },
            ],
        };
        let output = emit(&ir).unwrap();
        assert!(output.contains("type Optional2 struct"));
        assert!(output.contains("Next                 Optional[*Optional2]"));
        assert!(output.contains("type Optional3 string"));
        assert!(output.contains("func ParseOptional2"));
    }

    #[test]
    fn emits_named_literals_and_open_enums() {
        let mut ir = sample_ir();
        ir.types.push(NamedType {
            name: "ProtocolVersion".into(),
            source: "protocol.json#".into(),
            shape: Shape::Literal {
                value: serde_json::json!("2.0"),
            },
        });
        ir.types.push(NamedType {
            name: "Mode".into(),
            source: "mode.json#".into(),
            shape: Shape::Enum {
                values: vec![serde_json::json!("strict"), serde_json::json!("open")],
                open_strings: true,
            },
        });
        let output = emit(&ir).unwrap();
        assert!(output.contains("type ProtocolVersion string"));
        assert!(output.contains("const ProtocolVersionValue20 ProtocolVersion = \"2.0\""));
        assert!(output.contains("type Mode string"));
        assert!(output.contains("const ModeStrict Mode = \"strict\""));
    }

    #[test]
    fn intersection_properties_merge_commutatively_with_any_as_identity() {
        fn properties(variants: Vec<Shape>) -> Vec<Property> {
            let shape = Shape::Intersection { variants };
            let ir = Ir {
                schema_revision: "test".into(),
                protocol_version: "1".into(),
                roots: vec![],
                types: vec![],
            };
            Generator::new(&ir)
                .structural_properties(&shape, &mut BTreeSet::new())
                .unwrap()
        }
        fn object(shape: Shape, required: bool) -> Shape {
            Shape::Object {
                properties: vec![Property {
                    constructor_default: None,
                    wire_name: "effects".into(),
                    required,
                    shape,
                }],
                forbidden_property_sets: vec![],
                additional: AdditionalProperties::Allowed,
            }
        }

        let typed = Shape::Array {
            items: Box::new(Shape::String),
        };
        let forward = properties(vec![object(Shape::Any, false), object(typed.clone(), true)]);
        let reverse = properties(vec![object(typed, true), object(Shape::Any, false)]);
        assert_eq!(
            serde_json::to_value(&forward).unwrap(),
            serde_json::to_value(&reverse).unwrap()
        );
        assert!(forward[0].required);
        assert!(matches!(forward[0].shape, Shape::Array { .. }));
    }

    #[test]
    fn go_identifiers_are_exported_and_stable() {
        assert_eq!(go_identifier("eventName"), "EventName");
        assert_eq!(go_identifier("id"), "ID");
        assert_eq!(go_identifier("jsonrpc"), "JSONRPC");
        assert_eq!(go_identifier("future-field"), "FutureField");
        assert_eq!(go_identifier("123"), "Field123");
    }
}

#[cfg(test)]
mod decode_tests;
