use std::{
    collections::{HashMap, HashSet},
    fmt::Write,
};

use anyhow::Result;
use serde_json::Value;

use crate::model::{AdditionalProperties, Ir, Property, Shape};

pub fn emit(ir: &Ir) -> Result<String> {
    let identifiers = IdentifierMap::new(ir);
    let renderer = Renderer {
        ir,
        names: &identifiers.types,
    };
    let mut output = String::new();
    writeln!(output, "# Generated by ahp-codegen. DO NOT EDIT.")?;
    writeln!(
        output,
        "# Generated from AHP schema {}.",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "# The source schema is authoritative if this output conflicts with it.\n"
    )?;
    output.push_str(PRELUDE);
    writeln!(
        output,
        "SCHEMA_REVISION: Final[str] = {}",
        python_string(&ir.schema_revision)?
    )?;
    writeln!(
        output,
        "PROTOCOL_VERSION: Final[str] = {}\n",
        python_string(&ir.protocol_version)?
    )?;

    for named in &ir.types {
        let name = identifiers.type_name(&named.name);
        writeln!(output, "# Source: {}", named.source)?;
        renderer.emit_declarations(&named.shape, name, true, &mut output)?;
        if renderer.model_properties(&named.shape).is_none()
            || matches!(named.shape, Shape::Ref { .. })
        {
            writeln!(
                output,
                "{name}: TypeAlias = {}",
                renderer.render(&named.shape, name)?
            )?;
        }
        output.push('\n');
    }

    let descriptors = ir
        .types
        .iter()
        .map(|named| {
            (
                named.name.clone(),
                serde_json::to_value(&named.shape).expect("shape serializes"),
            )
        })
        .collect::<serde_json::Map<_, _>>();
    let descriptors = serde_json::to_string(&descriptors)?;
    writeln!(
        output,
        "_SCHEMAS: dict[str, _SchemaNode] = json.loads({}, parse_float=Decimal)\n",
        python_string(&descriptors)?
    )?;
    output.push_str(RUNTIME);

    for (index, root) in ir.roots.iter().enumerate() {
        let function = &identifiers.roots[index];
        let type_name = identifiers.type_name(&root.name);
        writeln!(
            output,
            "def parse_{function}(input: str | JsonValue) -> ParseResult[{type_name}]:\n    return cast(ParseResult[{type_name}], _parse_root({}, input))\n",
            python_string(&root.name)?
        )?;
        writeln!(
            output,
            "def encode_{function}(value: {type_name}) -> str:\n    return _encode_json(cast(JsonValue, value))\n"
        )?;
        writeln!(
            output,
            "{function}_schema_revision: Final[str] = SCHEMA_REVISION\n"
        )?;
    }
    Ok(output)
}

struct IdentifierMap {
    types: HashMap<String, String>,
    roots: Vec<String>,
}

impl IdentifierMap {
    fn new(ir: &Ir) -> Self {
        let mut occupied = reserved_identifiers();
        let mut types = HashMap::new();
        for named in &ir.types {
            if !types.contains_key(&named.name) {
                let identifier = allocate_identifier(&named.name, "Type", &mut occupied);
                types.insert(named.name.clone(), identifier);
            }
        }

        let mut roots = Vec::with_capacity(ir.roots.len());
        for root in &ir.roots {
            let candidate = snake_case(&root.name);
            roots.push(allocate_root_identifier(&candidate, "root", &mut occupied));
        }
        Self { types, roots }
    }

    fn type_name(&self, source: &str) -> &str {
        self.types
            .get(source)
            .map(String::as_str)
            .unwrap_or("JsonValue")
    }
}

fn allocate_identifier(value: &str, fallback: &str, occupied: &mut HashSet<String>) -> String {
    let base = sanitize_identifier(value, fallback);
    let mut identifier = base.clone();
    let mut suffix = 2;
    while occupied.contains(&identifier) {
        identifier = format!("{base}_{suffix}");
        suffix += 1;
    }
    occupied.insert(identifier.clone());
    identifier
}

fn allocate_root_identifier(value: &str, fallback: &str, occupied: &mut HashSet<String>) -> String {
    let base = sanitize_identifier(value, fallback);
    let mut identifier = base.clone();
    let mut suffix = 2;
    while occupied.contains(&identifier)
        || occupied.contains(&format!("parse_{identifier}"))
        || occupied.contains(&format!("encode_{identifier}"))
        || occupied.contains(&format!("{identifier}_schema_revision"))
    {
        identifier = format!("{base}_{suffix}");
        suffix += 1;
    }
    occupied.insert(identifier.clone());
    occupied.insert(format!("parse_{identifier}"));
    occupied.insert(format!("encode_{identifier}"));
    occupied.insert(format!("{identifier}_schema_revision"));
    identifier
}

fn sanitize_identifier(value: &str, fallback: &str) -> String {
    let mut identifier = String::new();
    for character in value.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            identifier.push(character);
        } else {
            identifier.push('_');
        }
    }
    if identifier.is_empty() {
        identifier.push_str(fallback);
    }
    if identifier.as_bytes()[0].is_ascii_digit() {
        identifier.insert(0, '_');
    }
    identifier
}

fn reserved_identifiers() -> HashSet<String> {
    [
        "False",
        "None",
        "True",
        "and",
        "as",
        "assert",
        "async",
        "await",
        "break",
        "class",
        "continue",
        "def",
        "del",
        "elif",
        "else",
        "except",
        "finally",
        "for",
        "from",
        "global",
        "if",
        "import",
        "in",
        "is",
        "lambda",
        "nonlocal",
        "not",
        "or",
        "pass",
        "raise",
        "return",
        "try",
        "while",
        "with",
        "yield",
        "__debug__",
        "json",
        "math",
        "Decimal",
        "InvalidOperation",
        "Any",
        "Final",
        "Generic",
        "Literal",
        "Never",
        "NotRequired",
        "Required",
        "TypeAlias",
        "TypeVar",
        "TypedDict",
        "Union",
        "cast",
        "JsonPrimitive",
        "JsonValue",
        "JsonObject",
        "OpenString",
        "UnknownVariant",
        "DiagnosticCode",
        "DiagnosticSeverity",
        "ParseDiagnostic",
        "ParseSuccess",
        "ParseFailure",
        "ParseResult",
        "T",
        "SCHEMA_REVISION",
        "PROTOCOL_VERSION",
        "_SCHEMAS",
        "_SchemaNode",
        "_parse_root",
        "_check_node",
        "_check_union",
        "_discriminator_value",
        "_to_safe_json",
        "_encode_json",
        "_encode_json_value",
        "_is_number",
        "_is_integer",
        "_same_json",
        "_display_json",
        "_escape_surrogates",
        "_join_path",
        "_error",
        "_reject_json_constant",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

struct Renderer<'a> {
    ir: &'a Ir,
    names: &'a HashMap<String, String>,
}

impl Renderer<'_> {
    fn emit_declarations(
        &self,
        shape: &Shape,
        hint: &str,
        public: bool,
        output: &mut String,
    ) -> Result<()> {
        // References are declared by their own stable-name entry. Following them here
        // causes direct and mutual recursive object graphs to recurse forever.
        if matches!(shape, Shape::Ref { .. }) {
            return Ok(());
        }
        if let Some(properties) = self.model_properties(shape) {
            for (index, property) in properties.iter().enumerate() {
                self.emit_declarations(
                    &property.shape,
                    &property_hint(hint, index, &property.wire_name),
                    false,
                    output,
                )?;
            }
            let name = self.model_name(hint, public);
            let fields = properties
                .iter()
                .enumerate()
                .map(|(index, property)| {
                    let annotation = self.render(
                        &property.shape,
                        &property_hint(hint, index, &property.wire_name),
                    )?;
                    let wrapper = if property.required {
                        "Required"
                    } else {
                        "NotRequired"
                    };
                    Ok(format!(
                        "{}: {wrapper}[{annotation}]",
                        python_string(&property.wire_name)?
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            if self.allows_additional(shape) {
                let known_fields = self.known_fields_name(&name);
                writeln!(
                    output,
                    "{known_fields} = TypedDict({}, {{{fields}}}, total=False)",
                    python_string(&known_fields)?
                )?;
                writeln!(
                    output,
                    "{name}: TypeAlias = {known_fields} | JsonObject  # permits additional JSON fields"
                )?;
            } else {
                writeln!(
                    output,
                    "{name} = TypedDict({}, {{{fields}}}, total=False)",
                    python_string(&name)?
                )?;
            }
            return Ok(());
        }

        match shape {
            Shape::Array { items } => {
                self.emit_declarations(items, &format!("{hint}Item"), false, output)?
            }
            Shape::Union { variants, .. } | Shape::Intersection { variants } => {
                for (index, variant) in variants.iter().enumerate() {
                    self.emit_declarations(
                        variant,
                        &format!("{hint}Variant{index}"),
                        false,
                        output,
                    )?;
                }
            }
            Shape::Any
            | Shape::Never
            | Shape::Null
            | Shape::Boolean
            | Shape::Integer
            | Shape::Number
            | Shape::String
            | Shape::Literal { .. }
            | Shape::Enum { .. }
            | Shape::Ref { .. }
            | Shape::Object { .. } => {}
        }
        Ok(())
    }

    fn render(&self, shape: &Shape, hint: &str) -> Result<String> {
        Ok(match shape {
            Shape::Any => "JsonValue".into(),
            Shape::Never => "Never".into(),
            Shape::Null => "None".into(),
            Shape::Boolean => "bool".into(),
            Shape::Integer => "int | Decimal".into(),
            Shape::Number => "int | float | Decimal".into(),
            Shape::String => "str".into(),
            Shape::Literal { value } => render_literal(value)?,
            Shape::Enum {
                values,
                open_strings,
            } => render_enum(values, *open_strings)?,
            Shape::Array { items } => {
                format!("list[{}]", self.render(items, &format!("{hint}Item"))?)
            }
            Shape::Ref { name } => {
                python_string(self.names.get(name).map(String::as_str).unwrap_or(name))?
            }
            Shape::Object { .. } => self.model_name(hint, false),
            Shape::Union {
                variants,
                discriminator,
                ..
            } => {
                let mut rendered = variants
                    .iter()
                    .enumerate()
                    .map(|(index, variant)| self.render(variant, &format!("{hint}Variant{index}")))
                    .collect::<Result<Vec<_>>>()?;
                if discriminator.is_some() {
                    rendered.push("UnknownVariant".into());
                }
                render_union(rendered)
            }
            Shape::Intersection { variants } => {
                if self.model_properties(shape).is_some() {
                    self.model_name(hint, false)
                } else {
                    let rendered = variants
                        .iter()
                        .filter(|variant| !matches!(variant, Shape::Any))
                        .enumerate()
                        .map(|(index, variant)| {
                            self.render(variant, &format!("{hint}Variant{index}"))
                        })
                        .collect::<Result<Vec<_>>>()?;
                    if rendered.is_empty() {
                        "JsonValue".into()
                    } else {
                        let simplified = variants
                            .iter()
                            .cloned()
                            .reduce(intersect_shapes)
                            .expect("non-empty intersection");
                        if matches!(simplified, Shape::Intersection { .. }) {
                            // Python has no general intersection type. An unresolved
                            // intersection can still be satisfiable, so stay conservative.
                            "JsonValue".into()
                        } else {
                            self.render(&simplified, hint)?
                        }
                    }
                }
            }
        })
    }

    fn model_properties(&self, shape: &Shape) -> Option<Vec<Property>> {
        self.model_properties_inner(shape, &mut Vec::new())
    }

    fn model_name(&self, hint: &str, public: bool) -> String {
        if public {
            return hint.into();
        }
        let base = format!("_{hint}Model");
        let mut candidate = base.clone();
        let mut suffix = 2;
        while self.names.values().any(|stable| stable == &candidate) {
            candidate = format!("{base}_{suffix}");
            suffix += 1;
        }
        candidate
    }

    fn allows_additional(&self, shape: &Shape) -> bool {
        self.allows_additional_inner(shape, &mut Vec::new())
    }

    fn known_fields_name(&self, name: &str) -> String {
        let base = format!("_{name}KnownFields");
        let mut candidate = base.clone();
        let mut suffix = 2;
        while self.names.values().any(|stable| stable == &candidate) {
            candidate = format!("{base}_{suffix}");
            suffix += 1;
        }
        candidate
    }

    fn allows_additional_inner(&self, shape: &Shape, visiting: &mut Vec<String>) -> bool {
        match shape {
            Shape::Object { additional, .. } => matches!(additional, AdditionalProperties::Allowed),
            Shape::Intersection { variants } => variants
                .iter()
                .any(|variant| self.allows_additional_inner(variant, visiting)),
            Shape::Ref { name } => {
                if visiting.contains(name) {
                    return false;
                }
                let Some(named) = self.ir.types.iter().find(|item| item.name == *name) else {
                    return true;
                };
                visiting.push(name.clone());
                let result = self.allows_additional_inner(&named.shape, visiting);
                visiting.pop();
                result
            }
            _ => false,
        }
    }

    fn model_properties_inner(
        &self,
        shape: &Shape,
        visiting: &mut Vec<String>,
    ) -> Option<Vec<Property>> {
        match shape {
            Shape::Object {
                properties,
                additional,
                ..
            } => {
                match additional {
                    AdditionalProperties::Allowed | AdditionalProperties::Forbidden => {}
                }
                Some(properties.clone())
            }
            Shape::Intersection { variants } => {
                let mut merged = Vec::<Property>::new();
                for variant in variants {
                    if matches!(variant, Shape::Any) {
                        continue;
                    }
                    for property in self.model_properties_inner(variant, visiting)? {
                        if let Some(existing) = merged
                            .iter_mut()
                            .find(|item| item.wire_name == property.wire_name)
                        {
                            existing.required |= property.required;
                            existing.shape =
                                intersect_shapes(existing.shape.clone(), property.shape);
                        } else {
                            merged.push(property);
                        }
                    }
                }
                Some(merged)
            }
            Shape::Ref { name } => {
                if visiting.contains(name) {
                    return None;
                }
                let named = self.ir.types.iter().find(|item| item.name == *name)?;
                visiting.push(name.clone());
                let result = self.model_properties_inner(&named.shape, visiting);
                visiting.pop();
                result
            }
            Shape::Any
            | Shape::Never
            | Shape::Null
            | Shape::Boolean
            | Shape::Integer
            | Shape::Number
            | Shape::String
            | Shape::Literal { .. }
            | Shape::Enum { .. }
            | Shape::Array { .. }
            | Shape::Union { .. } => None,
        }
    }
}

fn intersect_shapes(left: Shape, right: Shape) -> Shape {
    if is_subshape(&left, &right) {
        return left;
    }
    if is_subshape(&right, &left) {
        return right;
    }
    Shape::Intersection {
        variants: vec![left, right],
    }
}

fn is_subshape(candidate: &Shape, broad: &Shape) -> bool {
    if matches!(broad, Shape::Any)
        || serde_json::to_value(candidate).expect("shape serializes")
            == serde_json::to_value(broad).expect("shape serializes")
    {
        return true;
    }
    match (candidate, broad) {
        (Shape::Integer, Shape::Number) => true,
        (Shape::Literal { value }, Shape::String) => value.is_string(),
        (Shape::Literal { value }, Shape::Boolean) => value.is_boolean(),
        (Shape::Literal { value }, Shape::Null) => value.is_null(),
        (Shape::Literal { value }, Shape::Integer) => {
            value.as_i64().is_some() || value.as_u64().is_some()
        }
        (Shape::Literal { value }, Shape::Number) => value.is_number(),
        (Shape::Enum { values, .. }, Shape::String) => values.iter().all(Value::is_string),
        (Shape::Enum { values, .. }, Shape::Integer) => values
            .iter()
            .all(|value| value.as_i64().is_some() || value.as_u64().is_some()),
        (Shape::Enum { values, .. }, Shape::Number) => values.iter().all(Value::is_number),
        _ => false,
    }
}

fn render_union(mut variants: Vec<String>) -> String {
    variants.dedup();
    match variants.len() {
        0 => "Never".into(),
        1 => variants.pop().expect("one variant"),
        _ => format!("Union[{}]", variants.join(", ")),
    }
}

fn render_enum(values: &[Value], open_strings: bool) -> Result<String> {
    if open_strings {
        return Ok("OpenString".into());
    }
    let mut variants = Vec::new();
    for value in values {
        let annotation = match value {
            Value::Number(number) if number.is_f64() => "float".into(),
            Value::Array(_) | Value::Object(_) => "JsonValue".into(),
            _ => format!("Literal[{}]", python_value(value)?),
        };
        if !variants.contains(&annotation) {
            variants.push(annotation);
        }
    }
    Ok(render_union(variants))
}

fn render_literal(value: &Value) -> Result<String> {
    match value {
        Value::Number(number) if number.is_f64() => Ok("float".into()),
        Value::Null | Value::Bool(_) | Value::Number(_) | Value::String(_) => {
            Ok(format!("Literal[{}]", python_value(value)?))
        }
        Value::Array(_) | Value::Object(_) => Ok("JsonValue".into()),
    }
}

fn python_value(value: &Value) -> Result<String> {
    Ok(match value {
        Value::Null => "None".into(),
        Value::Bool(true) => "True".into(),
        Value::Bool(false) => "False".into(),
        Value::Number(number) => number.to_string(),
        Value::String(value) => python_string(value)?,
        Value::Array(_) | Value::Object(_) => "JsonValue".into(),
    })
}

fn property_hint(parent: &str, index: usize, wire_name: &str) -> String {
    format!("{parent}Field{index}{}", pascal_fragment(wire_name))
}

fn python_string(value: &str) -> Result<String> {
    Ok(serde_json::to_string(value)?)
}

fn snake_case(value: &str) -> String {
    let chars = value.chars().collect::<Vec<_>>();
    let mut result = String::new();
    for (index, current) in chars.iter().copied().enumerate() {
        let previous = index
            .checked_sub(1)
            .and_then(|item| chars.get(item))
            .copied();
        let next = chars.get(index + 1).copied();
        if current.is_uppercase()
            && !result.is_empty()
            && (previous.is_some_and(|item| item.is_lowercase() || item.is_ascii_digit())
                || (previous.is_some_and(char::is_uppercase)
                    && next.is_some_and(char::is_lowercase)))
        {
            result.push('_');
        }
        for lowered in current.to_lowercase() {
            result.push(lowered);
        }
    }
    result
}

fn pascal_fragment(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() {
            if uppercase_next {
                result.extend(character.to_uppercase());
                uppercase_next = false;
            } else {
                result.push(character);
            }
        } else {
            uppercase_next = true;
        }
    }
    if result.is_empty() {
        "Field".into()
    } else {
        result
    }
}

const PRELUDE: &str = r#"from __future__ import annotations

import json
import math
from decimal import Decimal, InvalidOperation
from typing import Any, Final, Generic, Literal, Never, NotRequired, Required, TypeAlias, TypeVar, TypedDict, Union, cast

JsonPrimitive: TypeAlias = Union[None, bool, int, float, Decimal, str]
JsonValue: TypeAlias = JsonPrimitive | list["JsonValue"] | dict[str, "JsonValue"]
JsonObject: TypeAlias = dict[str, JsonValue]
OpenString: TypeAlias = str
UnknownVariant: TypeAlias = JsonObject
_SchemaNode: TypeAlias = dict[str, Any]
DiagnosticCode: TypeAlias = Literal["invalid_type", "missing_required", "literal_mismatch", "unknown_enum", "unknown_variant", "invalid_known_variant", "no_union_match", "ambiguous_union", "invalid_json"]
DiagnosticSeverity: TypeAlias = Literal["error", "warning"]

class ParseDiagnostic(TypedDict):
    path: str
    code: DiagnosticCode
    severity: DiagnosticSeverity
    message: str

T = TypeVar("T")

class ParseSuccess(TypedDict, Generic[T]):
    ok: Literal[True]
    value: T
    raw: JsonValue
    diagnostics: tuple[ParseDiagnostic, ...]

class ParseFailure(TypedDict):
    ok: Literal[False]
    raw: NotRequired[JsonValue]
    diagnostics: tuple[ParseDiagnostic, ...]

ParseResult: TypeAlias = ParseSuccess[T] | ParseFailure

"#;

const RUNTIME: &str = r#"def _parse_root(name: str, input: str | JsonValue) -> ParseResult[JsonValue]:
    try:
        raw = _to_safe_json(
            json.loads(
                input,
                parse_float=Decimal,
                parse_constant=_reject_json_constant,
            )
            if isinstance(input, str)
            else input
        )
    except (TypeError, ValueError, InvalidOperation, RecursionError) as error:
        return {
            "ok": False,
            "diagnostics": ({
                "path": "",
                "code": "invalid_json",
                "severity": "error",
                "message": str(error) or "Invalid JSON",
            },),
        }
    diagnostics: list[ParseDiagnostic] = []
    _check_node(_SCHEMAS[name], raw, "", diagnostics)
    frozen = tuple(diagnostics)
    if any(item["severity"] == "error" for item in diagnostics):
        return {"ok": False, "raw": raw, "diagnostics": frozen}
    return {"ok": True, "value": raw, "raw": raw, "diagnostics": frozen}


def _check_node(schema: _SchemaNode, value: JsonValue, path: str, diagnostics: list[ParseDiagnostic]) -> None:
    kind = schema["kind"]
    if kind == "any":
        return
    if kind == "never":
        _error(diagnostics, path, "invalid_type", "Value is forbidden")
    elif kind == "null":
        if value is not None:
            _error(diagnostics, path, "invalid_type", "Expected null")
    elif kind == "boolean":
        if type(value) is not bool:
            _error(diagnostics, path, "invalid_type", "Expected boolean")
    elif kind == "integer":
        if not _is_integer(value) or abs(value) > 9_007_199_254_740_991:
            _error(diagnostics, path, "invalid_type", "Expected safely representable integer")
    elif kind == "number":
        if not _is_number(value):
            _error(diagnostics, path, "invalid_type", "Expected finite number")
    elif kind == "string":
        if not isinstance(value, str):
            _error(diagnostics, path, "invalid_type", "Expected string")
    elif kind == "literal":
        if not _same_json(value, schema["value"]):
            _error(diagnostics, path, "literal_mismatch", f"Expected {_display_json(schema['value'])}")
    elif kind == "enum":
        if any(_same_json(candidate, value) for candidate in schema["values"]):
            return
        if schema["open_strings"] and isinstance(value, str):
            diagnostics.append({
                "path": path,
                "code": "unknown_enum",
                "severity": "warning",
                "message": f"Unknown enum value {_display_json(value)} was preserved",
            })
        else:
            _error(diagnostics, path, "invalid_type", "Value does not match the enum's scalar type")
    elif kind == "array":
        if not isinstance(value, list):
            _error(diagnostics, path, "invalid_type", "Expected array")
            return
        for index, item in enumerate(value):
            _check_node(schema["items"], item, f"{path}/{index}", diagnostics)
    elif kind == "object":
        if not isinstance(value, dict):
            _error(diagnostics, path, "invalid_type", "Expected object")
            return
        for forbidden_set in schema["forbidden_property_sets"]:
            if all(key in value for key in forbidden_set):
                _error(
                    diagnostics,
                    path,
                    "invalid_type",
                    f"Forbidden property combination: {', '.join(forbidden_set)}",
                )
        for property in schema["properties"]:
            wire_name = property["wire_name"]
            if wire_name not in value:
                if property["required"]:
                    _error(
                        diagnostics,
                        _join_path(path, wire_name),
                        "missing_required",
                        "Required property is absent",
                    )
            else:
                _check_node(property["shape"], value[wire_name], _join_path(path, wire_name), diagnostics)
    elif kind == "intersection":
        for variant in schema["variants"]:
            _check_node(variant, value, path, diagnostics)
    elif kind == "ref":
        _check_node(_SCHEMAS[schema["name"]], value, path, diagnostics)
    elif kind == "union":
        _check_union(schema, value, path, diagnostics)


def _check_union(schema: _SchemaNode, value: JsonValue, path: str, diagnostics: list[ParseDiagnostic]) -> None:
    discriminator = schema.get("discriminator")
    if discriminator is not None:
        if not isinstance(value, dict) or not isinstance(value.get(discriminator), str):
            _error(diagnostics, _join_path(path, discriminator), "invalid_type", "Expected string discriminator")
            return
        actual = value[discriminator]
        branch = next(
            (
                variant
                for variant in schema["variants"]
                if _discriminator_value(variant, discriminator) == actual
            ),
            None,
        )
        if branch is None:
            diagnostics.append({
                "path": path,
                "code": "unknown_variant",
                "severity": "warning",
                "message": f"Unknown {discriminator} variant {_display_json(actual)} was preserved",
            })
            return
        branch_diagnostics: list[ParseDiagnostic] = []
        _check_node(branch, value, path, branch_diagnostics)
        diagnostics.extend(branch_diagnostics)
        if any(item["severity"] == "error" for item in branch_diagnostics):
            diagnostics.append({
                "path": path,
                "code": "invalid_known_variant",
                "severity": "error",
                "message": f"Known {discriminator} variant is malformed",
            })
        return

    attempts: list[list[ParseDiagnostic]] = []
    for variant in schema["variants"]:
        attempt: list[ParseDiagnostic] = []
        _check_node(variant, value, path, attempt)
        attempts.append(attempt)
    matches = [
        attempt
        for attempt in attempts
        if not any(item["severity"] == "error" for item in attempt)
    ]
    if not matches:
        _error(diagnostics, path, "no_union_match", "Value matches no union branch")
    elif schema["mode"] == "oneOf" and len(matches) > 1:
        _error(diagnostics, path, "ambiguous_union", "Value matches more than one union branch")
    else:
        diagnostics.extend(matches[0])


def _discriminator_value(schema: _SchemaNode, property: str) -> str | None:
    kind = schema["kind"]
    if kind == "ref":
        return _discriminator_value(_SCHEMAS[schema["name"]], property)
    if kind == "intersection":
        for variant in schema["variants"]:
            value = _discriminator_value(variant, property)
            if value is not None:
                return value
    if kind == "object":
        for field in schema["properties"]:
            if field["wire_name"] == property:
                shape = field["shape"]
                if shape["kind"] == "literal" and isinstance(shape["value"], str):
                    return shape["value"]
    return None


def _to_safe_json(value: object) -> JsonValue:
    if value is None or type(value) in (str, bool, int):
        return cast(JsonPrimitive, value)
    if type(value) is float:
        if not math.isfinite(value):
            raise ValueError("Input contains a non-finite number")
        return value
    if type(value) is Decimal:
        if not value.is_finite():
            raise ValueError("Input contains a non-finite number")
        return value
    if isinstance(value, list):
        return [_to_safe_json(item) for item in value]
    if isinstance(value, dict):
        result: JsonObject = {}
        for key, child in value.items():
            if not isinstance(key, str):
                raise TypeError("JSON object keys must be strings")
            result[key] = _to_safe_json(child)
        return result
    raise TypeError("Input is not a JSON value")


def _encode_json(value: JsonValue) -> str:
    return _encode_json_value(_to_safe_json(value))


def _encode_json_value(value: JsonValue) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return _escape_surrogates(
            json.dumps(value, ensure_ascii=False, separators=(",", ":"))
        )
    if type(value) is int:
        return str(value)
    if type(value) is Decimal:
        if not value.is_finite():
            raise ValueError("Input contains a non-finite number")
        return str(value)
    if type(value) is float:
        return json.dumps(value, allow_nan=False, separators=(",", ":"))
    if isinstance(value, list):
        return "[" + ",".join(_encode_json_value(item) for item in value) + "]"
    return "{" + ",".join(
        _encode_json_value(key) + ":" + _encode_json_value(child)
        for key, child in cast(JsonObject, value).items()
    ) + "}"


def _is_number(value: JsonValue) -> bool:
    return (
        type(value) is int
        or (type(value) is float and math.isfinite(value))
        or (type(value) is Decimal and value.is_finite())
    )


def _is_integer(value: JsonValue) -> bool:
    if type(value) is int:
        return True
    if type(value) is float:
        return math.isfinite(value) and value.is_integer()
    return type(value) is Decimal and value.is_finite() and value == value.to_integral_value()


def _same_json(left: JsonValue, right: JsonValue) -> bool:
    if _is_number(left) and _is_number(right):
        return left == right
    if type(left) is not type(right):
        return False
    if isinstance(left, list):
        right_list = cast(list[JsonValue], right)
        return len(left) == len(right_list) and all(
            _same_json(left_item, right_item)
            for left_item, right_item in zip(left, right_list)
        )
    if isinstance(left, dict):
        right_object = cast(JsonObject, right)
        return left.keys() == right_object.keys() and all(
            _same_json(left[key], right_object[key]) for key in left
        )
    return left == right


def _display_json(value: JsonValue) -> str:
    return _encode_json(value)


def _escape_surrogates(value: str) -> str:
    return "".join(
        f"\\u{ord(character):04x}" if 0xD800 <= ord(character) <= 0xDFFF else character
        for character in value
    )


def _join_path(path: str, key: str) -> str:
    return f"{path}/{key.replace('~', '~0').replace('/', '~1')}"


def _error(
    diagnostics: list[ParseDiagnostic],
    path: str,
    code: DiagnosticCode,
    message: str,
) -> None:
    diagnostics.append({"path": path, "code": code, "severity": "error", "message": message})


def _reject_json_constant(value: str) -> Never:
    raise ValueError(f"Invalid JSON constant {value}")


"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{NamedType, Property, PublicRoot, UnionMode};

    fn sample_ir() -> Ir {
        Ir {
            schema_revision: "test-revision".into(),
            protocol_version: "1".into(),
            roots: vec![PublicRoot {
                name: "JsonRpcMessage".into(),
                schema: "message.json".into(),
            }],
            types: vec![
                NamedType {
                    name: "KnownTransport".into(),
                    source: "message.json#/$defs/known".into(),
                    shape: Shape::Object {
                        properties: vec![
                            Property {
                                wire_name: "type".into(),
                                required: true,
                                shape: Shape::Literal {
                                    value: Value::String("known".into()),
                                },
                            },
                            Property {
                                wire_name: "required/value".into(),
                                required: true,
                                shape: Shape::String,
                            },
                        ],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Forbidden,
                    },
                },
                NamedType {
                    name: "JsonRpcMessage".into(),
                    source: "message.json#".into(),
                    shape: Shape::Object {
                        properties: vec![
                            Property {
                                wire_name: "transport".into(),
                                required: true,
                                shape: Shape::Union {
                                    mode: UnionMode::OneOf,
                                    variants: vec![Shape::Ref {
                                        name: "KnownTransport".into(),
                                    }],
                                    discriminator: Some("type".into()),
                                },
                            },
                            Property {
                                wire_name: "kind".into(),
                                required: false,
                                shape: Shape::Enum {
                                    values: vec![Value::String("known".into())],
                                    open_strings: true,
                                },
                            },
                            Property {
                                wire_name: "meta-data".into(),
                                required: false,
                                shape: Shape::Object {
                                    properties: vec![Property {
                                        wire_name: "trace/id".into(),
                                        required: true,
                                        shape: Shape::String,
                                    }],
                                    forbidden_property_sets: vec![],
                                    additional: AdditionalProperties::Allowed,
                                },
                            },
                        ],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Allowed,
                    },
                },
            ],
        }
    }

    #[test]
    fn output_is_deterministic_typed_and_snake_case() {
        let ir = sample_ir();
        let first = emit(&ir).unwrap();
        let second = emit(&ir).unwrap();
        assert_eq!(first, second);
        assert!(
            first.contains("JsonRpcMessage: TypeAlias = _JsonRpcMessageKnownFields | JsonObject")
        );
        assert!(first.contains("__JsonRpcMessageField2MetaDataModelKnownFields = TypedDict("));
        assert!(!first.contains(": TypeAlias = TypedDict("));
        assert!(!first.contains("ForwardRef("));
        assert!(first.contains("Required["));
        assert!(first.contains("NotRequired[OpenString]"));
        assert!(first.contains("def parse_json_rpc_message("));
        assert!(first.contains("def encode_json_rpc_message("));
        assert!(first.contains("json_rpc_message_schema_revision"));
        assert!(!first.contains("def parseJsonRpcMessage"));
    }

    #[test]
    fn renders_legal_enums_literals_arrays_and_intersections() {
        let ir = sample_ir();
        let identifiers = IdentifierMap::new(&ir);
        let renderer = Renderer {
            ir: &ir,
            names: &identifiers.types,
        };
        assert_eq!(
            renderer
                .render(
                    &Shape::Enum {
                        values: vec![Value::String("x".into()), Value::Bool(true)],
                        open_strings: false,
                    },
                    "Choice"
                )
                .unwrap(),
            "Union[Literal[\"x\"], Literal[True]]"
        );
        assert_eq!(
            renderer
                .render(
                    &Shape::Array {
                        items: Box::new(Shape::Ref {
                            name: "Item".into()
                        })
                    },
                    "Items"
                )
                .unwrap(),
            "list[\"Item\"]"
        );
        assert_eq!(
            renderer
                .render(
                    &Shape::Intersection {
                        variants: vec![Shape::String, Shape::String]
                    },
                    "Combined"
                )
                .unwrap(),
            "str"
        );
        assert_eq!(
            renderer
                .render(
                    &Shape::Intersection {
                        variants: vec![Shape::String, Shape::Number]
                    },
                    "Impossible"
                )
                .unwrap(),
            "JsonValue"
        );
        assert_eq!(
            renderer
                .render(
                    &Shape::Intersection {
                        variants: vec![
                            Shape::String,
                            Shape::Literal {
                                value: Value::String("fixed".into())
                            }
                        ]
                    },
                    "Narrowed"
                )
                .unwrap(),
            "Literal[\"fixed\"]"
        );
        assert_eq!(
            renderer
                .render(
                    &Shape::Literal {
                        value: serde_json::json!(1.5)
                    },
                    "Float"
                )
                .unwrap(),
            "float"
        );
        assert_eq!(snake_case("JSONRpcHTTPMessage"), "json_rpc_http_message");
    }

    #[test]
    fn object_intersections_merge_into_a_typed_model() {
        let mut ir = sample_ir();
        ir.types.push(NamedType {
            name: "Combined".into(),
            source: "combined.json#".into(),
            shape: Shape::Intersection {
                variants: vec![
                    Shape::Ref {
                        name: "JsonRpcMessage".into(),
                    },
                    Shape::Object {
                        properties: vec![Property {
                            wire_name: "extra".into(),
                            required: true,
                            shape: Shape::Integer,
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Allowed,
                    },
                ],
            },
        });
        let source = emit(&ir).unwrap();
        assert!(source.contains("Combined: TypeAlias = _CombinedKnownFields | JsonObject"));
        assert!(source.contains("\"extra\": Required[int | Decimal]"));
    }

    #[test]
    fn direct_and_mutual_recursive_objects_emit_once_without_recursing() {
        let object = |properties| Shape::Object {
            properties,
            forbidden_property_sets: vec![],
            additional: AdditionalProperties::Forbidden,
        };
        let ir = Ir {
            schema_revision: "recursive".into(),
            protocol_version: "test".into(),
            roots: vec![PublicRoot {
                name: "Node".into(),
                schema: "recursive.json".into(),
            }],
            types: vec![
                NamedType {
                    name: "Node".into(),
                    source: "recursive.json#/$defs/node".into(),
                    shape: object(vec![Property {
                        wire_name: "next".into(),
                        required: false,
                        shape: Shape::Ref {
                            name: "Node".into(),
                        },
                    }]),
                },
                NamedType {
                    name: "Left".into(),
                    source: "recursive.json#/$defs/left".into(),
                    shape: object(vec![Property {
                        wire_name: "right".into(),
                        required: false,
                        shape: Shape::Ref {
                            name: "Right".into(),
                        },
                    }]),
                },
                NamedType {
                    name: "Right".into(),
                    source: "recursive.json#/$defs/right".into(),
                    shape: object(vec![Property {
                        wire_name: "left".into(),
                        required: false,
                        shape: Shape::Ref {
                            name: "Left".into(),
                        },
                    }]),
                },
            ],
        };

        let source = emit(&ir).unwrap();
        assert_eq!(source.matches("Node = TypedDict(").count(), 1);
        assert_eq!(source.matches("Left = TypedDict(").count(), 1);
        assert_eq!(source.matches("Right = TypedDict(").count(), 1);
        assert!(source.contains("\"next\": NotRequired[\"Node\"]"));
        assert!(source.contains("\"right\": NotRequired[\"Right\"]"));
        assert!(source.contains("\"left\": NotRequired[\"Left\"]"));
    }

    #[test]
    fn stable_and_root_identifiers_are_reserved_and_collision_safe() {
        let names = ["JsonValue", "class", "A-B", "A_B", "__debug__", "parse_a_b"];
        let ir = Ir {
            schema_revision: "identifiers".into(),
            protocol_version: "test".into(),
            roots: names
                .iter()
                .skip(1)
                .map(|name| PublicRoot {
                    name: (*name).into(),
                    schema: "identifiers.json".into(),
                })
                .collect(),
            types: {
                let mut types = names
                    .iter()
                    .map(|name| NamedType {
                        name: (*name).into(),
                        source: "identifiers.json#".into(),
                        shape: Shape::String,
                    })
                    .collect::<Vec<_>>();
                types.push(NamedType {
                    name: "Foo".into(),
                    source: "identifiers.json#/$defs/foo".into(),
                    shape: Shape::Object {
                        properties: vec![Property {
                            wire_name: "child".into(),
                            required: true,
                            shape: Shape::Object {
                                properties: vec![],
                                forbidden_property_sets: vec![],
                                additional: AdditionalProperties::Forbidden,
                            },
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Forbidden,
                    },
                });
                types.push(NamedType {
                    name: "_FooField0ChildModel".into(),
                    source: "identifiers.json#/$defs/collision".into(),
                    shape: Shape::String,
                });
                types
            },
        };

        let source = emit(&ir).unwrap();
        assert!(source.contains("JsonValue_2: TypeAlias = str"));
        assert!(source.contains("class_2: TypeAlias = str"));
        assert!(source.contains("A_B: TypeAlias = str"));
        assert!(source.contains("A_B_2: TypeAlias = str"));
        assert!(source.contains("__debug___2: TypeAlias = str"));
        assert!(source.contains("_FooField0ChildModel_2 = TypedDict("));
        assert!(source.contains("def parse_class_3("));
        assert!(!source.contains("def parse_a_b("));
        assert!(source.contains("def parse_a_b_2("));
        assert!(source.contains("def parse_a_b_3("));
    }

    #[test]
    fn generated_runtime_preserves_unknowns_and_reports_structural_diagnostics() {
        let source = emit(&sample_ir()).unwrap();
        assert!(source.contains("unknown_variant"));
        assert!(source.contains("invalid_known_variant"));
        assert!(source.contains("unknown_enum"));
        assert!(source.contains("no_union_match"));
        assert!(source.contains("ambiguous_union"));
        assert!(source.contains("return {\"ok\": True, \"value\": raw, \"raw\": raw"));
        assert!(source.contains("result[key] = _to_safe_json(child)"));
        assert!(source.contains("9_007_199_254_740_991"));
        assert!(source.contains("def _escape_surrogates"));
        assert!(source.contains("0xD800 <= ord(character) <= 0xDFFF"));
    }

    #[test]
    fn schema_json_is_embedded_as_data_not_python_source() {
        let mut ir = sample_ir();
        ir.schema_revision = "quotes: \\\" and unicode: snowman".into();
        let source = emit(&ir).unwrap();
        assert!(source.contains("_SCHEMAS: dict[str, _SchemaNode] = json.loads("));
        assert!(source.contains("SCHEMA_REVISION: Final[str]"));
        assert!(!source.contains("const SCHEMAS"));
    }
}
