use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use anyhow::Result;
use serde_json::Value;

use crate::model::{Ir, Property, Shape};

const RESERVED_TYPE_NAMES: &[&str] = &[
    // Imported, prelude, and generated runtime names used unqualified below.
    "BTreeMap",
    "Box",
    "Default",
    "Deserialize",
    "DeserializeOwned",
    "Deserializer",
    "DiagnosticCode",
    "DiagnosticSeverity",
    "Deref",
    "Integer",
    "JsonNumber",
    "JsonValue",
    "OnceLock",
    "Option",
    "ParseDiagnostic",
    "ParseResult",
    "Presence",
    "Result",
    "SchemaNode",
    "SchemaProperty",
    "Serialize",
    "Serializer",
    "String",
    "UnionMode",
    "Vec",
];

/// Emit a self-contained Rust module for the supplied schema IR.
///
/// The generated decoder intentionally performs the same structural checks as
/// the TypeScript SDK. It does not try to reproduce canonical JSON Schema
/// validation. Unknown object members, open-enum strings, and discriminator
/// variants are retained so that decoding and encoding is lossless.
pub fn emit(ir: &Ir) -> Result<String> {
    let mut output = String::new();
    writeln!(output, "// Generated by ahp-codegen. DO NOT EDIT.")?;
    writeln!(
        output,
        "// Dependency: serde_json must enable its `arbitrary_precision` feature."
    )?;
    writeln!(
        output,
        "// Generated from AHP schema {}.",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "// The source schema is authoritative if this output conflicts with it.\n"
    )?;
    writeln!(
        output,
        "pub const SCHEMA_REVISION: &str = {:?};",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "pub const PROTOCOL_VERSION: &str = {:?};\n",
        ir.protocol_version
    )?;
    output.push_str(PRELUDE);

    let mut context = EmitContext::new(ir);
    let mut declarations = String::new();
    for named in &ir.types {
        writeln!(declarations, "/// Source: {}", one_line(&named.source))?;
        let name = context.type_name(&named.name);
        declarations.push_str(&context.emit_declaration(&name, &named.shape)?);
    }
    output.push_str(&declarations);
    output.push_str(&context.helpers);

    let schemas = ir
        .types
        .iter()
        .map(|named| (named.name.as_str(), &named.shape))
        .collect::<BTreeMap<_, _>>();
    let schemas_json = serde_json::to_string(&schemas)?;
    writeln!(output, "const SCHEMAS_JSON: &str = {:?};\n", schemas_json)?;
    output.push_str(RUNTIME);

    let function_names = root_function_names(ir);
    for root in &ir.roots {
        let rust_name = context.type_name(&root.name);
        let function_name = &function_names[&root.name];
        writeln!(
            output,
            "/// Parse and structurally check a `{rust_name}` JSON document.\npub fn parse_{function_name}(input: &str) -> ParseResult<{rust_name}> {{\n    parse_root({:?}, input)\n}}",
            root.name
        )?;
        writeln!(
            output,
            "/// Structurally check an already-decoded `{rust_name}` JSON value.\npub fn parse_{function_name}_value(input: JsonValue) -> ParseResult<{rust_name}> {{\n    parse_root_value({:?}, input)\n}}",
            root.name
        )?;
        writeln!(
            output,
            "/// Encode a `{rust_name}` without applying canonical normalization.\npub fn encode_{function_name}(value: &{rust_name}) -> Result<String, serde_json::Error> {{\n    serde_json::to_string(value)\n}}\n"
        )?;
    }
    Ok(output)
}

struct EmitContext<'a> {
    named_shapes: BTreeMap<&'a str, &'a Shape>,
    type_names: BTreeMap<String, String>,
    used_type_names: BTreeSet<String>,
    helpers: String,
}

impl<'a> EmitContext<'a> {
    fn new(ir: &'a Ir) -> Self {
        let mut used_type_names = RESERVED_TYPE_NAMES
            .iter()
            .map(|name| (*name).to_owned())
            .collect::<BTreeSet<_>>();
        let mut type_names = BTreeMap::new();
        let mut originals = ir
            .types
            .iter()
            .map(|named| named.name.as_str())
            .collect::<Vec<_>>();
        originals.sort_unstable();
        for original in originals {
            type_names.insert(
                original.to_owned(),
                unique_type_identifier(original, &mut used_type_names),
            );
        }
        Self {
            named_shapes: ir
                .types
                .iter()
                .map(|named| (named.name.as_str(), &named.shape))
                .collect(),
            type_names,
            used_type_names,
            helpers: String::new(),
        }
    }

    fn type_name(&self, original: &str) -> String {
        self.type_names
            .get(original)
            .cloned()
            .unwrap_or_else(|| type_identifier(original))
    }

    fn emit_declaration(&mut self, name: &str, shape: &Shape) -> Result<String> {
        match shape {
            Shape::Object { properties, .. } => self.emit_struct(name, properties),
            Shape::Intersection { .. } => {
                let mut visiting = BTreeSet::new();
                if let Some(properties) =
                    collect_object_properties(shape, &self.named_shapes, &mut visiting)
                {
                    self.emit_struct(name, &properties)
                } else {
                    Ok(format!(
                        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(transparent)]\npub struct {name}(pub JsonValue);\n\n"
                    ))
                }
            }
            Shape::Union {
                variants,
                discriminator,
                ..
            } => self.emit_union(name, variants, discriminator.as_deref()),
            Shape::Literal { value } => self.emit_literal(name, value),
            Shape::Enum {
                values,
                open_strings,
            } => self.emit_enum(name, values, *open_strings),
            Shape::Array { items } => {
                let item = self.render_type(items, &format!("{name} item"))?;
                Ok(format!(
                    "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(transparent)]\npub struct {name}(pub Vec<{item}>);\n\n"
                ))
            }
            Shape::Ref { name: target } => {
                let target = self.type_name(target);
                Ok(format!(
                    "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(transparent)]\npub struct {name}(pub Box<{target}>);\n\n"
                ))
            }
            shape => Ok(format!(
                "pub type {name} = {};\n\n",
                self.render_type(shape, name)?
            )),
        }
    }

    fn emit_struct(&mut self, name: &str, properties: &[Property]) -> Result<String> {
        let mut output = String::new();
        writeln!(
            output,
            "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\npub struct {name} {{"
        )?;
        let mut used = BTreeSet::new();
        for property in properties {
            let field = unique_field_identifier(&property.wire_name, &mut used);
            let ty =
                self.render_type(&property.shape, &format!("{name} {}", property.wire_name))?;
            writeln!(output, "    #[serde(rename = {:?})]", property.wire_name)?;
            if property.required {
                writeln!(output, "    pub {field}: {ty},")?;
            } else {
                writeln!(
                    output,
                    "    #[serde(default, skip_serializing_if = \"Presence::is_missing\")]\n    pub {field}: Presence<{ty}>,"
                )?;
            }
        }
        let extra = unique_field_identifier("additional_properties", &mut used);
        writeln!(
            output,
            "    /// Members not known to this schema revision.\n    #[serde(flatten)]\n    pub {extra}: BTreeMap<String, JsonValue>,\n}}\n"
        )?;
        Ok(output)
    }

    fn render_type(&mut self, shape: &Shape, hint: &str) -> Result<String> {
        Ok(match shape {
            Shape::Any | Shape::Never => "JsonValue".into(),
            Shape::Null => "()".into(),
            Shape::Boolean => "bool".into(),
            Shape::Integer => "Integer".into(),
            Shape::Number => "JsonNumber".into(),
            Shape::String => "String".into(),
            Shape::Array { items } => {
                format!("Vec<{}>", self.render_type(items, &format!("{hint} item"))?)
            }
            Shape::Ref { name } => format!("Box<{}>", self.type_name(name)),
            Shape::Literal { .. }
            | Shape::Enum { .. }
            | Shape::Object { .. }
            | Shape::Union { .. }
            | Shape::Intersection { .. } => self.ensure_helper(hint, shape)?,
        })
    }

    fn ensure_helper(&mut self, hint: &str, shape: &Shape) -> Result<String> {
        let name = unique_type_identifier(hint, &mut self.used_type_names);
        let declaration = self.emit_declaration(&name, shape)?;
        writeln!(self.helpers, "/// Inline schema model.")?;
        self.helpers.push_str(&declaration);
        Ok(name)
    }

    fn emit_literal(&self, name: &str, value: &Value) -> Result<String> {
        let encoded = serde_json::to_string(value)?;
        Ok(format!(
            "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct {name};\n\nimpl Serialize for {name} {{\n    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {{\n        let value: JsonValue = serde_json::from_str({encoded:?}).expect(\"generated literal is valid JSON\");\n        value.serialize(serializer)\n    }}\n}}\n\nimpl<'de> Deserialize<'de> for {name} {{\n    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        let value = JsonValue::deserialize(deserializer)?;\n        let expected: JsonValue = serde_json::from_str({encoded:?}).expect(\"generated literal is valid JSON\");\n        if same_json(&value, &expected) {{ Ok(Self) }} else {{ Err(<D::Error as serde::de::Error>::custom(format!(\"expected {{expected}}\"))) }}\n    }}\n}}\n\n"
        ))
    }

    fn emit_enum(&self, name: &str, values: &[Value], open_strings: bool) -> Result<String> {
        let mut used = BTreeSet::from(["Unknown".to_owned()]);
        let variants = values
            .iter()
            .enumerate()
            .map(|(index, value)| (unique_variant_identifier(value, index, &mut used), value))
            .collect::<Vec<_>>();
        let mut output = String::new();
        writeln!(
            output,
            "#[derive(Debug, Clone, PartialEq, Eq)]\npub enum {name} {{"
        )?;
        for (variant, _) in &variants {
            writeln!(output, "    {variant},")?;
        }
        if open_strings {
            writeln!(output, "    Unknown(String),")?;
        }
        writeln!(output, "}}\n")?;
        writeln!(
            output,
            "impl Serialize for {name} {{\n    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {{\n        match self {{"
        )?;
        for (variant, value) in &variants {
            let encoded = serde_json::to_string(value)?;
            writeln!(
                output,
                "            Self::{variant} => {{ let value: JsonValue = serde_json::from_str({encoded:?}).expect(\"generated enum value is valid JSON\"); value.serialize(serializer) }},"
            )?;
        }
        if open_strings {
            writeln!(
                output,
                "            Self::Unknown(value) => value.serialize(serializer),"
            )?;
        }
        writeln!(output, "        }}\n    }}\n}}\n")?;
        writeln!(
            output,
            "impl<'de> Deserialize<'de> for {name} {{\n    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        let value = JsonValue::deserialize(deserializer)?;"
        )?;
        for (variant, expected) in &variants {
            let encoded = serde_json::to_string(expected)?;
            writeln!(
                output,
                "        if same_json(&value, &serde_json::from_str({encoded:?}).expect(\"generated enum value is valid JSON\")) {{ return Ok(Self::{variant}); }}"
            )?;
        }
        if open_strings {
            writeln!(
                output,
                "        if let Some(value) = value.as_str() {{ return Ok(Self::Unknown(value.to_owned())); }}"
            )?;
        }
        writeln!(
            output,
            "        Err(<D::Error as serde::de::Error>::custom(format!(\"unknown value for {name}: {{value}}\")))\n    }}\n}}\n"
        )?;
        Ok(output)
    }

    fn emit_union(
        &mut self,
        name: &str,
        variants: &[Shape],
        discriminator: Option<&str>,
    ) -> Result<String> {
        let mut used = BTreeSet::from(["Unknown".to_owned()]);
        let mut rendered = Vec::new();
        for (index, shape) in variants.iter().enumerate() {
            if matches!(shape, Shape::Never) {
                continue;
            }
            let variant = unique_union_variant_identifier(shape, index, &mut used);
            let discriminator_value = discriminator.and_then(|property| {
                shape_discriminator_value(shape, property, &self.named_shapes, &mut BTreeSet::new())
                    .map(str::to_owned)
            });
            let ty = self.render_type(shape, &format!("{name} {variant}"))?;
            rendered.push((variant, ty, discriminator_value));
        }
        let mut output = String::new();
        if discriminator.is_some() {
            writeln!(
                output,
                "#[derive(Debug, Clone, PartialEq, Serialize)]\n#[serde(untagged)]\npub enum {name} {{"
            )?;
        } else {
            writeln!(
                output,
                "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(untagged)]\npub enum {name} {{"
            )?;
        }
        for (variant, ty, _) in &rendered {
            writeln!(output, "    {variant}({ty}),")?;
        }
        if let Some(discriminator) = discriminator {
            writeln!(
                output,
                "    /// Raw value for a forward-compatible discriminator variant.\n    Unknown(JsonValue),\n}}\n"
            )?;
            writeln!(
                output,
                "impl<'de> Deserialize<'de> for {name} {{\n    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {{\n        let value = JsonValue::deserialize(deserializer)?;\n        let actual = value.as_object()\n            .and_then(|object| object.get({discriminator:?}))\n            .and_then(JsonValue::as_str)\n            .map(str::to_owned)\n            .ok_or_else(|| <D::Error as serde::de::Error>::custom(\"expected string discriminator {discriminator}\"))?;\n        match actual.as_str() {{"
            )?;
            for (variant, ty, value) in &rendered {
                if let Some(value) = value {
                    writeln!(
                        output,
                        "            {value:?} => serde_json::from_value::<{ty}>(value)\n                .map(Self::{variant})\n                .map_err(<D::Error as serde::de::Error>::custom),"
                    )?;
                }
            }
            writeln!(
                output,
                "            _ => Ok(Self::Unknown(value)),\n        }}\n    }}\n}}\n"
            )?;
        } else {
            writeln!(output, "}}\n")?;
        }
        Ok(output)
    }
}

fn root_function_names(ir: &Ir) -> BTreeMap<String, String> {
    let mut roots = ir
        .roots
        .iter()
        .map(|root| root.name.as_str())
        .collect::<Vec<_>>();
    roots.sort_unstable();
    let mut used = BTreeSet::from(["parse_root".to_owned(), "parse_root_value".to_owned()]);
    let mut result = BTreeMap::new();
    for root in roots {
        let base = snake_identifier(root);
        let mut candidate = base.clone();
        let mut suffix = 2;
        loop {
            let functions = [
                format!("parse_{candidate}"),
                format!("parse_{candidate}_value"),
                format!("encode_{candidate}"),
            ];
            if functions.iter().all(|name| !used.contains(name)) {
                used.extend(functions);
                result.insert(root.to_owned(), candidate);
                break;
            }
            candidate = format!("{base}_{suffix}");
            suffix += 1;
        }
    }
    result
}

fn collect_object_properties(
    shape: &Shape,
    named_shapes: &BTreeMap<&str, &Shape>,
    visiting: &mut BTreeSet<String>,
) -> Option<Vec<Property>> {
    match shape {
        Shape::Object { properties, .. } => Some(properties.clone()),
        Shape::Intersection { variants } => {
            let mut merged: Vec<Property> = Vec::new();
            for variant in variants {
                for property in collect_object_properties(variant, named_shapes, visiting)? {
                    if let Some(existing) = merged
                        .iter_mut()
                        .find(|existing| existing.wire_name == property.wire_name)
                    {
                        existing.required |= property.required;
                        existing.shape = intersect_shapes(
                            std::mem::replace(&mut existing.shape, Shape::Any),
                            property.shape,
                        );
                    } else {
                        merged.push(property);
                    }
                }
            }
            Some(merged)
        }
        Shape::Ref { name } => {
            if !visiting.insert(name.clone()) {
                return None;
            }
            let result = named_shapes
                .get(name.as_str())
                .and_then(|shape| collect_object_properties(shape, named_shapes, visiting));
            visiting.remove(name);
            result
        }
        _ => None,
    }
}

fn intersect_shapes(left: Shape, right: Shape) -> Shape {
    match (left, right) {
        (Shape::Any, shape) | (shape, Shape::Any) => shape,
        (Shape::Never, _) | (_, Shape::Never) => Shape::Never,
        (left, right) => {
            let mut variants = Vec::new();
            for shape in [left, right] {
                match shape {
                    Shape::Intersection { variants: nested } => variants.extend(nested),
                    shape => variants.push(shape),
                }
            }
            variants.sort_by_cached_key(|shape| {
                serde_json::to_string(shape).expect("shape serializes")
            });
            variants.dedup_by(|left, right| {
                serde_json::to_string(left).expect("shape serializes")
                    == serde_json::to_string(right).expect("shape serializes")
            });
            if variants.len() == 1 {
                variants.pop().expect("one intersection shape")
            } else {
                Shape::Intersection { variants }
            }
        }
    }
}

fn shape_discriminator_value<'a>(
    shape: &'a Shape,
    property: &str,
    named_shapes: &BTreeMap<&str, &'a Shape>,
    visiting: &mut BTreeSet<String>,
) -> Option<&'a str> {
    match shape {
        Shape::Ref { name } => {
            if !visiting.insert(name.clone()) {
                return None;
            }
            let result = named_shapes.get(name.as_str()).and_then(|shape| {
                shape_discriminator_value(shape, property, named_shapes, visiting)
            });
            visiting.remove(name);
            result
        }
        Shape::Intersection { variants } => variants
            .iter()
            .find_map(|shape| shape_discriminator_value(shape, property, named_shapes, visiting)),
        Shape::Object { properties, .. } => properties.iter().find_map(|candidate| {
            if candidate.wire_name == property {
                match &candidate.shape {
                    Shape::Literal { value } => value.as_str(),
                    _ => None,
                }
            } else {
                None
            }
        }),
        _ => None,
    }
}

fn type_identifier(value: &str) -> String {
    let words = identifier_words(value);
    let mut result = words
        .iter()
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect::<String>(),
                None => String::new(),
            }
        })
        .collect::<String>();
    if result.is_empty() {
        result.push_str("GeneratedType");
    }
    if result.as_bytes()[0].is_ascii_digit() {
        result.insert(0, '_');
    }
    if is_keyword(&result) {
        result.push('_');
    }
    result
}

fn snake_identifier(value: &str) -> String {
    let mut result = identifier_words(value).join("_");
    if result.is_empty() {
        result.push_str("field");
    }
    if result.as_bytes()[0].is_ascii_digit() {
        result.insert(0, '_');
    }
    if is_keyword(&result) {
        result.push('_');
    }
    result
}

fn unique_field_identifier(value: &str, used: &mut BTreeSet<String>) -> String {
    let base = snake_identifier(value);
    let mut candidate = base.clone();
    let mut suffix = 2;
    while !used.insert(candidate.clone()) {
        candidate = format!("{base}_{suffix}");
        suffix += 1;
    }
    candidate
}

fn unique_type_identifier(value: &str, used: &mut BTreeSet<String>) -> String {
    unique_upper_camel_identifier(type_identifier(value), used)
}

fn unique_variant_identifier(value: &Value, index: usize, used: &mut BTreeSet<String>) -> String {
    let label = match value {
        Value::Null => "Null".to_owned(),
        Value::Bool(true) => "True".to_owned(),
        Value::Bool(false) => "False".to_owned(),
        Value::Number(number) if number.to_string().starts_with('-') => {
            format!("Negative {}", &number.to_string()[1..])
        }
        Value::Number(number) => format!("Value {number}"),
        Value::String(value) if value.is_empty() => "Empty".to_owned(),
        Value::String(value) => value.clone(),
        Value::Array(_) => format!("Array {}", index + 1),
        Value::Object(_) => format!("Object {}", index + 1),
    };
    unique_upper_camel_identifier(type_identifier(&label), used)
}

fn unique_union_variant_identifier(
    shape: &Shape,
    index: usize,
    used: &mut BTreeSet<String>,
) -> String {
    let label = match shape {
        Shape::Any => "Any".to_owned(),
        Shape::Never => "Never".to_owned(),
        Shape::Null => "Null".to_owned(),
        Shape::Boolean => "Boolean".to_owned(),
        Shape::Integer => "Integer".to_owned(),
        Shape::Number => "Number".to_owned(),
        Shape::String => "String".to_owned(),
        Shape::Literal { value } => {
            let mut local = BTreeSet::new();
            unique_variant_identifier(value, index, &mut local)
        }
        Shape::Enum { .. } => "Enum".to_owned(),
        Shape::Array { .. } => "Array".to_owned(),
        Shape::Object { .. } => "Object".to_owned(),
        Shape::Union { .. } => "Union".to_owned(),
        Shape::Intersection { .. } => "Intersection".to_owned(),
        Shape::Ref { name } => name.clone(),
    };
    unique_upper_camel_identifier(type_identifier(&label), used)
}

fn unique_upper_camel_identifier(base: String, used: &mut BTreeSet<String>) -> String {
    let mut candidate = base.clone();
    let mut suffix = 2;
    while !used.insert(candidate.clone()) {
        candidate = format!("{base}{suffix}");
        suffix += 1;
    }
    candidate
}

fn identifier_words(value: &str) -> Vec<String> {
    let chars = value.chars().collect::<Vec<_>>();
    let mut words = Vec::new();
    let mut current = String::new();
    for (index, character) in chars.iter().copied().enumerate() {
        if !character.is_ascii_alphanumeric() {
            if !current.is_empty() {
                words.push(current.to_ascii_lowercase());
                current.clear();
            }
            continue;
        }
        let previous = index
            .checked_sub(1)
            .and_then(|item| chars.get(item))
            .copied();
        let next = chars.get(index + 1).copied();
        let boundary = character.is_ascii_uppercase()
            && !current.is_empty()
            && (previous.is_some_and(|item| item.is_ascii_lowercase() || item.is_ascii_digit())
                || next.is_some_and(|item| item.is_ascii_lowercase()));
        if boundary {
            words.push(current.to_ascii_lowercase());
            current.clear();
        }
        current.push(character);
    }
    if !current.is_empty() {
        words.push(current.to_ascii_lowercase());
    }
    words
}

fn is_keyword(value: &str) -> bool {
    matches!(
        value,
        "Self"
            | "abstract"
            | "as"
            | "async"
            | "await"
            | "become"
            | "box"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "do"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "final"
            | "fn"
            | "for"
            | "gen"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "macro"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "override"
            | "priv"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "typeof"
            | "union"
            | "unsafe"
            | "unsized"
            | "use"
            | "virtual"
            | "where"
            | "while"
            | "yield"
    )
}

fn one_line(value: &str) -> String {
    value.replace(['\r', '\n'], " ")
}

const PRELUDE: &str = r#"use std::collections::BTreeMap;
use std::ops::Deref;
use std::sync::OnceLock;

use serde::de::DeserializeOwned;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
pub use serde_json::{Number as JsonNumber, Value as JsonValue};

/// A JSON integer that is exactly usable by every generated SDK. The original
/// JSON number representation is retained, including an integral `1.0`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Integer(JsonNumber);

impl Integer {
    pub fn new(value: JsonNumber) -> Option<Self> {
        is_safe_integer_number(&value).then_some(Self(value))
    }

    pub fn from_i64(value: i64) -> Option<Self> {
        Self::new(JsonNumber::from(value))
    }

    pub fn as_number(&self) -> &JsonNumber {
        &self.0
    }

    pub fn into_number(self) -> JsonNumber {
        self.0
    }
}

impl Serialize for Integer {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for Integer {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = JsonNumber::deserialize(deserializer)?;
        Self::new(value).ok_or_else(|| {
            <D::Error as serde::de::Error>::custom("expected safely representable integer")
        })
    }
}

/// Presence of an optional object member. Unlike `Option`, this distinguishes
/// an absent member from a present member whose schema accepts JSON null.
#[derive(Debug, Clone, PartialEq, Default)]
pub enum Presence<T> {
    #[default]
    Missing,
    Present(T),
}

impl<T> Presence<T> {
    pub fn is_missing(&self) -> bool {
        matches!(self, Self::Missing)
    }

    pub fn as_ref(&self) -> Presence<&T> {
        match self {
            Self::Missing => Presence::Missing,
            Self::Present(value) => Presence::Present(value),
        }
    }
}

impl<T> Deref for Presence<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        match self {
            Self::Present(value) => value,
            Self::Missing => panic!("attempted to dereference a missing optional member"),
        }
    }
}

impl<T: Serialize> Serialize for Presence<T> {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        match self {
            Self::Present(value) => value.serialize(serializer),
            Self::Missing => serializer.serialize_unit(),
        }
    }
}

impl<'de, T: Deserialize<'de>> Deserialize<'de> for Presence<T> {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        T::deserialize(deserializer).map(Self::Present)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DiagnosticCode {
    InvalidType,
    MissingRequired,
    LiteralMismatch,
    UnknownEnum,
    UnknownVariant,
    InvalidKnownVariant,
    NoUnionMatch,
    AmbiguousUnion,
    InvalidJson,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DiagnosticSeverity {
    Error,
    Warning,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ParseDiagnostic {
    pub path: String,
    pub code: DiagnosticCode,
    pub severity: DiagnosticSeverity,
    pub message: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ParseResult<T> {
    Success {
        value: T,
        raw: JsonValue,
        diagnostics: Vec<ParseDiagnostic>,
    },
    Failure {
        raw: Option<JsonValue>,
        diagnostics: Vec<ParseDiagnostic>,
    },
}

impl<T> ParseResult<T> {
    pub fn is_ok(&self) -> bool {
        matches!(self, Self::Success { .. })
    }

    pub fn value(&self) -> Option<&T> {
        match self {
            Self::Success { value, .. } => Some(value),
            Self::Failure { .. } => None,
        }
    }

    pub fn raw(&self) -> Option<&JsonValue> {
        match self {
            Self::Success { raw, .. } => Some(raw),
            Self::Failure { raw, .. } => raw.as_ref(),
        }
    }

    pub fn diagnostics(&self) -> &[ParseDiagnostic] {
        match self {
            Self::Success { diagnostics, .. } | Self::Failure { diagnostics, .. } => diagnostics,
        }
    }

    pub fn into_value(self) -> Option<T> {
        match self {
            Self::Success { value, .. } => Some(value),
            Self::Failure { .. } => None,
        }
    }
}

"#;

const RUNTIME: &str = r#"#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SchemaNode {
    Any,
    Never,
    Null,
    Boolean,
    Integer,
    Number,
    String,
    Literal { value: JsonValue },
    Enum { values: Vec<JsonValue>, open_strings: bool },
    Array { items: Box<SchemaNode> },
    Object {
        properties: Vec<SchemaProperty>,
        forbidden_property_sets: Vec<Vec<String>>,
        #[serde(rename = "additional")]
        _additional: JsonValue,
    },
    Union {
        mode: UnionMode,
        variants: Vec<SchemaNode>,
        discriminator: Option<String>,
    },
    Intersection { variants: Vec<SchemaNode> },
    Ref { name: String },
}

#[derive(Debug, Deserialize)]
struct SchemaProperty {
    wire_name: String,
    required: bool,
    shape: SchemaNode,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "camelCase")]
enum UnionMode {
    AnyOf,
    OneOf,
}

fn schemas() -> &'static BTreeMap<String, SchemaNode> {
    static SCHEMAS: OnceLock<BTreeMap<String, SchemaNode>> = OnceLock::new();
    SCHEMAS.get_or_init(|| {
        serde_json::from_str(SCHEMAS_JSON)
            .expect("ahp-codegen emitted an invalid embedded schema table")
    })
}

fn parse_root<T: DeserializeOwned>(name: &str, input: &str) -> ParseResult<T> {
    match serde_json::from_str(input) {
        Ok(raw) => parse_root_value(name, raw),
        Err(error) => ParseResult::Failure {
            raw: None,
            diagnostics: vec![ParseDiagnostic {
                path: String::new(),
                code: DiagnosticCode::InvalidJson,
                severity: DiagnosticSeverity::Error,
                message: error.to_string(),
            }],
        },
    }
}

fn parse_root_value<T: DeserializeOwned>(name: &str, raw: JsonValue) -> ParseResult<T> {
    let mut diagnostics = Vec::new();
    let schema = schemas()
        .get(name)
        .unwrap_or_else(|| panic!("missing generated schema {name}"));
    check_node(schema, &raw, "", &mut diagnostics);
    if has_errors(&diagnostics) {
        return ParseResult::Failure {
            raw: Some(raw),
            diagnostics,
        };
    }
    match serde_json::from_value(raw.clone()) {
        Ok(value) => ParseResult::Success {
            value,
            raw,
            diagnostics,
        },
        Err(error) => {
            push_error(
                &mut diagnostics,
                "",
                DiagnosticCode::InvalidType,
                format!("Structurally valid value could not be decoded: {error}"),
            );
            ParseResult::Failure {
                raw: Some(raw),
                diagnostics,
            }
        }
    }
}

fn check_node(
    schema: &SchemaNode,
    value: &JsonValue,
    path: &str,
    diagnostics: &mut Vec<ParseDiagnostic>,
) {
    match schema {
        SchemaNode::Any => {}
        SchemaNode::Never => push_error(
            diagnostics,
            path,
            DiagnosticCode::InvalidType,
            "Value is forbidden",
        ),
        SchemaNode::Null => {
            if !value.is_null() {
                push_error(diagnostics, path, DiagnosticCode::InvalidType, "Expected null");
            }
        }
        SchemaNode::Boolean => {
            if !value.is_boolean() {
                push_error(diagnostics, path, DiagnosticCode::InvalidType, "Expected boolean");
            }
        }
        SchemaNode::Integer => {
            if !value.as_number().is_some_and(is_safe_integer_number) {
                push_error(
                    diagnostics,
                    path,
                    DiagnosticCode::InvalidType,
                    "Expected safely representable integer",
                );
            }
        }
        SchemaNode::Number => {
            if !value.is_number() {
                push_error(diagnostics, path, DiagnosticCode::InvalidType, "Expected finite number");
            }
        }
        SchemaNode::String => {
            if !value.is_string() {
                push_error(diagnostics, path, DiagnosticCode::InvalidType, "Expected string");
            }
        }
        SchemaNode::Literal { value: expected } => {
            if !same_json(value, expected) {
                push_error(
                    diagnostics,
                    path,
                    DiagnosticCode::LiteralMismatch,
                    format!("Expected {expected}"),
                );
            }
        }
        SchemaNode::Enum {
            values,
            open_strings,
        } => {
            if !values.iter().any(|expected| same_json(value, expected)) {
                if *open_strings && value.is_string() {
                    diagnostics.push(ParseDiagnostic {
                        path: path.into(),
                        code: DiagnosticCode::UnknownEnum,
                        severity: DiagnosticSeverity::Warning,
                        message: format!("Unknown enum value {value} was preserved"),
                    });
                } else {
                    push_error(
                        diagnostics,
                        path,
                        DiagnosticCode::InvalidType,
                        "Value does not match the enum's scalar type",
                    );
                }
            }
        }
        SchemaNode::Array { items } => match value.as_array() {
            Some(values) => {
                for (index, item) in values.iter().enumerate() {
                    check_node(items, item, &format!("{path}/{index}"), diagnostics);
                }
            }
            None => push_error(diagnostics, path, DiagnosticCode::InvalidType, "Expected array"),
        },
        SchemaNode::Object {
            properties,
            forbidden_property_sets,
            ..
        } => match value.as_object() {
            Some(object) => {
                for forbidden in forbidden_property_sets {
                    if forbidden.iter().all(|key| object.contains_key(key)) {
                        push_error(
                            diagnostics,
                            path,
                            DiagnosticCode::InvalidType,
                            format!("Forbidden property combination: {}", forbidden.join(", ")),
                        );
                    }
                }
                for property in properties {
                    let property_path = join_path(path, &property.wire_name);
                    match object.get(&property.wire_name) {
                        Some(child) => check_node(
                            &property.shape,
                            child,
                            &property_path,
                            diagnostics,
                        ),
                        None if property.required => push_error(
                            diagnostics,
                            &property_path,
                            DiagnosticCode::MissingRequired,
                            "Required property is absent",
                        ),
                        None => {}
                    }
                }
            }
            None => push_error(diagnostics, path, DiagnosticCode::InvalidType, "Expected object"),
        },
        SchemaNode::Intersection { variants } => {
            for variant in variants {
                check_node(variant, value, path, diagnostics);
            }
        }
        SchemaNode::Ref { name } => check_node(schema_named(name), value, path, diagnostics),
        SchemaNode::Union {
            mode,
            variants,
            discriminator,
        } => check_union(
            *mode,
            variants,
            discriminator.as_deref(),
            value,
            path,
            diagnostics,
        ),
    }
}

fn check_union(
    mode: UnionMode,
    variants: &[SchemaNode],
    discriminator: Option<&str>,
    value: &JsonValue,
    path: &str,
    diagnostics: &mut Vec<ParseDiagnostic>,
) {
    if let Some(discriminator) = discriminator {
        let Some(actual) = value
            .as_object()
            .and_then(|object| object.get(discriminator))
            .and_then(JsonValue::as_str)
        else {
            push_error(
                diagnostics,
                &join_path(path, discriminator),
                DiagnosticCode::InvalidType,
                "Expected string discriminator",
            );
            return;
        };
        let branch = variants.iter().find(|variant| {
            discriminator_value(variant, discriminator).is_some_and(|known| known == actual)
        });
        let Some(branch) = branch else {
            diagnostics.push(ParseDiagnostic {
                path: path.into(),
                code: DiagnosticCode::UnknownVariant,
                severity: DiagnosticSeverity::Warning,
                message: format!("Unknown {discriminator} variant {actual:?} was preserved"),
            });
            return;
        };
        let mut branch_diagnostics = Vec::new();
        check_node(branch, value, path, &mut branch_diagnostics);
        let malformed = has_errors(&branch_diagnostics);
        diagnostics.append(&mut branch_diagnostics);
        if malformed {
            push_error(
                diagnostics,
                path,
                DiagnosticCode::InvalidKnownVariant,
                format!("Known {discriminator} variant is malformed"),
            );
        }
        return;
    }

    let attempts = variants
        .iter()
        .map(|variant| {
            let mut attempt = Vec::new();
            check_node(variant, value, path, &mut attempt);
            attempt
        })
        .collect::<Vec<_>>();
    let matches = attempts
        .iter()
        .filter(|attempt| !has_errors(attempt))
        .collect::<Vec<_>>();
    if matches.is_empty() {
        push_error(
            diagnostics,
            path,
            DiagnosticCode::NoUnionMatch,
            "Value matches no union branch",
        );
    } else if mode == UnionMode::OneOf && matches.len() > 1 {
        push_error(
            diagnostics,
            path,
            DiagnosticCode::AmbiguousUnion,
            "Value matches more than one union branch",
        );
    } else {
        diagnostics.extend(matches[0].iter().cloned());
    }
}

fn discriminator_value<'a>(schema: &'a SchemaNode, property: &str) -> Option<&'a str> {
    match schema {
        SchemaNode::Ref { name } => discriminator_value(schema_named(name), property),
        SchemaNode::Intersection { variants } => variants
            .iter()
            .find_map(|variant| discriminator_value(variant, property)),
        SchemaNode::Object { properties, .. } => properties.iter().find_map(|candidate| {
            if candidate.wire_name == property {
                match &candidate.shape {
                    SchemaNode::Literal { value } => value.as_str(),
                    _ => None,
                }
            } else {
                None
            }
        }),
        _ => None,
    }
}

fn is_safe_integer_number(number: &JsonNumber) -> bool {
    const MAX_SAFE_INTEGER: &str = "9007199254740991";
    let Some((_, digits, scale)) = normalized_number(number) else {
        return false;
    };
    if digits == "0" {
        return true;
    }
    let Ok(scale) = usize::try_from(scale) else {
        return false;
    };
    let Some(length) = digits.len().checked_add(scale) else {
        return false;
    };
    length < MAX_SAFE_INTEGER.len()
        || (length == MAX_SAFE_INTEGER.len()
            && format!("{digits}{}", "0".repeat(scale)).as_str() <= MAX_SAFE_INTEGER)
}

fn same_json(left: &JsonValue, right: &JsonValue) -> bool {
    match (left, right) {
        (JsonValue::Number(left), JsonValue::Number(right)) => same_number(left, right),
        (JsonValue::Array(left), JsonValue::Array(right)) => {
            left.len() == right.len()
                && left.iter().zip(right).all(|(left, right)| same_json(left, right))
        }
        (JsonValue::Object(left), JsonValue::Object(right)) => {
            left.len() == right.len()
                && left.iter().all(|(key, value)| {
                    right.get(key).is_some_and(|right| same_json(value, right))
                })
        }
        _ => left == right,
    }
}

fn same_number(left: &JsonNumber, right: &JsonNumber) -> bool {
    left == right || normalized_number(left) == normalized_number(right)
}

fn normalized_number(number: &JsonNumber) -> Option<(bool, String, i64)> {
    let text = number.to_string();
    let (negative, unsigned) = text
        .strip_prefix('-')
        .map_or((false, text.as_str()), |unsigned| (true, unsigned));
    let (mantissa, exponent) =
        if let Some((mantissa, exponent)) = unsigned.split_once('e').or_else(|| unsigned.split_once('E')) {
            (mantissa, exponent.parse::<i64>().ok()?)
        } else {
            (unsigned, 0)
        };
    let (integer, fraction) = mantissa.split_once('.').unwrap_or((mantissa, ""));
    let mut digits = format!("{integer}{fraction}");
    let mut scale = exponent.checked_sub(i64::try_from(fraction.len()).ok()?)?;
    let first_nonzero = digits.find(|character| character != '0');
    let Some(first_nonzero) = first_nonzero else {
        return Some((false, "0".to_owned(), 0));
    };
    digits.drain(..first_nonzero);
    while digits.ends_with('0') {
        digits.pop();
        scale = scale.checked_add(1)?;
    }
    Some((negative, digits, scale))
}

fn schema_named(name: &str) -> &'static SchemaNode {
    schemas()
        .get(name)
        .unwrap_or_else(|| panic!("missing generated schema {name}"))
}

fn has_errors(diagnostics: &[ParseDiagnostic]) -> bool {
    diagnostics
        .iter()
        .any(|item| item.severity == DiagnosticSeverity::Error)
}

fn join_path(path: &str, key: &str) -> String {
    format!(
        "{path}/{}",
        key.replace('~', "~0").replace('/', "~1")
    )
}

fn push_error(
    diagnostics: &mut Vec<ParseDiagnostic>,
    path: &str,
    code: DiagnosticCode,
    message: impl Into<String>,
) {
    diagnostics.push(ParseDiagnostic {
        path: path.into(),
        code,
        severity: DiagnosticSeverity::Error,
        message: message.into(),
    });
}

"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{AdditionalProperties, NamedType, PublicRoot, UnionMode};

    fn sample_ir() -> Ir {
        Ir {
            schema_revision: "test-revision".into(),
            protocol_version: "1.2.3".into(),
            roots: vec![PublicRoot {
                name: "JsonRpcMessage".into(),
                schema: "message.json".into(),
            }],
            types: vec![NamedType {
                name: "JsonRpcMessage".into(),
                source: "message.json#".into(),
                shape: Shape::Object {
                    properties: vec![Property {
                        wire_name: "type".into(),
                        required: false,
                        shape: Shape::Union {
                            mode: UnionMode::OneOf,
                            variants: vec![Shape::String, Shape::Integer],
                            discriminator: None,
                        },
                    }],
                    forbidden_property_sets: Vec::new(),
                    additional: AdditionalProperties::Forbidden,
                },
            }],
        }
    }

    #[test]
    fn output_is_deterministic_typed_and_open() {
        let ir = sample_ir();
        let first = emit(&ir).unwrap();
        let second = emit(&ir).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("pub struct JsonRpcMessage"));
        assert!(first.contains("pub type_: Presence<JsonRpcMessageType>"));
        assert!(first.contains("pub enum JsonRpcMessageType"));
        let union = first
            .split("pub enum JsonRpcMessageType")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        assert!(!union.contains("Unknown(JsonValue)"));
        assert!(first.contains("Integer(Integer)"));
        assert!(first.contains("#[serde(flatten)]"));
        assert!(first.contains("pub fn parse_json_rpc_message("));
        assert!(first.contains("pub fn encode_json_rpc_message("));
        assert!(first.contains("UnknownVariant"));
    }

    #[test]
    fn recursive_refs_are_boxed_and_numeric_shapes_are_lossless() {
        let ir = Ir {
            schema_revision: "test".into(),
            protocol_version: "1".into(),
            roots: vec![],
            types: vec![
                NamedType {
                    name: "Node".into(),
                    source: "node.json#".into(),
                    shape: Shape::Object {
                        properties: vec![Property {
                            wire_name: "next".into(),
                            required: false,
                            shape: Shape::Ref {
                                name: "Node".into(),
                            },
                        }],
                        forbidden_property_sets: vec![],
                        additional: AdditionalProperties::Forbidden,
                    },
                },
                NamedType {
                    name: "ExactNumber".into(),
                    source: "number.json#".into(),
                    shape: Shape::Number,
                },
                NamedType {
                    name: "LargeLiteral".into(),
                    source: "literal.json#".into(),
                    shape: Shape::Literal {
                        value: serde_json::json!(u64::MAX),
                    },
                },
            ],
        };
        let source = emit(&ir).unwrap();
        assert!(source.contains("pub next: Presence<Box<Node>>"));
        assert!(source.contains("pub type ExactNumber = JsonNumber"));
        assert!(source.contains("pub struct LargeLiteral;"));
    }

    #[test]
    fn intersection_properties_merge_commutatively_with_any_as_identity() {
        fn object(shape: Shape, required: bool) -> Shape {
            Shape::Object {
                properties: vec![Property {
                    wire_name: "effects".into(),
                    required,
                    shape,
                }],
                forbidden_property_sets: vec![],
                additional: AdditionalProperties::Allowed,
            }
        }
        let named = BTreeMap::new();
        let typed = Shape::Array {
            items: Box::new(Shape::String),
        };
        let forward = collect_object_properties(
            &Shape::Intersection {
                variants: vec![object(Shape::Any, false), object(typed.clone(), true)],
            },
            &named,
            &mut BTreeSet::new(),
        )
        .unwrap();
        let reverse = collect_object_properties(
            &Shape::Intersection {
                variants: vec![object(typed, true), object(Shape::Any, false)],
            },
            &named,
            &mut BTreeSet::new(),
        )
        .unwrap();
        assert_eq!(
            serde_json::to_value(&forward).unwrap(),
            serde_json::to_value(&reverse).unwrap()
        );
        assert!(forward[0].required);
        assert!(matches!(forward[0].shape, Shape::Array { .. }));
    }

    #[test]
    fn discriminated_unions_alone_emit_guarded_unknown_variants() {
        let branch = |name: &str| Shape::Object {
            properties: vec![Property {
                wire_name: "type".into(),
                required: true,
                shape: Shape::Literal {
                    value: Value::String(name.into()),
                },
            }],
            forbidden_property_sets: vec![],
            additional: AdditionalProperties::Allowed,
        };
        let ir = Ir {
            schema_revision: "test".into(),
            protocol_version: "1".into(),
            roots: vec![],
            types: vec![NamedType {
                name: "Transport".into(),
                source: "transport.json#".into(),
                shape: Shape::Union {
                    mode: UnionMode::OneOf,
                    variants: vec![branch("http"), branch("stdio")],
                    discriminator: Some("type".into()),
                },
            }],
        };
        let source = emit(&ir).unwrap();
        assert!(source.contains("pub enum Transport"));
        assert!(source.contains("Unknown(JsonValue)"));
        assert!(source.contains("match actual.as_str()"));
        assert!(source.contains("\"http\" => serde_json::from_value"));
    }

    #[test]
    fn normalized_public_symbols_are_globally_collision_safe() {
        let names = [
            "FooBar",
            "foo-bar",
            "JsonValue",
            "Root",
            "root",
            "BTreeMap",
            "Deserialize",
            "String",
            "Vec",
            "Box",
            "Result",
        ];
        let ir = Ir {
            schema_revision: "test".into(),
            protocol_version: "1".into(),
            roots: vec![
                PublicRoot {
                    name: "Root".into(),
                    schema: "root.json".into(),
                },
                PublicRoot {
                    name: "root".into(),
                    schema: "root-lower.json".into(),
                },
            ],
            types: names
                .into_iter()
                .map(|name| NamedType {
                    name: name.into(),
                    source: format!("{name}.json#"),
                    shape: Shape::String,
                })
                .collect(),
        };
        let source = emit(&ir).unwrap();
        assert!(source.contains("pub type FooBar = String"));
        assert!(source.contains("pub type FooBar2 = String"));
        assert!(source.contains("pub type JsonValue2 = String"));
        assert!(source.contains("pub type BTreeMap2 = String"));
        assert!(source.contains("pub type Deserialize2 = String"));
        assert!(source.contains("pub type String2 = String"));
        assert!(source.contains("pub type Vec2 = String"));
        assert!(source.contains("pub type Box2 = String"));
        assert!(source.contains("pub type Result2 = String"));
        assert!(source.contains("pub fn parse_root_2("));
        assert!(source.contains("pub fn parse_root_3("));
    }

    #[test]
    fn identifiers_are_valid_and_collision_safe() {
        let mut used = BTreeSet::new();
        assert_eq!(snake_identifier("JSONRPCMessage"), "jsonrpc_message");
        assert_eq!(snake_identifier("request-id"), "request_id");
        assert_eq!(unique_field_identifier("type", &mut used), "type_");
        assert_eq!(unique_field_identifier("type", &mut used), "type__2");
        assert_eq!(type_identifier("3d-event"), "_3dEvent");
        let mut types = RESERVED_TYPE_NAMES
            .iter()
            .map(|name| (*name).to_owned())
            .collect::<BTreeSet<_>>();
        assert_eq!(
            unique_type_identifier("json-value", &mut types),
            "JsonValue2"
        );
        assert_eq!(unique_type_identifier("foo-bar", &mut types), "FooBar");
        assert_eq!(unique_type_identifier("foo_bar", &mut types), "FooBar2");

        let mut variants = BTreeSet::from(["Unknown".to_owned()]);
        assert_eq!(
            unique_variant_identifier(&Value::String("unknown".into()), 0, &mut variants),
            "Unknown2"
        );
        let mut union_variants = BTreeSet::from(["Unknown".to_owned()]);
        assert_eq!(
            unique_union_variant_identifier(
                &Shape::Ref {
                    name: "Unknown".into(),
                },
                0,
                &mut union_variants,
            ),
            "Unknown2"
        );
    }
}
