//! Runtime semantic constructors are separate from the lossless wire parser.
use super::*;
use std::collections::BTreeMap;

const HEADER: &str = "# Generated by ahp-codegen. DO NOT EDIT.\n";

include!("facade_tests.rs");
#[path = "grants.rs"]
mod grants;

pub fn emit(ir: &Ir) -> Result<BTreeMap<String, String>> {
    let identifiers = IdentifierMap::new(ir)?;
    let renderer = Renderer {
        ir,
        names: &identifiers.types,
    };
    let mut shapes = BTreeMap::new();
    for named in &ir.types {
        collect(&named.name, &named.shape, &mut shapes)?;
    }
    let mut body = format!(
        "{HEADER}from __future__ import annotations\nfrom typing import TYPE_CHECKING, Any\nfrom enum import StrEnum\nfrom copy import copy, deepcopy\nimport json\n\nif TYPE_CHECKING:\n    from ..content import OwnedContentSource\n\n_UNSET: Any = object()\n\n"
    );
    let mut modules: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    let mut boundaries = format!(
        "{HEADER}from __future__ import annotations\nfrom typing import TYPE_CHECKING, Any, cast\n\nif TYPE_CHECKING:\n    from ._hooks import HookResult, Hooks\n    from . import _models as models\n\nclass BoundaryMixin:\n    \"\"\"Schema-derived named boundaries; implemented by Hooks.dispatch.\"\"\"\n"
    );
    let mut content_slots_source =
        String::from("\nCONTENT_SOURCE_SLOTS: dict[str, tuple[str, tuple[str, ...]]] = {\n");
    let mut count = 0;
    for (name, shape) in &shapes {
        if let Some(fields) = properties(&renderer, shape) {
            constructor(&mut body, name, &fields, ir)?;
            let role = if name.starts_with("Effect") && name != "Effect" {
                Some(("effect", name.trim_start_matches("Effect").to_owned()))
            } else {
                crate::langs::go::facade::role(name)
            };
            if let Some((namespace, short)) = role {
                let exports = modules.entry(namespace.into()).or_default();
                export(exports, name.clone(), name.clone())?;
                if !short.is_empty() {
                    export(exports, short, name.clone())?;
                }
            }
            if name.ends_with("Event") && fields.iter().any(|p| p.wire_name == "source") {
                let short = name.trim_end_matches("Event");
                let exports = modules.entry("event".into()).or_default();
                export(exports, short.into(), name.clone())?;
                export(exports, name.clone(), name.clone())?;
                if let Some(Value::String(tag)) = fields
                    .iter()
                    .find(|p| p.wire_name == "type")
                    .and_then(|p| literal(ir, &p.shape))
                {
                    let input_name = format!("{short}Input");
                    let projection = crate::ergonomics::input_fields(ir, &fields, &tag)?;
                    let input_fields = projection
                        .iter()
                        .map(|field| field.property.clone())
                        .collect::<Vec<_>>();
                    constructor(&mut body, &input_name, &input_fields, ir)?;
                    body.push_str("    def to_wire(self) -> dict[str, Any]:\n        result = deepcopy(dict(self))\n");
                    for field in &projection {
                        if field.path != [field.property.wire_name.clone()] {
                            writeln!(body, "        if {:?} in self:", field.property.wire_name)?;
                            writeln!(
                                body,
                                "            value = result.pop({:?})",
                                field.property.wire_name
                            )?;
                            body.push_str("            target = result\n");
                            for key in &field.path[..field.path.len() - 1] {
                                writeln!(
                                    body,
                                    "            target = target.setdefault({key:?}, {{}})"
                                )?;
                            }
                            writeln!(
                                body,
                                "            target[{:?}] = value",
                                field.path.last().unwrap()
                            )?;
                        }
                    }
                    body.push_str("        return result\n\n");
                    let slots = crate::ergonomics::content_slots(ir, &projection);
                    if !slots.is_empty() {
                        body.push_str("    @property\n    def content_sources(self) -> dict[str, OwnedContentSource]:\n        return dict(getattr(self, \"_content_sources\", {}))\n\n");
                    }
                    let mut slot_names = HashSet::new();
                    for slot in slots {
                        let method = snake_case(&slot.name);
                        anyhow::ensure!(
                            slot_names.insert(method.clone()),
                            "content slot collision in {tag}: {method}"
                        );
                        let key = format!("{tag}.{method}");
                        writeln!(
                            content_slots_source,
                            "    {key:?}: ({tag:?}, ({})),",
                            slot.path
                                .iter()
                                .map(|p| format!("{p:?},"))
                                .collect::<Vec<_>>()
                                .join(" ")
                        )?;
                        write!(
                            body,
                            "    def bind_{method}_source(self, source: OwnedContentSource"
                        )?;
                        let indices = (0..slot.path.iter().filter(|p| *p == "*").count())
                            .map(|i| {
                                if i == 0 {
                                    "index".to_owned()
                                } else {
                                    format!("index_{}", i + 1)
                                }
                            })
                            .collect::<Vec<_>>();
                        if slot.many {
                            body.push_str(", *");
                        }
                        for index in &indices {
                            write!(body, ", {index}: int")?;
                        }
                        writeln!(body, ") -> {input_name}:")?;
                        for index in &indices {
                            writeln!(
                                body,
                                "        if isinstance({index}, bool) or not isinstance({index}, int) or {index} < 0:\n            raise ValueError(\"Content source index must be a nonnegative integer\")"
                            )?;
                        }
                        let suffix = indices
                            .iter()
                            .map(|index| format!("[{{{index}}}]"))
                            .collect::<Vec<_>>()
                            .join("");
                        let prefix = if indices.is_empty() { "" } else { "f" };
                        writeln!(
                            body,
                            "        result = copy(self)\n        result._content_sources = {{**self.content_sources, {prefix}\"{key}{suffix}\": source}}\n        return result\n"
                        )?;
                    }
                    export(exports, input_name.clone(), input_name.clone())?;
                    writeln!(
                        boundaries,
                        "\n    async def {}(self, input: models.{input_name} | dict[str, Any], **kwargs: Any) -> HookResult:\n        return await cast(\"Hooks\", self).dispatch({tag:?}, input, **kwargs)",
                        snake_case(short)
                    )?;
                    count += 1;
                }
            }
        } else if let Shape::Enum { values, .. } = shape {
            if values.iter().all(Value::is_string) {
                writeln!(body, "class {name}(StrEnum):")?;
                let mut seen = HashSet::new();
                for (value, label) in values.iter().zip(literal_labels(values)?) {
                    let key =
                        public_identifier(&snake_case(&label).to_uppercase(), "VALUE", &mut seen)?;
                    writeln!(
                        body,
                        "    {key} = {}",
                        python_string(value.as_str().unwrap())?
                    )?;
                }
                body.push('\n');
            }
        }
    }
    content_slots_source.push_str("}\n");
    boundaries.push_str(&content_slots_source);
    if count == 0 {
        boundaries.push_str("    pass\n");
    }
    // Stable semantic aliases use the same resolved schema names as Go/Rust.
    for (alias, model) in [
        ("Input", "ExecutionEventTool"),
        ("Tool", "ExecutionEventTool"),
        ("Call", "ToolBeforeEventCall"),
    ] {
        export(
            modules.entry("tool".into()).or_default(),
            alias.into(),
            model.into(),
        )?;
    }
    // This established capability vocabulary has an explicit canonical owner;
    // it must not disappear when another nested manifest exposes an Event field.
    export(
        modules.entry("capability".into()).or_default(),
        "Event".into(),
        "CapabilitiesResponseResultManifestEventsItemEvent".into(),
    )?;
    // Offer a short alias only when exactly one canonical model owns it.
    // Never let traversal order choose between unrelated nested field models.
    for exports in modules.values_mut() {
        let owners = exports.values().cloned().collect::<HashSet<_>>();
        let mut candidates: BTreeMap<String, HashSet<String>> = BTreeMap::new();
        for (name, shape) in &shapes {
            if properties(&renderer, shape).is_none()
                && !matches!(shape, Shape::Enum { values, .. } if values.iter().all(Value::is_string))
            {
                continue;
            }
            for owner in &owners {
                if let Some(short) = name.strip_prefix(owner) {
                    if !short.is_empty() {
                        candidates
                            .entry(short.into())
                            .or_default()
                            .insert(name.clone());
                    }
                }
            }
        }
        for (short, models) in candidates {
            if models.len() == 1 && !exports.contains_key(&short) {
                exports.insert(short, models.into_iter().next().unwrap());
            }
        }
    }
    // The schema defines path as an open string, NOT the origin enum.
    // NATIVE is the canonical path shown in spec/draft/base/events.md.
    // Never infer that other tool origins are supported paths.
    body.push_str("class Path(StrEnum):\n    NATIVE = \"native\"\n\n");
    modules
        .entry("event".into())
        .or_default()
        .insert("Path".into(), "Path".into());
    modules
        .entry("tool".into())
        .or_default()
        .insert("Path".into(), "Path".into());
    let mut public = shapes.iter().filter(|(_, shape)| properties(&renderer, shape).is_some() || matches!(shape, Shape::Enum { values, .. } if values.iter().all(Value::is_string))).map(|(name, _)| name.clone()).collect::<Vec<_>>();
    public.push("Path".into());
    public.extend(
        modules
            .get("event")
            .into_iter()
            .flat_map(|exports| exports.keys())
            .filter(|name| name.ends_with("Input"))
            .cloned(),
    );
    writeln!(body, "__all__ = {}", serde_json::to_string(&public)?)?;
    let mut files = BTreeMap::new();
    files.insert("_models/__init__.py".into(), body);
    files.insert("_boundaries.py".into(), boundaries);
    files.insert(
        "path.py".into(),
        format!("{HEADER}from ._models import Path as Path\n"),
    );
    files
        .get_mut("path.py")
        .unwrap()
        .push_str("NATIVE = Path.NATIVE\n");
    let (grant_source, grant_exports) = grants::emit(&renderer)?;
    files.insert("_grants.py".into(), grant_source);
    for namespace in [
        "event",
        "tool",
        "effect",
        "capability",
        "registration",
        "transport",
        "subscription",
        "content",
    ] {
        let exports = modules.entry(namespace.into()).or_default();
        let mut source = HEADER.to_owned();
        for (alias, name) in exports.iter() {
            writeln!(source, "from . import {name} as {alias}")?;
        }
        writeln!(
            source,
            "__all__ = {}",
            serde_json::to_string(&exports.keys().collect::<Vec<_>>())?
        )?;
        files.insert(format!("_models/{namespace}.py"), source);
        // Existing runtime modules must never be replaced by generation.
        if [
            "event",
            "tool",
            "effect",
            "capability",
            "transport",
            "subscription",
        ]
        .contains(&namespace)
        {
            let mut public = HEADER.to_owned();
            for alias in exports.keys() {
                if namespace == "capability" && grant_exports.contains(alias) {
                    continue;
                }
                writeln!(
                    public,
                    "from ._models.{namespace} import {alias} as {alias}"
                )?;
            }
            files.insert(format!("{namespace}.py"), public);
        }
    }
    for name in grant_exports {
        writeln!(
            files.get_mut("capability.py").unwrap(),
            "from ._grants import {name} as {name}"
        )?;
    }
    ergonomic_modules(&mut files, &renderer, &shapes)?;
    Ok(files)
}

fn export(exports: &mut BTreeMap<String, String>, alias: String, model: String) -> Result<()> {
    if let Some(previous) = exports.get(&alias) {
        anyhow::ensure!(
            previous == &model,
            "public Python alias collision: {alias} refers to both {previous} and {model}"
        );
    } else {
        exports.insert(alias, model);
    }
    Ok(())
}

fn literal_labels(values: &[Value]) -> Result<Vec<String>> {
    super::super::naming::try_literal_names(values)
}

fn collect(name: &str, shape: &Shape, shapes: &mut BTreeMap<String, Shape>) -> Result<()> {
    anyhow::ensure!(
        name.len() <= 100,
        "public Python model name is too long: {name}; provide a canonical schema ref"
    );
    if let Some(existing) = shapes.get(name) {
        anyhow::ensure!(
            format!("{existing:?}") == format!("{shape:?}"),
            "public Python model collision: {name}; use distinct canonical schema names"
        );
        return Ok(());
    }
    shapes.insert(name.into(), shape.clone());
    match shape {
        Shape::Object { properties, .. } => {
            collect_properties(name, properties.iter(), shapes)?;
        }
        Shape::Array { items } => collect(&format!("{name}Item"), items, shapes)?,
        Shape::Union { variants, .. } => {
            for arm in super::super::naming::projected_union(variants)? {
                let variant = &variants[arm.source_indices[0]];
                let label = &arm.name;
                // Referenced alternatives already have canonical public constructors.
                // Do not duplicate event boundaries under union-context aliases.
                if !matches!(variant, Shape::Ref { .. }) {
                    collect(&format!("{name}{label}"), variant, shapes)?;
                }
            }
        }
        Shape::Intersection { variants } => {
            collect_properties(
                name,
                variants
                    .iter()
                    .filter_map(|variant| {
                        if let Shape::Object { properties, .. } = variant {
                            Some(properties.iter())
                        } else {
                            None
                        }
                    })
                    .flatten(),
                shapes,
            )?;
        }
        _ => {}
    }
    Ok(())
}

fn collect_properties<'a>(
    name: &str,
    properties: impl Iterator<Item = &'a Property>,
    shapes: &mut BTreeMap<String, Shape>,
) -> Result<()> {
    // Resolve sibling spelling collisions before adding models to the global map.
    // Repeated intersection fields refer to the same wire property.
    let mut fields = BTreeMap::new();
    for property in properties {
        fields
            .entry(property.wire_name.as_str())
            .or_insert(property);
    }
    let values = fields
        .keys()
        .map(|name| Value::String((*name).into()))
        .collect::<Vec<_>>();
    for (property, label) in fields.values().zip(literal_labels(&values)?) {
        collect(&format!("{name}{label}"), &property.shape, shapes)?;
    }
    Ok(())
}

fn properties(renderer: &Renderer<'_>, shape: &Shape) -> Option<Vec<Property>> {
    if let Some(fields) = renderer.model_properties(shape) {
        return Some(fields);
    }
    // Conditional union constraints remain parser concerns. Preserve declared
    // fields of composite objects without making alternative fields mandatory.
    match shape {
        Shape::Intersection { variants } => {
            let mut fields: Vec<Property> = Vec::new();
            for variant in variants {
                if let Some(next) = properties(renderer, variant) {
                    for p in next {
                        if let Some(old) =
                            fields.iter_mut().find(|old| old.wire_name == p.wire_name)
                        {
                            old.required |= p.required;
                        } else {
                            fields.push(p);
                        }
                    }
                }
            }
            Some(fields)
        }
        Shape::Ref { name } => renderer
            .ir
            .types
            .iter()
            .find(|n| n.name == *name)
            .and_then(|n| properties(renderer, &n.shape)),
        _ => None,
    }
}

fn literal(ir: &Ir, shape: &Shape) -> Option<Value> {
    match shape {
        Shape::Literal { value } => Some(value.clone()),
        Shape::Ref { name } => ir
            .types
            .iter()
            .find(|n| n.name == *name)
            .and_then(|n| literal(ir, &n.shape)),
        _ => None,
    }
}

fn constructor(out: &mut String, name: &str, fields: &[Property], ir: &Ir) -> Result<()> {
    writeln!(
        out,
        "class {name}(dict[str, Any]):\n    \"\"\"Keyword-only wire object; parsing remains strict and separate.\"\"\""
    )?;
    let mut occupied = reserved_identifiers();
    occupied.insert("self".into());
    occupied.insert("extra".into());
    let params = fields
        .iter()
        .map(|p| public_identifier(&snake_case(&p.wire_name), "field", &mut occupied))
        .collect::<Result<Vec<_>>>()?;
    write!(out, "    def __init__(self, ")?;
    if !fields.is_empty() {
        write!(out, "*, ")?;
    }
    for (p, param) in fields.iter().zip(&params) {
        let default = p
            .constructor_default
            .clone()
            .or_else(|| literal(ir, &p.shape));
        let optional = !p.required || default.is_some() || p.wire_name == "protocolVersion";
        write!(
            out,
            "{param}: {}{}, ",
            annotation(ir, &p.shape),
            if optional { " = _UNSET" } else { "" }
        )?;
    }
    writeln!(
        out,
        "**extra: Any) -> None:\n        super().__init__(extra)"
    )?;
    for (p, param) in fields.iter().zip(&params) {
        let default = p
            .constructor_default
            .clone()
            .or_else(|| literal(ir, &p.shape))
            .or_else(|| {
                (p.wire_name == "protocolVersion")
                    .then(|| Value::String(ir.protocol_version.clone()))
            });
        if let Some(value) = default {
            let encoded = python_string(&serde_json::to_string(&value)?)?;
            writeln!(
                out,
                "        self[{:?}] = json.loads({encoded}) if {param} is _UNSET else {param}",
                p.wire_name
            )?;
        } else if p.required {
            writeln!(out, "        self[{:?}] = {param}", p.wire_name)?;
        } else {
            writeln!(
                out,
                "        if {param} is not _UNSET:\n            self[{:?}] = {param}",
                p.wire_name
            )?;
        }
    }
    out.push('\n');
    Ok(())
}

fn annotation(ir: &Ir, shape: &Shape) -> &'static str {
    match shape {
        Shape::String => "str",
        Shape::Boolean => "bool",
        Shape::Integer => "int",
        Shape::Number => "float",
        Shape::Null => "None",
        Shape::Array { .. } => "list[Any]",
        Shape::Object { .. } => "dict[str, Any]",
        Shape::Enum { values, .. } if values.iter().all(Value::is_string) => "str",
        Shape::Literal { value } => match value {
            Value::String(_) => "str",
            Value::Bool(_) => "bool",
            Value::Number(_) => "float",
            Value::Null => "None",
            _ => "Any",
        },
        Shape::Ref { name } => ir
            .types
            .iter()
            .find(|n| n.name == *name)
            .map(|n| match n.shape {
                Shape::Ref { .. } => "Any",
                _ => annotation(ir, &n.shape),
            })
            .unwrap_or("Any"),
        _ => "Any",
    }
}

/// Native ergonomic names retain the canonical model objects as their values.
fn ergonomic_modules(
    files: &mut BTreeMap<String, String>,
    renderer: &Renderer<'_>,
    shapes: &BTreeMap<String, Shape>,
) -> Result<()> {
    let mut diagnostics = format!("{HEADER}from enum import StrEnum\n\nclass Code(StrEnum):\n");
    for code in crate::ergonomics::DIAGNOSTIC_CODES {
        writeln!(
            diagnostics,
            "    {} = {code:?}",
            snake_case(code).to_uppercase()
        )?;
    }
    diagnostics.push_str("\nDiagnosticCode = Code\n");
    files.insert("diagnostics.py".into(), diagnostics);
    let state_name = "InterceptRequestParamsState";
    let candidate_union = &shapes[&format!("{state_name}Candidate")];
    let Shape::Union { variants, .. } = candidate_union else {
        anyhow::bail!("decision state candidate must be a union");
    };
    let candidate_name = variants
        .iter()
        .zip(super::super::naming::try_union_names(variants)?)
        .find(|(shape, _)| {
            properties(renderer, shape)
                .is_some_and(|fields| fields.iter().any(|field| field.wire_name == "value"))
        })
        .map(|(shape, label)| match shape {
            Shape::Ref { name } => name.clone(),
            _ => format!("{state_name}Candidate{label}"),
        })
        .ok_or_else(|| anyhow::anyhow!("decision state candidate has no value object"))?;
    let mut state = format!(
        "{HEADER}from __future__ import annotations\nfrom typing import Any\nfrom ._models import {state_name} as State\nfrom ._models import {state_name}Permission as Permission\nfrom ._models import {state_name}Flow as Flow\nfrom ._models import {candidate_name} as Candidate\nfrom ._models import {candidate_name}Provenance as Provenance\n\n_UNSET: Any = object()\n\ndef initial(permission: Permission, *, candidate: Candidate | None = None"
    );
    let fields = properties(renderer, &shapes[state_name]).expect("decision state object");
    for field in &fields {
        if !["permission", "candidate"].contains(&field.wire_name.as_str()) {
            write!(
                state,
                ", {}: {} = _UNSET",
                snake_case(&field.wire_name),
                if field.wire_name == "flow" {
                    "Flow"
                } else {
                    annotation(renderer.ir, &field.shape)
                }
            )?;
        }
    }
    state.push_str(") -> State:\n    \"\"\"Explicit native-hook starting permission, not execution authorization.\"\"\"\n    result = State(permission=Permission(permission), candidate=candidate)\n");
    for field in &fields {
        if !["permission", "candidate"].contains(&field.wire_name.as_str()) {
            let param = snake_case(&field.wire_name);
            writeln!(
                state,
                "    if {param} is not _UNSET:\n        result[{:?}] = {param}",
                field.wire_name
            )?;
        }
    }
    state.push_str("    return result\n\n__all__ = [\"State\", \"Permission\", \"Candidate\", \"Provenance\", \"Flow\", \"initial\"]\n");
    files.insert("state.py".into(), state);
    files.insert(
        "permission.py".into(),
        format!("{HEADER}from .state import Permission as Permission\n"),
    );
    files.insert("candidate.py".into(), format!("{HEADER}from __future__ import annotations\nfrom typing import Any\nfrom .state import Candidate as Candidate, Provenance as Provenance\n\ndef value(value: Any, *, provenance: Provenance | None = None) -> Candidate:\n    if provenance is None:\n        return Candidate(value=value)\n    return Candidate(value=value, provenance=provenance)\n"));

    let effect = files.get_mut("effect.py").unwrap();
    let mut effect_names = reserved_identifiers();
    effect.push_str("\nfrom typing import Any\nfrom ._models import _UNSET\n\n");
    // Match operation helpers to the exact same target grants as declarations.
    let capabilities = renderer
        .ir
        .types
        .iter()
        .find(|n| n.name == "Capabilities")
        .unwrap();
    let dimensions = properties(renderer, &capabilities.shape).unwrap();
    let modify = dimensions
        .iter()
        .find(|field| field.wire_name == "modify")
        .unwrap();
    for target in properties(renderer, &modify.shape).unwrap() {
        for operation in properties(renderer, &target.shape).unwrap_or_default() {
            if !matches!(
                operation.shape,
                Shape::Boolean
                    | Shape::Literal {
                        value: Value::Bool(_)
                    }
            ) {
                continue;
            }
            let name = format!(
                "{}_{}",
                snake_case(&operation.wire_name),
                snake_case(&target.wire_name)
            );
            let name = public_identifier(&name, "effect", &mut effect_names)?;
            writeln!(
                effect,
                "def {name}(value: Any) -> Modify:\n    return Modify(target={:?}, operation={:?}, value=value)\n",
                target.wire_name, operation.wire_name
            )?;
        }
    }
    for (name, shape) in shapes {
        if name.starts_with("Effect") && name != "EffectModify" {
            if let Some(fields) = properties(renderer, shape) {
                if fields
                    .iter()
                    .any(|p| p.wire_name == "type" && literal(renderer.ir, &p.shape).is_some())
                {
                    let short = name.trim_start_matches("Effect");
                    let alias = public_identifier(&snake_case(short), "effect", &mut effect_names)?;
                    let params = fields
                        .iter()
                        .filter(|p| literal(renderer.ir, &p.shape).is_none())
                        .collect::<Vec<_>>();
                    let mut occupied = reserved_identifiers();
                    let param_names = params
                        .iter()
                        .map(|p| {
                            public_identifier(&snake_case(&p.wire_name), "field", &mut occupied)
                        })
                        .collect::<Result<Vec<_>>>()?;
                    write!(effect, "def {alias}(")?;
                    if !params.is_empty() {
                        effect.push_str("*, ");
                    }
                    for (p, param) in params.iter().zip(&param_names) {
                        write!(
                            effect,
                            "{}: {}{}, ",
                            param,
                            annotation(renderer.ir, &p.shape),
                            if p.required { "" } else { " = _UNSET" }
                        )?;
                    }
                    writeln!(
                        effect,
                        ") -> {short}:\n    return {short}({})\n",
                        param_names
                            .iter()
                            .map(|name| format!("{name}={name}"))
                            .collect::<Vec<_>>()
                            .join(", ")
                    )?;
                    let semantic = ["type", "target", "operation"]
                        .iter()
                        .filter_map(|key| {
                            fields
                                .iter()
                                .find(|p| p.wire_name == *key)
                                .and_then(|p| literal(renderer.ir, &p.shape))
                                .and_then(|v| v.as_str().map(str::to_owned))
                        })
                        .collect::<Vec<_>>()
                        .join("_");
                    let semantic =
                        public_identifier(&semantic, "effect", &mut reserved_identifiers())?;
                    if semantic != alias {
                        anyhow::ensure!(
                            effect_names.insert(semantic.clone()),
                            "public Python effect alias collision: {semantic}"
                        );
                        writeln!(effect, "{semantic} = {alias}")?;
                    }
                }
            }
        }
    }
    // Deny is a separately named canonical model, not an Effect-prefixed model.
    anyhow::ensure!(
        effect_names.insert("deny".into()),
        "public Python effect alias collision: deny"
    );
    effect.push_str("deny = Deny\n");
    Ok(())
}
