//! Runtime semantic constructors are separate from the lossless wire parser.
use super::*;
use std::collections::BTreeMap;

const HEADER: &str = "# Generated by ahp-codegen. DO NOT EDIT.\n";

include!("facade_tests.rs");
#[path = "grants.rs"]
mod grants;

pub fn emit(ir: &Ir) -> Result<BTreeMap<String, String>> {
    let identifiers = IdentifierMap::new(ir);
    let renderer = Renderer {
        ir,
        names: &identifiers.types,
    };
    let mut shapes = BTreeMap::new();
    for named in &ir.types {
        collect(&named.name, &named.shape, &mut shapes);
    }
    let mut body = format!(
        "{HEADER}from __future__ import annotations\nfrom typing import Any\nfrom enum import StrEnum\nimport json\n\n_UNSET: Any = object()\n\n"
    );
    let mut modules: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    let mut boundaries = format!(
        "{HEADER}from __future__ import annotations\nfrom typing import TYPE_CHECKING, Any, cast\n\nif TYPE_CHECKING:\n    from ._hooks import HookResult, Hooks\n    from . import _models as models\n\nclass BoundaryMixin:\n    \"\"\"Schema-derived named boundaries; implemented by Hooks.dispatch.\"\"\"\n"
    );
    let mut count = 0;
    for (name, shape) in &shapes {
        if let Some(fields) = properties(&renderer, shape) {
            constructor(&mut body, name, &fields, ir)?;
            let role = if name.starts_with("Effect") && name != "Effect" {
                Some(("effect", name.trim_start_matches("Effect").to_owned()))
            } else {
                crate::langs::go::facade::role(name)
            };
            if let Some((namespace, short)) = role {
                let exports = modules.entry(namespace.into()).or_default();
                exports.insert(name.clone(), name.clone());
                if !short.is_empty() {
                    exports.insert(short, name.clone());
                }
            }
            if name.ends_with("Event") && fields.iter().any(|p| p.wire_name == "source") {
                let short = name.trim_end_matches("Event");
                let exports = modules.entry("event".into()).or_default();
                exports.insert(short.into(), name.clone());
                exports.insert(name.clone(), name.clone());
                if let Some(Value::String(tag)) = fields
                    .iter()
                    .find(|p| p.wire_name == "type")
                    .and_then(|p| literal(ir, &p.shape))
                {
                    let input_name = format!("{short}Input");
                    let input_fields = fields
                        .iter()
                        .filter(|p| {
                            !["id", "type", "time", "source", "protocolVersion"]
                                .contains(&p.wire_name.as_str())
                        })
                        .cloned()
                        .collect::<Vec<_>>();
                    constructor(&mut body, &input_name, &input_fields, ir)?;
                    exports.insert(input_name.clone(), input_name.clone());
                    writeln!(
                        boundaries,
                        "\n    async def {}(self, input: models.{input_name} | dict[str, Any], **kwargs: Any) -> HookResult:\n        return await cast(\"Hooks\", self).dispatch({tag:?}, input, **kwargs)",
                        snake_case(short)
                    )?;
                    count += 1;
                }
            }
        } else if let Shape::Enum { values, .. } = shape {
            if values.iter().all(Value::is_string) {
                writeln!(body, "class {name}(StrEnum):")?;
                let mut seen = HashSet::new();
                for value in values {
                    let key = allocate_identifier(
                        &snake_case(value.as_str().unwrap())
                            .replace(['.', '-'], "_")
                            .to_uppercase(),
                        "VALUE",
                        &mut seen,
                    );
                    writeln!(
                        body,
                        "    {key} = {}",
                        python_string(value.as_str().unwrap())?
                    )?;
                }
                body.push('\n');
            }
        }
    }
    if count == 0 {
        boundaries.push_str("    pass\n");
    }
    // Stable semantic aliases use the same resolved schema names as Go/Rust.
    for (alias, model) in [
        ("Input", "ExecutionEventTool"),
        ("Tool", "ExecutionEventTool"),
        ("Call", "ToolBeforeEventCall"),
    ] {
        modules
            .entry("tool".into())
            .or_default()
            .insert(alias.into(), model.into());
    }
    // Enum fields retain their complete context name, with unambiguous short
    // aliases exposed in their owning namespace.
    for (name, shape) in &shapes {
        if properties(&renderer, shape).is_none()
            && !matches!(shape, Shape::Enum { values, .. } if values.iter().all(Value::is_string))
        {
            continue;
        }
        for exports in modules.values_mut() {
            let owners = exports.values().cloned().collect::<Vec<_>>();
            for owner in owners {
                if let Some(short) = name.strip_prefix(&owner) {
                    if !short.is_empty() {
                        exports.entry(short.into()).or_insert(name.clone());
                    }
                }
            }
        }
    }
    // The schema defines path as an open string, NOT the origin enum.
    // NATIVE is the canonical path shown in spec/draft/base/events.md.
    // Never infer that other tool origins are supported paths.
    body.push_str("class Path(StrEnum):\n    NATIVE = \"native\"\n\n");
    modules
        .entry("event".into())
        .or_default()
        .insert("Path".into(), "Path".into());
    modules
        .entry("tool".into())
        .or_default()
        .insert("Path".into(), "Path".into());
    let mut public = shapes.iter().filter(|(_, shape)| properties(&renderer, shape).is_some() || matches!(shape, Shape::Enum { values, .. } if values.iter().all(Value::is_string))).map(|(name, _)| name.clone()).collect::<Vec<_>>();
    public.push("Path".into());
    public.extend(
        modules
            .get("event")
            .into_iter()
            .flat_map(|exports| exports.keys())
            .filter(|name| name.ends_with("Input"))
            .cloned(),
    );
    writeln!(body, "__all__ = {}", serde_json::to_string(&public)?)?;
    let mut files = BTreeMap::new();
    files.insert("_models/__init__.py".into(), body);
    files.insert("_boundaries.py".into(), boundaries);
    files.insert(
        "path.py".into(),
        format!("{HEADER}from ._models import Path as Path\n"),
    );
    files
        .get_mut("path.py")
        .unwrap()
        .push_str("NATIVE = Path.NATIVE\n");
    let (grant_source, grant_exports) = grants::emit(&renderer)?;
    files.insert("_grants.py".into(), grant_source);
    for namespace in [
        "event",
        "tool",
        "effect",
        "capability",
        "registration",
        "transport",
        "subscription",
        "content",
    ] {
        let exports = modules.entry(namespace.into()).or_default();
        let mut source = HEADER.to_owned();
        for (alias, name) in exports.iter() {
            writeln!(source, "from . import {name} as {alias}")?;
        }
        writeln!(
            source,
            "__all__ = {}",
            serde_json::to_string(&exports.keys().collect::<Vec<_>>())?
        )?;
        files.insert(format!("_models/{namespace}.py"), source);
        // Existing runtime modules must never be replaced by generation.
        if [
            "event",
            "tool",
            "effect",
            "capability",
            "transport",
            "subscription",
        ]
        .contains(&namespace)
        {
            let mut public = HEADER.to_owned();
            for alias in exports.keys() {
                if namespace == "capability" && grant_exports.contains(alias) {
                    continue;
                }
                writeln!(
                    public,
                    "from ._models.{namespace} import {alias} as {alias}"
                )?;
            }
            files.insert(format!("{namespace}.py"), public);
        }
    }
    for name in grant_exports {
        writeln!(
            files.get_mut("capability.py").unwrap(),
            "from ._grants import {name} as {name}"
        )?;
    }
    Ok(files)
}

fn collect(name: &str, shape: &Shape, shapes: &mut BTreeMap<String, Shape>) {
    shapes.entry(name.into()).or_insert_with(|| shape.clone());
    match shape {
        Shape::Object { properties, .. } => {
            for p in properties {
                collect(
                    &format!("{name}{}", pascal_fragment(&p.wire_name)),
                    &p.shape,
                    shapes,
                );
            }
        }
        Shape::Array { items } => collect(&format!("{name}Item"), items, shapes),
        Shape::Union { variants, .. } => {
            for (index, variant) in variants.iter().enumerate() {
                let tag = if let Shape::Object { properties, .. } = variant {
                    let mut label = String::new();
                    for key in ["type", "operation"] {
                        if let Some(Property {
                            shape:
                                Shape::Literal {
                                    value: Value::String(value),
                                },
                            ..
                        }) = properties.iter().find(|p| p.wire_name == key)
                        {
                            label.push_str(&pascal_fragment(value));
                        }
                    }
                    label
                } else {
                    String::new()
                };
                collect(
                    &format!(
                        "{name}{}",
                        if tag.is_empty() {
                            format!("Variant{}", index + 1)
                        } else {
                            tag
                        }
                    ),
                    variant,
                    shapes,
                );
            }
        }
        Shape::Intersection { variants } => {
            for variant in variants {
                if let Shape::Object { properties, .. } = variant {
                    for p in properties {
                        collect(
                            &format!("{name}{}", pascal_fragment(&p.wire_name)),
                            &p.shape,
                            shapes,
                        );
                    }
                }
            }
        }
        _ => {}
    }
}

fn properties(renderer: &Renderer<'_>, shape: &Shape) -> Option<Vec<Property>> {
    if let Some(fields) = renderer.model_properties(shape) {
        return Some(fields);
    }
    // Conditional union constraints remain parser concerns. Preserve declared
    // fields of composite objects without making alternative fields mandatory.
    match shape {
        Shape::Intersection { variants } => {
            let mut fields: Vec<Property> = Vec::new();
            for variant in variants {
                if let Some(next) = properties(renderer, variant) {
                    for p in next {
                        if let Some(old) =
                            fields.iter_mut().find(|old| old.wire_name == p.wire_name)
                        {
                            old.required |= p.required;
                        } else {
                            fields.push(p);
                        }
                    }
                }
            }
            Some(fields)
        }
        Shape::Ref { name } => renderer
            .ir
            .types
            .iter()
            .find(|n| n.name == *name)
            .and_then(|n| properties(renderer, &n.shape)),
        _ => None,
    }
}

fn literal(ir: &Ir, shape: &Shape) -> Option<Value> {
    match shape {
        Shape::Literal { value } => Some(value.clone()),
        Shape::Ref { name } => ir
            .types
            .iter()
            .find(|n| n.name == *name)
            .and_then(|n| literal(ir, &n.shape)),
        _ => None,
    }
}

fn constructor(out: &mut String, name: &str, fields: &[Property], ir: &Ir) -> Result<()> {
    writeln!(
        out,
        "class {name}(dict[str, Any]):\n    \"\"\"Keyword-only wire object; parsing remains strict and separate.\"\"\""
    )?;
    let mut occupied = reserved_identifiers();
    occupied.insert("self".into());
    occupied.insert("extra".into());
    let params = fields
        .iter()
        .map(|p| allocate_identifier(&snake_case(&p.wire_name), "field", &mut occupied))
        .collect::<Vec<_>>();
    write!(out, "    def __init__(self, ")?;
    if !fields.is_empty() {
        write!(out, "*, ")?;
    }
    for (p, param) in fields.iter().zip(&params) {
        let default = p
            .constructor_default
            .clone()
            .or_else(|| literal(ir, &p.shape));
        let optional = !p.required || default.is_some() || p.wire_name == "protocolVersion";
        write!(
            out,
            "{param}: {}{}, ",
            annotation(ir, &p.shape),
            if optional { " = _UNSET" } else { "" }
        )?;
    }
    writeln!(
        out,
        "**extra: Any) -> None:\n        super().__init__(extra)"
    )?;
    for (p, param) in fields.iter().zip(&params) {
        let default = p
            .constructor_default
            .clone()
            .or_else(|| literal(ir, &p.shape))
            .or_else(|| {
                (p.wire_name == "protocolVersion")
                    .then(|| Value::String(ir.protocol_version.clone()))
            });
        if let Some(value) = default {
            let encoded = python_string(&serde_json::to_string(&value)?)?;
            writeln!(
                out,
                "        self[{:?}] = json.loads({encoded}) if {param} is _UNSET else {param}",
                p.wire_name
            )?;
        } else if p.required {
            writeln!(out, "        self[{:?}] = {param}", p.wire_name)?;
        } else {
            writeln!(
                out,
                "        if {param} is not _UNSET:\n            self[{:?}] = {param}",
                p.wire_name
            )?;
        }
    }
    out.push('\n');
    Ok(())
}

fn annotation(ir: &Ir, shape: &Shape) -> &'static str {
    match shape {
        Shape::String => "str",
        Shape::Boolean => "bool",
        Shape::Integer => "int",
        Shape::Number => "float",
        Shape::Null => "None",
        Shape::Array { .. } => "list[Any]",
        Shape::Object { .. } => "dict[str, Any]",
        Shape::Enum { values, .. } if values.iter().all(Value::is_string) => "str",
        Shape::Literal { value } => match value {
            Value::String(_) => "str",
            Value::Bool(_) => "bool",
            Value::Number(_) => "float",
            Value::Null => "None",
            _ => "Any",
        },
        Shape::Ref { name } => ir
            .types
            .iter()
            .find(|n| n.name == *name)
            .map(|n| match n.shape {
                Shape::Ref { .. } => "Any",
                _ => annotation(ir, &n.shape),
            })
            .unwrap_or("Any"),
        _ => "Any",
    }
}
