use std::fmt::Write;

use anyhow::Result;
use serde_json::json;

use crate::model::{AdditionalProperties, Ir, Shape};

pub fn emit(ir: &Ir) -> Result<String> {
    let mut output = String::new();
    writeln!(output, "// Generated by ahp-codegen. DO NOT EDIT.")?;
    writeln!(
        output,
        "// Non-normative derivative of AHP schema {}.",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "// Canonical validity requires the original Draft 2020-12 schemas.\n"
    )?;
    writeln!(
        output,
        "export const SCHEMA_REVISION = {:?} as const;",
        ir.schema_revision
    )?;
    writeln!(
        output,
        "export const PROTOCOL_VERSION = {:?} as const;\n",
        ir.protocol_version
    )?;
    output.push_str(PRELUDE);

    for named in &ir.types {
        writeln!(output, "/** Source: {} */", named.source)?;
        writeln!(
            output,
            "export type {} = {};\n",
            named.name,
            render(&named.shape, 0)?
        )?;
    }

    let descriptors = ir
        .types
        .iter()
        .map(|named| {
            (
                named.name.clone(),
                serde_json::to_value(&named.shape).expect("shape serializes"),
            )
        })
        .collect::<serde_json::Map<_, _>>();
    writeln!(
        output,
        "const SCHEMAS: Record<string, SchemaNode> = {} as unknown as Record<string, SchemaNode>;",
        serde_json::to_string_pretty(&descriptors)?
    )?;
    writeln!(
        output,
        "const ROOTS = {} as const;\n",
        serde_json::to_string_pretty(&json!(ir.roots))?
    )?;
    output.push_str(RUNTIME);

    for root in &ir.roots {
        let function = lower_camel(&root.name);
        writeln!(
            output,
            "export function parse{}(input: string | unknown): ParseResult<{}> {{ return parseRoot({:?}, input) as ParseResult<{}>; }}",
            root.name, root.name, root.name, root.name
        )?;
        writeln!(
            output,
            "export function encode{}(value: {}): string {{ return encodeJson(value as JsonValue); }}",
            root.name, root.name
        )?;
        writeln!(
            output,
            "export const {}SchemaRevision = SCHEMA_REVISION;\n",
            function
        )?;
    }
    Ok(output)
}

fn render(shape: &Shape, depth: usize) -> Result<String> {
    Ok(match shape {
        Shape::Any => "JsonValue".into(),
        Shape::Never => "never".into(),
        Shape::Null => "null".into(),
        Shape::Boolean => "boolean".into(),
        Shape::Integer | Shape::Number => "number".into(),
        Shape::String => "string".into(),
        Shape::Literal { value } => serde_json::to_string(value)?,
        Shape::Enum {
            values,
            open_strings,
        } => {
            let variants = values
                .iter()
                .map(serde_json::to_string)
                .collect::<std::result::Result<Vec<_>, _>>()?
                .join(" | ");
            if *open_strings {
                format!("OpenString<{variants}>")
            } else {
                variants
            }
        }
        Shape::Array { items } => format!("Array<{}>", render(items, depth)?),
        Shape::Ref { name } => name.clone(),
        Shape::Intersection { variants } => variants
            .iter()
            .map(|variant| render(variant, depth))
            .collect::<Result<Vec<_>>>()?
            .join(" & "),
        Shape::Union {
            variants,
            discriminator,
            ..
        } => {
            let mut rendered = variants
                .iter()
                .map(|variant| render(variant, depth))
                .collect::<Result<Vec<_>>>()?;
            if let Some(property) = discriminator {
                rendered.push(format!("UnknownVariant<{:?}>", property));
            }
            rendered.join(" | ")
        }
        Shape::Object {
            properties,
            additional,
            ..
        } => {
            let indent = "  ".repeat(depth);
            let child_indent = "  ".repeat(depth + 1);
            let mut value = String::from("{\n");
            for property in properties {
                writeln!(
                    value,
                    "{child_indent}{}{}: {};",
                    serde_json::to_string(&property.wire_name)?,
                    if property.required { "" } else { "?" },
                    render(&property.shape, depth + 1)?
                )?;
            }
            write!(value, "{indent}}}")?;
            match additional {
                AdditionalProperties::Allowed | AdditionalProperties::Forbidden => {
                    // Even canonically closed objects retain unknown input for lossless parsing.
                    value.push_str(" & AdditionalProperties");
                }
            }
            value
        }
    })
}

fn lower_camel(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

const PRELUDE: &str = r#"export type JsonPrimitive = null | boolean | number | string;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type AdditionalProperties = { [key: string]: JsonValue };
export type OpenString<Known extends string> = Known | (string & {});
export type UnknownVariant<Discriminator extends string> = AdditionalProperties & { [Key in Discriminator]: string };

export interface ParseDiagnostic {
  readonly path: string;
  readonly code: "invalid_type" | "missing_required" | "literal_mismatch" | "unknown_enum" | "unknown_variant" | "invalid_known_variant" | "no_union_match" | "ambiguous_union" | "unsupported_protocol_version" | "invalid_json";
  readonly severity: "error" | "warning";
  readonly message: string;
}

export type ParseResult<T> =
  | { readonly ok: true; readonly value: T; readonly raw: JsonValue; readonly diagnostics: readonly ParseDiagnostic[] }
  | { readonly ok: false; readonly raw?: JsonValue; readonly diagnostics: readonly ParseDiagnostic[] };

type SchemaNode =
  | { kind: "any" | "never" | "null" | "boolean" | "integer" | "number" | "string" }
  | { kind: "literal"; value: JsonValue }
  | { kind: "enum"; values: JsonValue[]; open_strings: boolean }
  | { kind: "array"; items: SchemaNode }
  | { kind: "object"; properties: Array<{ wire_name: string; required: boolean; shape: SchemaNode }>; forbidden_property_sets: string[][]; additional: unknown }
  | { kind: "union"; mode: "anyOf" | "oneOf"; variants: SchemaNode[]; discriminator?: string }
  | { kind: "intersection"; variants: SchemaNode[] }
  | { kind: "ref"; name: string };

"#;

const RUNTIME: &str = r#"function parseRoot(name: string, input: string | unknown): ParseResult<unknown> {
  let raw: JsonValue;
  try {
    raw = toSafeJson(typeof input === "string" ? JSON.parse(input) : input);
  } catch (error) {
    return { ok: false, diagnostics: [{ path: "", code: "invalid_json", severity: "error", message: error instanceof Error ? error.message : "Invalid JSON" }] };
  }
  const diagnostics: ParseDiagnostic[] = [];
  checkNode(SCHEMAS[name], raw, "", diagnostics);
  const root = ROOTS.find((candidate) => candidate.name === name);
  if (root && "protocolVersionPointer" in root && root.protocolVersionPointer) {
    const version = readPointer(raw, root.protocolVersionPointer);
    if (version !== PROTOCOL_VERSION) {
      diagnostics.push({ path: root.protocolVersionPointer, code: "unsupported_protocol_version", severity: "error", message: `Expected protocolVersion ${PROTOCOL_VERSION}` });
    }
  }
  if (diagnostics.some((diagnostic) => diagnostic.severity === "error")) return { ok: false, raw, diagnostics };
  return { ok: true, value: raw, raw, diagnostics };
}

function checkNode(schema: SchemaNode, value: JsonValue, path: string, diagnostics: ParseDiagnostic[]): void {
  switch (schema.kind) {
    case "any": return;
    case "never": return error(diagnostics, path, "invalid_type", "Value is forbidden");
    case "null": if (value !== null) error(diagnostics, path, "invalid_type", "Expected null"); return;
    case "boolean": if (typeof value !== "boolean") error(diagnostics, path, "invalid_type", "Expected boolean"); return;
    case "integer": if (typeof value !== "number" || !Number.isSafeInteger(value)) error(diagnostics, path, "invalid_type", "Expected safely representable integer"); return;
    case "number": if (typeof value !== "number" || !Number.isFinite(value)) error(diagnostics, path, "invalid_type", "Expected finite number"); return;
    case "string": if (typeof value !== "string") error(diagnostics, path, "invalid_type", "Expected string"); return;
    case "literal": if (!sameJson(value, schema.value)) error(diagnostics, path, "literal_mismatch", `Expected ${JSON.stringify(schema.value)}`); return;
    case "enum": {
      if (schema.values.some((candidate) => sameJson(candidate, value))) return;
      if (schema.open_strings && typeof value === "string") {
        diagnostics.push({ path, code: "unknown_enum", severity: "warning", message: `Unknown enum value ${JSON.stringify(value)} was preserved` });
      } else error(diagnostics, path, "invalid_type", "Value does not match the enum's scalar type");
      return;
    }
    case "array":
      if (!Array.isArray(value)) return error(diagnostics, path, "invalid_type", "Expected array");
      value.forEach((item, index) => checkNode(schema.items, item, `${path}/${index}`, diagnostics));
      return;
    case "object":
      if (!isObject(value)) return error(diagnostics, path, "invalid_type", "Expected object");
      for (const forbiddenSet of schema.forbidden_property_sets) {
        if (forbiddenSet.every((key) => Object.prototype.hasOwnProperty.call(value, key))) {
          error(diagnostics, path, "invalid_type", `Forbidden property combination: ${forbiddenSet.join(", ")}`);
        }
      }
      for (const property of schema.properties) {
        if (!Object.prototype.hasOwnProperty.call(value, property.wire_name)) {
          if (property.required) error(diagnostics, joinPath(path, property.wire_name), "missing_required", "Required property is absent");
        } else checkNode(property.shape, value[property.wire_name], joinPath(path, property.wire_name), diagnostics);
      }
      return;
    case "intersection": schema.variants.forEach((variant) => checkNode(variant, value, path, diagnostics)); return;
    case "ref": checkNode(SCHEMAS[schema.name], value, path, diagnostics); return;
    case "union": checkUnion(schema, value, path, diagnostics); return;
  }
}

function checkUnion(schema: Extract<SchemaNode, { kind: "union" }>, value: JsonValue, path: string, diagnostics: ParseDiagnostic[]): void {
  if (schema.discriminator) {
    if (!isObject(value) || typeof value[schema.discriminator] !== "string") return error(diagnostics, joinPath(path, schema.discriminator), "invalid_type", "Expected string discriminator");
    const actual = value[schema.discriminator] as string;
    const branch = schema.variants.find((variant) => discriminatorValue(variant, schema.discriminator as string) === actual);
    if (!branch) {
      diagnostics.push({ path, code: "unknown_variant", severity: "warning", message: `Unknown ${schema.discriminator} variant ${JSON.stringify(actual)} was preserved` });
      return;
    }
    const branchDiagnostics: ParseDiagnostic[] = [];
    checkNode(branch, value, path, branchDiagnostics);
    if (branchDiagnostics.some((item) => item.severity === "error")) {
      diagnostics.push(...branchDiagnostics, { path, code: "invalid_known_variant", severity: "error", message: `Known ${schema.discriminator} variant is malformed` });
    } else diagnostics.push(...branchDiagnostics);
    return;
  }
  const attempts = schema.variants.map((variant) => { const result: ParseDiagnostic[] = []; checkNode(variant, value, path, result); return result; });
  const matches = attempts.filter((attempt) => !attempt.some((item) => item.severity === "error"));
  if (matches.length === 0) error(diagnostics, path, "no_union_match", "Value matches no union branch");
  else if (schema.mode === "oneOf" && matches.length > 1) error(diagnostics, path, "ambiguous_union", "Value matches more than one union branch");
  else diagnostics.push(...matches[0]);
}

function discriminatorValue(schema: SchemaNode, property: string): string | undefined {
  if (schema.kind === "ref") return discriminatorValue(SCHEMAS[schema.name], property);
  if (schema.kind === "intersection") {
    for (const variant of schema.variants) { const value = discriminatorValue(variant, property); if (value !== undefined) return value; }
  }
  if (schema.kind === "object") {
    const field = schema.properties.find((candidate) => candidate.wire_name === property);
    if (field?.shape.kind === "literal" && typeof field.shape.value === "string") return field.shape.value;
  }
  return undefined;
}

function toSafeJson(value: unknown): JsonValue {
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (Array.isArray(value)) return value.map(toSafeJson);
  if (typeof value === "object") {
    const result = Object.create(null) as Record<string, JsonValue>;
    for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
      Object.defineProperty(result, key, { value: toSafeJson(child), enumerable: true, configurable: true, writable: true });
    }
    return result;
  }
  throw new TypeError("Input is not a JSON value");
}

function encodeJson(value: JsonValue): string { return JSON.stringify(value); }
function isObject(value: JsonValue): value is Record<string, JsonValue> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function sameJson(left: JsonValue, right: JsonValue): boolean { return JSON.stringify(left) === JSON.stringify(right); }
function joinPath(path: string, key: string): string { return `${path}/${key.replace(/~/g, "~0").replace(/\//g, "~1")}`; }
function error(diagnostics: ParseDiagnostic[], path: string, code: ParseDiagnostic["code"], message: string): void { diagnostics.push({ path, code, severity: "error", message }); }
function readPointer(value: JsonValue, pointer: string): JsonValue | undefined {
  let current: JsonValue | undefined = value;
  for (const token of pointer.split("/").slice(1)) {
    if (!isObject(current as JsonValue)) return undefined;
    current = (current as Record<string, JsonValue>)[token.replace(/~1/g, "/").replace(/~0/g, "~")];
  }
  return current;
}

"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Ir, NamedType, PublicRoot, Shape};

    #[test]
    fn output_is_deterministic_and_open() {
        let ir = Ir {
            schema_revision: "test".into(),
            protocol_version: "1".into(),
            roots: vec![PublicRoot {
                name: "Message".into(),
                schema: "message.json".into(),
                method: None,
                protocol_version_pointer: None,
                response_context_required: false,
            }],
            types: vec![NamedType {
                name: "Message".into(),
                source: "message.json#".into(),
                shape: Shape::String,
            }],
        };
        let first = emit(&ir).unwrap();
        let second = emit(&ir).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("OpenString"));
        assert!(first.contains("UnknownVariant"));
        assert!(first.contains("parseMessage"));
    }
}
