#!/usr/bin/env python3
"""Verify offline or explicitly refresh the pinned MCP elicitation extraction."""
import argparse
import hashlib
import json
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
PIN = ROOT / 'upstream/mcp/2025-11-25'
BASE = 'https://raw.githubusercontent.com/modelcontextprotocol/modelcontextprotocol/2025-11-25/schema/2025-11-25/'
TARGET = ROOT / 'schema/draft/mcp-elicitation.schema.json'

def digest(data):
    return hashlib.sha256(data).hexdigest()

def extract(source):
    definitions = source['$defs']
    selected = {}
    def visit(name):
        if name in selected:
            return
        selected[name] = definitions[name]
        def walk(value):
            if isinstance(value, dict):
                if '$ref' in value:
                    visit(value['$ref'].split('/')[-1])
                for child in value.values():
                    walk(child)
            elif isinstance(value, list):
                for child in value:
                    walk(child)
        walk(selected[name])
    for name in ['ElicitRequestParams', 'ElicitResult']:
        visit(name)
    # Published JSON Schema leaves all objects open. Close the requested-schema
    # vocabulary only: otherwise StringSchema silently accepts arbitrary nested
    # schemas/keywords through the primitive union. Keep MCP _meta/extensions.
    def close(value):
        if isinstance(value, dict):
            if value.get('type') == 'object' and 'additionalProperties' not in value:
                value['additionalProperties'] = False
            for child in value.values():
                close(child)
        elif isinstance(value, list):
            for child in value:
                close(child)
    for name, value in selected.items():
        if name.endswith('Schema') or name == 'PrimitiveSchemaDefinition':
            close(value)
    close(selected['ElicitRequestFormParams']['properties']['requestedSchema'])
    # The published JSON generator narrows TypeScript `number` to integer.
    # Restore the authoritative TS numeric fields/results, not user schema tags.
    for name, fields in {'NumberSchema': ['minimum', 'maximum', 'default'], 'StringSchema': ['minLength', 'maxLength'], 'UntitledMultiSelectEnumSchema': ['minItems', 'maxItems'], 'TitledMultiSelectEnumSchema': ['minItems', 'maxItems'], 'TaskMetadata': ['ttl']}.items():
        for field in fields:
            selected[name]['properties'][field]['type'] = 'number'
    selected['ProgressToken']['type'] = ['string', 'number']
    values = selected['ElicitResult']['properties']['content']['additionalProperties']['anyOf'][1]['type']
    values[values.index('integer')] = 'number'
    selected['request'] = {'$ref': '#/$defs/ElicitRequestParams'}
    selected['result'] = {'$ref': '#/$defs/ElicitResult'}
    return {'$schema': 'https://json-schema.org/draft/2020-12/schema', '$id': 'https://agenthooksprotocol.org/schemas/draft/mcp-elicitation.schema.json', 'title': 'Pinned MCP 2025-11-25 elicitation payloads (Draft)', '$comment': 'Mutable AHP draft. Generated by tools/mcp_elicitation.py. Complete referenced JSON params/result, not inline AHP fields. Requested-schema vocabulary is closed to the published subset; TypeScript number fields restore precision lost by upstream JSON generation.', '$defs': dict(sorted(selected.items()))}

def encoded(value):
    return (json.dumps(value, indent=2) + '\n').encode()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh', action='store_true', help='Explicit network refresh of the versioned official source and extraction; review the diff')
    args = parser.parse_args()
    if args.refresh:
        for name in ['schema.ts', 'schema.json']:
            data = urlopen(BASE + name, timeout=30).read()
            (PIN / name).write_bytes(data)
        lock = {'version': '2025-11-25', 'sources': {name: {'url': BASE + name, 'sha256': digest((PIN / name).read_bytes())} for name in ['schema.ts', 'schema.json']}}
        (PIN / 'pin.json').write_bytes(encoded(lock))
        TARGET.write_bytes(encoded(extract(json.loads((PIN / 'schema.json').read_bytes()))))
    lock = json.loads((PIN / 'pin.json').read_text())
    for name, info in lock['sources'].items():
        if digest((PIN / name).read_bytes()) != info['sha256']:
            raise SystemExit('Pinned MCP source drift: ' + name)
    expected = encoded(extract(json.loads((PIN / 'schema.json').read_bytes())))
    if TARGET.read_bytes() != expected:
        raise SystemExit('MCP elicitation extraction drift; use --refresh explicitly and review')
    print('MCP 2025-11-25 source digests and elicitation extraction match (offline).')

if __name__ == '__main__':
    main()
